# Generated by Django 5.2.11 on 2026-04-13 03:13

import apps.analytics.models.report_definition
import apps.analytics.models.report_instance
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(help_text='Human-readable name for this report.', max_length=200, verbose_name='Report Name')),
                ('code', models.CharField(help_text='Unique code identifier for this report type.', max_length=100, verbose_name='Report Code')),
                ('description', models.TextField(blank=True, help_text='Detailed report description.', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this report type is currently available.', verbose_name='Active')),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('PURCHASE', 'Purchase'), ('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('FINANCIAL', 'Financial'), ('TAX', 'Tax & Compliance')], help_text='Report category for organisation.', max_length=20, verbose_name='Category')),
                ('default_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('HTML', 'HTML')], default='PDF', help_text='Default output format when generating this report.', max_length=10, verbose_name='Default Format')),
                ('available_filters', models.JSONField(blank=True, default=apps.analytics.models.report_definition._default_filters, help_text='JSON schema defining available filter parameters.', verbose_name='Available Filters')),
                ('required_permission', models.CharField(blank=True, help_text='Permission codename required to generate this report.', max_length=255, verbose_name='Required Permission')),
                ('allows_scheduling', models.BooleanField(default=True, help_text='Whether this report can be scheduled.', verbose_name='Allows Scheduling')),
                ('allows_export', models.BooleanField(default=True, help_text='Whether this report can be exported.', verbose_name='Allows Export')),
                ('max_date_range_days', models.IntegerField(blank=True, help_text='Maximum allowed date range in days. Null for unlimited.', null=True, verbose_name='Max Date Range (days)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order in UI. Lower numbers appear first.', verbose_name='Display Order')),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI display (e.g. fa-chart-line).', max_length=50, verbose_name='Icon')),
                ('help_text_content', models.TextField(blank=True, help_text='User-facing help text explaining report purpose.', verbose_name='Help Text')),
                ('estimated_time_seconds', models.IntegerField(default=60, help_text='Estimated generation time in seconds.', verbose_name='Estimated Time (seconds)')),
                ('tags', models.JSONField(blank=True, default=apps.analytics.models.report_definition._default_tags, help_text='Searchable tags for categorisation.', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Report Definition',
                'verbose_name_plural': 'Report Definitions',
                'ordering': ['category', 'order', 'name'],
                'permissions': [('view_sales_reports', 'Can view sales reports'), ('view_inventory_reports', 'Can view inventory reports'), ('view_purchase_reports', 'Can view purchase reports'), ('view_customer_reports', 'Can view customer reports'), ('view_staff_reports', 'Can view staff reports'), ('view_financial_reports', 'Can view financial reports'), ('view_tax_reports', 'Can view tax reports')],
                'indexes': [models.Index(fields=['category'], name='analytics_r_categor_01f4c4_idx'), models.Index(fields=['is_active'], name='analytics_r_is_acti_f44c2b_idx'), models.Index(fields=['code'], name='analytics_r_code_25fc40_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('filter_parameters', models.JSONField(blank=True, default=apps.analytics.models.report_instance._default_filter_params, help_text='Filter values used for this report generation.', verbose_name='Filter Parameters')),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('HTML', 'HTML')], default='PDF', help_text='Format of the generated report file.', max_length=10, verbose_name='Output Format')),
                ('output_file', models.FileField(blank=True, help_text='Generated report file.', null=True, upload_to='reports/%Y/%m/', verbose_name='Output File')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of the generated file in bytes.', null=True, verbose_name='File Size (bytes)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current status of report generation.', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, help_text='When generation started.', null=True, verbose_name='Started At')),
                ('generated_at', models.DateTimeField(blank=True, help_text='When generation completed.', null=True, verbose_name='Generated At')),
                ('generation_time_seconds', models.IntegerField(blank=True, help_text='Time taken to generate the report in seconds.', null=True, verbose_name='Generation Time (seconds)')),
                ('error_message', models.TextField(blank=True, help_text='Error details if generation failed.', verbose_name='Error Message')),
                ('report_definition', models.ForeignKey(help_text='The report definition that was generated.', on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='analytics.reportdefinition', verbose_name='Report Definition')),
                ('user', models.ForeignKey(blank=True, help_text='User who requested this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_instances', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Report Instance',
                'verbose_name_plural': 'Report Instances',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status'], name='analytics_r_status_837821_idx'), models.Index(fields=['report_definition', '-created_on'], name='analytics_r_report__c0f243_idx')],
            },
        ),
    ]
