# Generated by Django 5.2.11 on 2026-04-13 04:08

import apps.analytics.models.scheduled_report
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(db_index=True, help_text='User-assigned name for this saved report.', max_length=150, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('filters_config', models.JSONField(blank=True, default=dict, help_text='Saved filter parameters (date_range, category, etc).')),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('HTML', 'HTML')], default='PDF', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='If True, other users can view/use this saved report.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
                ('report_definition', models.ForeignKey(help_text='The base report definition.', on_delete=django.db.models.deletion.PROTECT, related_name='saved_reports', to='analytics.reportdefinition')),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'db_table': 'analytics_saved_report',
                'ordering': ['-created_on', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10)),
                ('time_of_day', models.TimeField(default=datetime.time(9, 0), help_text='Time to run the report (tenant timezone).')),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday .. 6=Sunday. Required for WEEKLY.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month (1-31). Required for MONTHLY.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('next_run', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_status', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recipients', models.JSONField(blank=True, default=apps.analytics.models.scheduled_report._default_recipients, help_text='List of email addresses.', validators=[apps.analytics.models.scheduled_report.validate_email_list])),
                ('email_subject', models.CharField(blank=True, help_text='Supports {report_name}, {date}.', max_length=200, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('attach_pdf', models.BooleanField(default=True)),
                ('include_csv', models.BooleanField(default=False)),
                ('include_excel', models.BooleanField(default=False)),
                ('cc_emails', models.JSONField(blank=True, default=apps.analytics.models.scheduled_report._default_recipients, validators=[apps.analytics.models.scheduled_report.validate_email_list])),
                ('bcc_emails', models.JSONField(blank=True, default=apps.analytics.models.scheduled_report._default_recipients, validators=[apps.analytics.models.scheduled_report.validate_email_list])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('last_report_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analytics.reportinstance')),
                ('saved_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='analytics.savedreport')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'db_table': 'analytics_scheduled_report',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recipients_count', models.IntegerField(default=0)),
                ('email_sent', models.BooleanField(default=False)),
                ('execution_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('report_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.reportinstance')),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='analytics.scheduledreport')),
            ],
            options={
                'verbose_name': 'Schedule History',
                'verbose_name_plural': 'Schedule Histories',
                'db_table': 'analytics_schedule_history',
                'ordering': ['-run_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['is_active', 'next_run'], name='idx_sched_active_next'),
        ),
        migrations.AddIndex(
            model_name='schedulehistory',
            index=models.Index(fields=['scheduled_report', 'run_at'], name='analytics_s_schedul_f6c77c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulehistory',
            index=models.Index(fields=['status'], name='analytics_s_status_69b1d5_idx'),
        ),
    ]
