# Generated by Django 5.2.11 on 2026-04-13 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_savedreport_scheduledreport_schedulehistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdefinition',
            name='sample_output_url',
            field=models.URLField(blank=True, help_text='Link to a sample report output for preview.', verbose_name='Sample Output URL'),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='access_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the report has been downloaded.', verbose_name='Access Count'),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='accessed_at',
            field=models.DateTimeField(blank=True, help_text='When the report was last downloaded.', null=True, verbose_name='Last Accessed'),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID of the Celery task for cancellation.', max_length=255, verbose_name='Celery Task ID'),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the report file will be eligible for deletion.', null=True, verbose_name='Expires At'),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='is_scheduled',
            field=models.BooleanField(default=False, help_text='Indicates if this report was triggered by a schedule.', verbose_name='Is Scheduled'),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='title',
            field=models.CharField(blank=True, help_text='User-friendly report title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='reportinstance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current status of report generation.', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['celery_task_id'], name='analytics_r_celery__db6d18_idx'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['expires_at'], name='analytics_r_expires_f3b277_idx'),
        ),
    ]
