# Generated by Django 5.2.11 on 2026-03-23 12:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_sp07_error_message_field'),
        ('purchases', '0007_sp11_deep_audit_fixes'),
        ('tenants', '0010_add_billing_fields'),
        ('vendors', '0010_sp10_audit_history_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('line_number', models.PositiveIntegerField(help_text='Line item sequence number')),
                ('vendor_sku', models.CharField(blank=True, help_text="Vendor's SKU/part number", max_length=100)),
                ('item_description', models.TextField(blank=True, help_text='Description of the item (auto-populated from product or manual)', max_length=1000)),
                ('quantity', models.PositiveIntegerField(help_text='Billed quantity')),
                ('quantity_ordered', models.PositiveIntegerField(blank=True, help_text='Quantity ordered from PO (for matching)', null=True)),
                ('quantity_received', models.PositiveIntegerField(blank=True, help_text='Quantity received from GRN (for matching)', null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original unit price from PO', max_digits=12, null=True)),
                ('billed_price', models.DecimalField(decimal_places=2, help_text="Price on the vendor's bill", max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate as a percentage (0-100)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed tax amount for this line', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed: (quantity * billed_price) + tax_amount', max_digits=12)),
                ('grn_line', models.ForeignKey(blank=True, help_text='Matched GRN line item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='purchases.grnlineitem')),
                ('po_line', models.ForeignKey(blank=True, help_text='Matched PO line item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='purchases.polineitem')),
                ('product', models.ForeignKey(blank=True, help_text='Product reference (optional for non-catalog items)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_line_items', to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Product variant reference (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_line_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Bill Line Item',
                'verbose_name_plural': 'Bill Line Items',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='BillSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('bill_number_prefix', models.CharField(default='BILL', help_text='Prefix for auto-generated bill numbers', max_length=10)),
                ('bill_number_sequence', models.PositiveIntegerField(default=1, help_text='Next bill sequence number')),
                ('bill_number_padding', models.PositiveSmallIntegerField(default=5, help_text='Zero-padding length for bill numbers')),
                ('include_year_in_number', models.BooleanField(default=True, help_text='Include year in bill number (BILL-2026-00001)')),
                ('require_approval', models.BooleanField(default=True, help_text='Require approval before payment')),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Bills above this amount require approval. 0 = all bills.', max_digits=12)),
                ('auto_approve_matched', models.BooleanField(default=False, help_text='Auto-approve perfectly matched bills')),
                ('quantity_tolerance_percentage', models.DecimalField(decimal_places=2, default=5, help_text='Acceptable quantity variance percentage', max_digits=5)),
                ('price_tolerance_percentage', models.DecimalField(decimal_places=2, default=2, help_text='Acceptable price variance percentage', max_digits=5)),
                ('default_payment_terms', models.PositiveIntegerField(default=30, help_text='Default payment terms in days')),
                ('allow_early_payment_discount', models.BooleanField(default=False, help_text='Enable early payment discount tracking')),
                ('early_payment_discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Discount percentage for early payment', max_digits=5, null=True)),
                ('early_payment_discount_days', models.PositiveIntegerField(blank=True, default=None, help_text='Days within which early payment discount applies', null=True)),
                ('require_po_reference', models.BooleanField(default=False, help_text='Require PO reference for manual bills')),
                ('enable_dispute_workflow', models.BooleanField(default=True, help_text='Enable bill dispute functionality')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Bill Settings',
                'verbose_name_plural': 'Bill Settings',
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('bill_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated bill number (BILL-YYYY-NNNNN)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('partial_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='draft', help_text='Current bill status', max_length=20)),
                ('vendor_invoice_number', models.CharField(blank=True, help_text="Vendor's own invoice/reference number", max_length=100)),
                ('bill_date', models.DateField(help_text="Date on the vendor's invoice")),
                ('received_date', models.DateField(help_text='Date the bill was received')),
                ('due_date', models.DateField(db_index=True, help_text='Payment due date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line item totals before tax and discount', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax amount', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Grand total (subtotal + tax - discount)', max_digits=12)),
                ('currency', models.CharField(default='LKR', help_text='Bill currency code', max_length=3)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid so far', max_digits=12)),
                ('payment_terms', models.CharField(choices=[('cia', 'Cash in Advance'), ('cod', 'Cash on Delivery'), ('net15', 'Net 15 Days'), ('net30', 'Net 30 Days'), ('net45', 'Net 45 Days'), ('net60', 'Net 60 Days'), ('net90', 'Net 90 Days'), ('custom', 'Custom')], default='net30', help_text='Payment terms for this bill', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the bill was approved', null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes visible to all')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes not shared with vendor')),
                ('dispute_reason', models.TextField(blank=True, help_text='Reason for disputing the bill', null=True)),
                ('attachment', models.FileField(blank=True, help_text='Scanned copy of vendor invoice', null=True, upload_to='vendor_bills/%Y/')),
                ('is_matched', models.BooleanField(default=False, help_text='Whether this bill has been matched to PO/GRN')),
                ('matched_at', models.DateTimeField(blank=True, help_text='When the bill was matched', null=True)),
                ('matching_variance', models.DecimalField(blank=True, decimal_places=2, help_text='Absolute variance amount from matching', max_digits=12, null=True)),
                ('matching_variance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Variance as a percentage of PO total', max_digits=5, null=True)),
                ('matching_status', models.CharField(choices=[('not_matched', 'Not Matched'), ('matched', 'Matched'), ('variance_within_tolerance', 'Variance Within Tolerance'), ('variance_exceeds_tolerance', 'Variance Exceeds Tolerance')], default='not_matched', help_text='Status of the 3-way matching process', max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this bill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bills', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this bill', on_delete=django.db.models.deletion.PROTECT, related_name='created_bills', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Associated purchase order (optional for manual bills)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='purchases.purchaseorder')),
                ('vendor', models.ForeignKey(help_text='Vendor who issued this bill', on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Bill',
                'verbose_name_plural': 'Vendor Bills',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('variance', 'Variance'), ('unmatched', 'Unmatched')], db_index=True, default='unmatched', help_text='Result of the matching process', max_length=20)),
                ('quantity_ordered', models.PositiveIntegerField(blank=True, help_text='Quantity from PO', null=True)),
                ('quantity_received', models.PositiveIntegerField(blank=True, help_text='Quantity from GRN', null=True)),
                ('quantity_billed', models.PositiveIntegerField(blank=True, help_text='Quantity from Bill', null=True)),
                ('quantity_variance', models.IntegerField(default=0, help_text='Variance in quantities')),
                ('po_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price from PO', max_digits=12, null=True)),
                ('grn_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price from GRN (if available)', max_digits=12, null=True)),
                ('billed_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price on the bill', max_digits=12, null=True)),
                ('price_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price variance amount', max_digits=12)),
                ('total_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total variance amount', max_digits=12)),
                ('is_within_tolerance', models.BooleanField(db_index=True, default=False, help_text='Whether the variance is within tolerance')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the variance was approved', null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Notes from variance approval')),
                ('matched_at', models.DateTimeField(auto_now_add=True, help_text='When the matching was performed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional matching metadata')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the variance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_matching_results', to=settings.AUTH_USER_MODEL)),
                ('bill_line', models.OneToOneField(help_text='The specific bill line item', on_delete=django.db.models.deletion.CASCADE, related_name='matching_result', to='vendor_bills.billlineitem')),
                ('grn_line', models.ForeignKey(blank=True, help_text='Matched GRN line item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_results', to='purchases.grnlineitem')),
                ('po_line', models.ForeignKey(blank=True, help_text='Matched PO line item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_results', to='purchases.polineitem')),
                ('vendor_bill', models.ForeignKey(help_text='The vendor bill being matched', on_delete=django.db.models.deletion.CASCADE, related_name='matching_results', to='vendor_bills.vendorbill')),
            ],
            options={
                'verbose_name': 'Matching Result',
                'verbose_name_plural': 'Matching Results',
                'ordering': ['-matched_at'],
            },
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='vendor_bill',
            field=models.ForeignKey(help_text='The vendor bill this line item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='vendor_bills.vendorbill'),
        ),
        migrations.CreateModel(
            name='BillHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('payment_recorded', 'Payment Recorded'), ('matched', 'Matched'), ('line_added', 'Line Added'), ('line_updated', 'Line Updated'), ('line_removed', 'Line Removed')], default='created', max_length=20)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of bill state at time of change for audit.')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_history_entries', to=settings.AUTH_USER_MODEL)),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='vendor_bills.vendorbill')),
            ],
            options={
                'verbose_name': 'Bill History',
                'verbose_name_plural': 'Bill History Entries',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('payment_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated payment number (PAY-YYYY-NNNNN)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('payment_date', models.DateField(db_index=True, help_text='Date the payment was made')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('online', 'Online Payment')], default='bank_transfer', help_text='Method of payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', help_text='Current payment status', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='External reference or transaction reference', max_length=100)),
                ('check_number', models.CharField(blank=True, help_text='Check/cheque number if payment method is check', max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for bank transfers', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number used for payment', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from bank or gateway', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the payment was approved', null=True)),
                ('is_advance', models.BooleanField(default=False, help_text='Whether this is an advance payment without a bill')),
                ('currency', models.CharField(default='LKR', help_text='Payment currency code', max_length=3)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who recorded this payment', on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='Vendor receiving this payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='vendors.vendor')),
                ('vendor_bill', models.ForeignKey(blank=True, help_text='Bill this payment applies to (null for advances)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vendor_bills.vendorbill')),
            ],
            options={
                'verbose_name': 'Vendor Payment',
                'verbose_name_plural': 'Vendor Payments',
                'ordering': ['-payment_date', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('scheduled_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='vendor_bills.vendorbill')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='vendor_bills.vendorpayment')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['status'], name='idx_vendorbill_status'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['due_date'], name='idx_vendorbill_due_date'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['bill_date'], name='idx_vendorbill_bill_date'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['status', 'vendor'], name='idx_status_vendor'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['status', 'due_date'], name='idx_status_due'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['vendor', 'bill_date'], name='idx_vendor_date'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', Decimal('0'))), name='vendorbill_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', Decimal('0'))), name='vendorbill_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', Decimal('0'))), name='vendorbill_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', Decimal('0'))), name='vendorbill_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', Decimal('0'))), name='vendorbill_amount_paid_non_negative'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['match_status'], name='idx_matchresult_status'),
        ),
        migrations.AddIndex(
            model_name='matchingresult',
            index=models.Index(fields=['is_within_tolerance'], name='idx_matchresult_tolerance'),
        ),
        migrations.AddConstraint(
            model_name='billlineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='billlineitem_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='billlineitem',
            constraint=models.CheckConstraint(condition=models.Q(('billed_price__gt', Decimal('0'))), name='billlineitem_billed_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='billlineitem',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', Decimal('0')), ('tax_rate__lte', Decimal('100'))), name='billlineitem_tax_rate_range'),
        ),
        migrations.AlterUniqueTogether(
            name='billlineitem',
            unique_together={('vendor_bill', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='billhistory',
            index=models.Index(fields=['vendor_bill'], name='idx_bh_vendor_bill'),
        ),
        migrations.AddIndex(
            model_name='billhistory',
            index=models.Index(fields=['created_on'], name='idx_bh_changed_at'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['status'], name='idx_vpay_status'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['payment_date'], name='idx_vpay_date'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['vendor', 'payment_date'], name='idx_vpay_vendor_date'),
        ),
        migrations.AddConstraint(
            model_name='vendorpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='vpay_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['status', 'scheduled_date'], name='idx_ps_status_date'),
        ),
        migrations.AddConstraint(
            model_name='paymentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_ps_amount_positive'),
        ),
    ]
