# Generated by Django 5.2.11 on 2026-02-21 12:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(help_text="Human-friendly name for the location (e.g. 'Main Warehouse').", max_length=255, unique=True, verbose_name='Location Name')),
                ('location_type', models.CharField(choices=[('warehouse', 'Central Warehouse'), ('store', 'Retail Store'), ('transit', 'In-Transit'), ('virtual', 'Virtual / Dropship')], db_index=True, default='warehouse', help_text='Type of location: warehouse, store, transit, or virtual.', max_length=20, verbose_name='Location Type')),
                ('address_line_1', models.CharField(blank=True, default='', help_text='Primary address line for physical locations.', max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, default='', help_text='Secondary address line (optional).', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, default='', help_text='City where the location is situated.', max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, default='', help_text='State or province of the location.', max_length=100, verbose_name='State / Province')),
                ('postal_code', models.CharField(blank=True, default='', help_text='Postal / ZIP code.', max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='Sri Lanka', help_text='Country where the location is situated.', max_length=100, verbose_name='Country')),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number for the location.', max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', help_text='Contact email for the location.', max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Controls whether this location is available for stock operations. Inactive locations retain their existing stock records but cannot be used for new transactions.', verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional internal notes about this location.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Stock Location',
                'verbose_name_plural': 'Stock Locations',
                'db_table': 'inventory_stock_location',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['location_type', 'is_active'], name='idx_location_type_active')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Current on-hand quantity. Adjusted via stock movements for full audit trail. Supports fractional units (e.g. kg).', max_digits=12, verbose_name='Quantity')),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, help_text='Low-stock threshold. A reorder alert is triggered when quantity drops below this value. Set to 0 to disable.', max_digits=12, verbose_name='Reorder Level')),
                ('last_counted', models.DateTimeField(blank=True, help_text='Date/time of the last physical stock count.', null=True, verbose_name='Last Counted')),
                ('product', models.ForeignKey(help_text='The product this stock record is for.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='products.product', verbose_name='Product')),
                ('location', models.ForeignKey(help_text='The location where this stock is held.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.stocklocation', verbose_name='Stock Location')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'db_table': 'inventory_stock',
                'ordering': ['product', 'location'],
                'indexes': [models.Index(fields=['product', 'location'], name='idx_stock_product_location')],
                'constraints': [models.UniqueConstraint(fields=('product', 'location'), name='uq_stock_product_location')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('movement_type', models.CharField(choices=[('in', 'Stock Received'), ('out', 'Stock Sold / Consumed'), ('transfer', 'Transfer Between Locations'), ('adjustment', 'Manual Adjustment'), ('return', 'Customer Return')], db_index=True, default='in', help_text='Type of stock movement: in, out, transfer, adjustment, or return.', max_length=20, verbose_name='Movement Type')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Amount moved (always positive). Direction is inferred from the movement_type.', max_digits=12, verbose_name='Quantity')),
                ('reference', models.CharField(blank=True, db_index=True, default='', help_text='Reference linking to the source document — order number, invoice ID, purchase order, or adjustment reason.', max_length=255, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional additional notes about this movement.', verbose_name='Notes')),
                ('destination_location', models.ForeignKey(blank=True, help_text='Destination location for transfer movements. Null for non-transfer movements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='inventory.stocklocation', verbose_name='Destination Location')),
                ('location', models.ForeignKey(help_text='The location where the movement occurs. For transfers, this is the source location.', on_delete=django.db.models.deletion.CASCADE, related_name='movements_from', to='inventory.stocklocation', verbose_name='Location')),
                ('performed_by', models.ForeignKey(blank=True, help_text='The user who performed this stock movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('product', models.ForeignKey(help_text='The product being moved.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'inventory_stock_movement',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['product', 'movement_type'], name='idx_movement_product_type'), models.Index(fields=['location', 'movement_type'], name='idx_movement_location_type'), models.Index(fields=['-created_on'], name='idx_movement_created')],
            },
        ),
    ]
