# Generated by Django 5.2.11 on 2026-03-13 20:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text='e.g., "Colombo Main Warehouse"', max_length=200, verbose_name='Warehouse Name')),
                ('code', models.CharField(help_text='Unique code like "WH-CMB-01". Stored uppercase.', max_length=50, unique=True, verbose_name='Warehouse Code')),
                ('warehouse_type', models.CharField(choices=[('main', 'Main Warehouse'), ('distribution', 'Distribution Center'), ('retail', 'Retail Store Warehouse'), ('returns', 'Returns Processing')], db_index=True, default='main', max_length=20, verbose_name='Warehouse Type')),
                ('address_line_1', models.CharField(help_text='Street address or P.O. Box', max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, default='', help_text='Apartment, suite, building, floor, etc.', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(help_text='e.g., Colombo, Kandy, Galle', max_length=100, verbose_name='City')),
                ('district', models.CharField(choices=[('colombo', 'Colombo'), ('gampaha', 'Gampaha'), ('kalutara', 'Kalutara'), ('kandy', 'Kandy'), ('matale', 'Matale'), ('nuwara_eliya', 'Nuwara Eliya'), ('galle', 'Galle'), ('matara', 'Matara'), ('hambantota', 'Hambantota'), ('jaffna', 'Jaffna'), ('kilinochchi', 'Kilinochchi'), ('mannar', 'Mannar'), ('vavuniya', 'Vavuniya'), ('mullaitivu', 'Mullaitivu'), ('batticaloa', 'Batticaloa'), ('ampara', 'Ampara'), ('trincomalee', 'Trincomalee'), ('kurunegala', 'Kurunegala'), ('puttalam', 'Puttalam'), ('anuradhapura', 'Anuradhapura'), ('polonnaruwa', 'Polonnaruwa'), ('badulla', 'Badulla'), ('monaragala', 'Monaragala'), ('ratnapura', 'Ratnapura'), ('kegalle', 'Kegalle')], db_index=True, max_length=50, verbose_name='District')),
                ('postal_code', models.CharField(blank=True, default='', help_text='Sri Lankan postal code (5 digits)', max_length=10, verbose_name='Postal Code')),
                ('phone', models.CharField(help_text='Format: +94 XX XXX XXXX', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, default='', help_text='Warehouse contact email', max_length=254, verbose_name='Email Address')),
                ('manager_name', models.CharField(blank=True, default='', help_text='Warehouse manager or supervisor', max_length=200, verbose_name='Manager Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Default warehouse for POS and automatic operations', verbose_name='Default Warehouse')),
                ('is_24_hours', models.BooleanField(default=False, verbose_name='24-Hour Operation')),
                ('opens_at', models.TimeField(blank=True, help_text='Warehouse opening time (Asia/Colombo)', null=True, verbose_name='Opens At')),
                ('closes_at', models.TimeField(blank=True, help_text='Warehouse closing time (Asia/Colombo)', null=True, verbose_name='Closes At')),
                ('breaks_start', models.TimeField(blank=True, null=True, verbose_name='Break Start')),
                ('breaks_end', models.TimeField(blank=True, null=True, verbose_name='Break End')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'inventory_warehouses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='idx_wh_status'), models.Index(fields=['warehouse_type'], name='idx_wh_type'), models.Index(fields=['district'], name='idx_wh_district'), models.Index(fields=['is_default'], name='idx_wh_default')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_warehouse_per_tenant')],
            },
        ),
    ]
