# Generated by Django 5.2.11 on 2026-03-13 20:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('location_type', models.CharField(choices=[('zone', 'Zone'), ('aisle', 'Aisle'), ('rack', 'Rack'), ('shelf', 'Shelf'), ('bin', 'Bin')], db_index=True, help_text='Hierarchy level: zone, aisle, rack, shelf, or bin.', max_length=20, verbose_name='Location Type')),
                ('name', models.CharField(help_text='e.g., "Storage Zone A", "Aisle 3", "Rack 2"', max_length=100, verbose_name='Location Name')),
                ('code', models.CharField(db_index=True, help_text='Unique code like "A03-R02-S04-B01".', max_length=50, verbose_name='Location Code')),
                ('barcode', models.CharField(blank=True, db_index=True, default='', help_text='Scannable barcode for this location.', max_length=100, verbose_name='Barcode')),
                ('description', models.TextField(blank=True, default='', help_text='Additional location details or instructions.', verbose_name='Description')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight capacity in kilograms.', max_digits=10, null=True, verbose_name='Max Weight (kg)')),
                ('max_volume', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum volume capacity in cubic metres.', max_digits=10, null=True, verbose_name='Max Volume (m³)')),
                ('max_items', models.PositiveIntegerField(blank=True, help_text='Maximum number of items/SKUs at this location.', null=True, verbose_name='Max Items')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Location is operational and can be used.', verbose_name='Active')),
                ('is_pickable', models.BooleanField(db_index=True, default=True, help_text='Location can be used for order picking.', verbose_name='Pickable')),
                ('is_receivable', models.BooleanField(db_index=True, default=True, help_text='Location can receive incoming goods.', verbose_name='Receivable')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent location in the hierarchy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.storagelocation', verbose_name='Parent Location')),
                ('warehouse', models.ForeignKey(help_text='Warehouse containing this location.', on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'db_table': 'inventory_storage_locations',
                'ordering': ['warehouse', 'code'],
                'indexes': [models.Index(fields=['warehouse', 'code'], name='idx_loc_wh_code'), models.Index(fields=['warehouse', 'location_type'], name='idx_loc_wh_type'), models.Index(fields=['warehouse', 'is_active'], name='idx_loc_wh_active')],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'code'), name='uq_storage_location_warehouse_code')],
            },
        ),
    ]
