# Generated by Django 5.2.11 on 2026-03-13 20:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_storage_location_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('scan_type', models.CharField(choices=[('RECEIVING', 'Receiving'), ('PICKING', 'Picking'), ('INVENTORY_COUNT', 'Inventory Count'), ('TRANSFER', 'Transfer'), ('INQUIRY', 'Inquiry')], db_index=True, max_length=20)),
                ('scanned_barcode', models.CharField(help_text='Raw barcode value as scanned (may include errors)', max_length=100)),
                ('success', models.BooleanField(db_index=True, default=True, help_text='True if the barcode resolved to a valid location')),
                ('device_id', models.CharField(blank=True, default='', help_text='Identifier of the scanning device or terminal', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Extra context (order_id, transfer_id, etc.)')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='inventory.storagelocation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barcode Scan',
                'verbose_name_plural': 'Barcode Scans',
                'db_table': 'inventory_barcode_scans',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['location', 'created_on'], name='inventory_b_locatio_72250f_idx'), models.Index(fields=['user', 'created_on'], name='inventory_b_user_id_114336_idx'), models.Index(fields=['scan_type', 'created_on'], name='inventory_b_scan_ty_1cd2cb_idx'), models.Index(fields=['success', 'created_on'], name='inventory_b_success_3600b3_idx')],
            },
        ),
    ]
