# Generated by Django 5.2.11 on 2026-03-13 20:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_barcode_scan_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last stock movement at this location.', null=True, verbose_name='Last Activity'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='utilization_status',
            field=models.CharField(choices=[('empty', 'Empty'), ('partial', 'Partial'), ('full', 'Full')], db_index=True, default='empty', max_length=10, verbose_name='Utilisation Status'),
        ),
        migrations.CreateModel(
            name='POSWarehouseMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('terminal_id', models.CharField(help_text='POS terminal identifier (e.g. POS-TERM-001)', max_length=50, unique=True)),
                ('terminal_location', models.CharField(blank=True, default='', help_text='Physical location of the POS device', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'POS Warehouse Mapping',
                'verbose_name_plural': 'POS Warehouse Mappings',
                'db_table': 'inventory_pos_warehouse_mappings',
            },
        ),
        migrations.CreateModel(
            name='WarehouseCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('max_item_capacity', models.PositiveIntegerField(default=0)),
                ('max_weight_capacity', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Maximum weight in kg', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_volume_capacity', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Maximum volume in m³', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_item_count', models.PositiveIntegerField(default=0)),
                ('current_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('current_volume', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Capacity',
                'verbose_name_plural': 'Warehouse Capacities',
                'db_table': 'inventory_warehouse_capacities',
            },
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short identifier, unique per warehouse', max_length=20)),
                ('purpose', models.CharField(choices=[('receiving', 'Receiving'), ('storage', 'Storage'), ('picking', 'Picking'), ('shipping', 'Shipping'), ('returns', 'Returns'), ('quarantine', 'Quarantine')], db_index=True, default='storage', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Zone',
                'verbose_name_plural': 'Warehouse Zones',
                'db_table': 'inventory_warehouse_zones',
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DefaultWarehouseConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('scope', models.CharField(choices=[('tenant_default', 'Tenant Default'), ('user_default', 'User Default')], db_index=True, default='tenant_default', max_length=20)),
                ('default_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.warehouse')),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for a tenant-level default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_configs', to=settings.AUTH_USER_MODEL)),
                ('default_picking_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehousezone')),
                ('default_receiving_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehousezone')),
            ],
            options={
                'verbose_name': 'Default Warehouse Config',
                'verbose_name_plural': 'Default Warehouse Configs',
                'db_table': 'inventory_default_warehouse_configs',
            },
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Operational zone this location belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='inventory.warehousezone', verbose_name='Zone'),
        ),
        migrations.CreateModel(
            name='TransferRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('transit_days', models.PositiveIntegerField(default=1, help_text='Estimated transit time in days')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('primary_carrier', models.CharField(blank=True, default='', help_text='Name of primary transport company', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_preferred', models.BooleanField(default=False, help_text='Flag this as the preferred route between these warehouses')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Flat estimated cost (LKR)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_per_m3', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fixed minimum charge (LKR)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='inventory.warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Transfer Route',
                'verbose_name_plural': 'Transfer Routes',
                'db_table': 'inventory_transfer_routes',
                'ordering': ['source_warehouse', 'destination_warehouse'],
                'indexes': [models.Index(fields=['source_warehouse', 'is_active'], name='inventory_t_source__ef5eb9_idx'), models.Index(fields=['destination_warehouse', 'is_active'], name='inventory_t_destina_93da78_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_warehouse', 'destination_warehouse'), name='uq_transfer_route_src_dst')],
            },
        ),
        migrations.AddIndex(
            model_name='warehousezone',
            index=models.Index(fields=['warehouse', 'purpose'], name='inventory_w_warehou_b8161b_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehousezone',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='uq_zone_warehouse_code'),
        ),
        migrations.AddConstraint(
            model_name='defaultwarehouseconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='uq_default_config_per_user'),
        ),
    ]
