# Generated by Django 5.2.11 on 2026-03-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_group_d_warehouse_operations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'ordering': ['warehouse', 'code'], 'permissions': [('can_deactivate_location', 'Can deactivate a storage location'), ('can_bulk_create_locations', 'Can bulk-create storage locations')], 'verbose_name': 'Storage Location', 'verbose_name_plural': 'Storage Locations'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'permissions': [('can_set_default_warehouse', 'Can set a warehouse as default'), ('can_deactivate_warehouse', 'Can deactivate a warehouse')], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='capacity_notes',
            field=models.TextField(blank=True, help_text='Additional notes about storage capacity or restrictions.', null=True, verbose_name='Capacity Notes'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='max_pallets',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of pallets at this location.', null=True, verbose_name='Max Pallets'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Scannable barcode for this location.', max_length=100, null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='description',
            field=models.TextField(blank=True, help_text='Additional location details or instructions.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='max_volume',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum volume capacity in cubic metres.', max_digits=10, null=True, verbose_name='Max Volume (m³)'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Apartment, suite, building, floor, etc.', max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, help_text='Warehouse contact email', max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Warehouse manager or supervisor', max_length=200, null=True, verbose_name='Manager Name'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Sri Lankan postal code (5 digits)', max_length=10, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode',), name='uq_storage_location_barcode'),
        ),
    ]
