# Generated by Django 5.2.11 on 2026-03-14 00:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_storagelocation_options_and_more'),
        ('products', '0014_sp07_error_message_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Current physical stock on hand.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantity reserved for pending orders but not yet fulfilled.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Reserved Quantity')),
                ('incoming_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Expected quantity from pending purchase orders.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Incoming Quantity')),
                ('reorder_point', models.DecimalField(decimal_places=3, default=10, help_text='Low stock threshold. Alerts trigger when available falls below this.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Reorder Point')),
                ('cost_per_unit', models.DecimalField(decimal_places=3, default=0, help_text='Weighted average cost per unit at this stock level.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cost Per Unit')),
                ('last_stock_update', models.DateTimeField(auto_now=True, help_text='Last time stock quantity was modified.', verbose_name='Last Stock Update')),
                ('location', models.ForeignKey(blank=True, help_text='Optional. Specific location within the warehouse. NULL means stock tracked at warehouse level only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_levels', to='inventory.storagelocation', verbose_name='Storage Location')),
                ('product', models.ForeignKey(help_text='Product being tracked.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_levels', to='products.product', verbose_name='Product')),
                ('variant', models.ForeignKey(blank=True, help_text='Optional. If the product has variants, specify which variant this stock level tracks. NULL means product-level tracking.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_levels', to='products.productvariant', verbose_name='Variant')),
                ('warehouse', models.ForeignKey(help_text='Warehouse where the stock is held.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock Level',
                'verbose_name_plural': 'Stock Levels',
                'db_table': 'inventory_stock_level',
                'ordering': ['product__name', 'warehouse__name'],
                'permissions': [('can_adjust_stock', 'Can adjust stock levels'), ('can_view_stock_levels', 'Can view stock levels'), ('can_approve_adjustments', 'Can approve stock adjustments')],
                'indexes': [models.Index(fields=['product', 'warehouse'], name='idx_stock_level_product_wh'), models.Index(fields=['warehouse', 'location'], name='idx_stock_level_wh_loc'), models.Index(fields=['last_stock_update'], name='idx_stock_level_last_update')],
                'constraints': [models.UniqueConstraint(fields=('product', 'variant', 'warehouse', 'location'), name='uq_stock_level_product_variant_wh_loc')],
            },
        ),
    ]
