# Generated by Django 5.2.11 on 2026-03-14 00:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_legacy_stock_movement'),
        ('products', '0014_sp07_error_message_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('movement_type', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('reserved', 'Reserved'), ('released', 'Released')], db_index=True, help_text='Type of stock movement.', max_length=20, verbose_name='Movement Type')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Amount moved (always positive — direction from movement_type).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantity')),
                ('reason', models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('damage', 'Damage'), ('theft', 'Theft'), ('correction', 'Correction'), ('expired', 'Expired'), ('production', 'Production'), ('initial', 'Initial Stock'), ('stock_take', 'Stock Take'), ('other', 'Other')], default='', help_text='Reason for this movement.', max_length=30, verbose_name='Reason')),
                ('movement_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the movement occurred.', verbose_name='Movement Date')),
                ('reference_type', models.CharField(blank=True, choices=[('order', 'Order'), ('purchase_order', 'Purchase Order'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('stock_take', 'Stock Take')], default='', help_text='Type of the source document (order, PO, adjustment, etc.).', max_length=30, verbose_name='Reference Type')),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', help_text='ID of the source document.', max_length=100, verbose_name='Reference ID')),
                ('reference_number', models.CharField(blank=True, default='', help_text='Human-readable reference number for display.', max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional context or notes about this movement.', verbose_name='Notes')),
                ('cost_per_unit', models.DecimalField(decimal_places=3, default=0, help_text='Cost per unit at the time of movement (for COGS).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cost Per Unit')),
                ('is_reversed', models.BooleanField(default=False, help_text='Whether this movement has been reversed.', verbose_name='Is Reversed')),
                ('reversed_at', models.DateTimeField(blank=True, help_text='When this movement was reversed.', null=True, verbose_name='Reversed At')),
                ('reversal_reason', models.CharField(blank=True, default='', help_text='Reason for reversing this movement.', max_length=255, verbose_name='Reversal Reason')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who performed this movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_location', models.ForeignKey(blank=True, help_text='Source storage location within the warehouse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='inventory.storagelocation', verbose_name='Source Location')),
                ('from_warehouse', models.ForeignKey(blank=True, help_text='Source warehouse. Required for STOCK_OUT, TRANSFER, RESERVED.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='inventory.warehouse', verbose_name='Source Warehouse')),
                ('original_movement', models.ForeignKey(blank=True, help_text='If this is a reversal, points to the original movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.stockmovement', verbose_name='Original Movement')),
                ('product', models.ForeignKey(help_text='Product being moved.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.product', verbose_name='Product')),
                ('reversed_by', models.ForeignKey(blank=True, help_text='The reversal movement that reversed this one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='inventory.stockmovement', verbose_name='Reversed By')),
                ('to_location', models.ForeignKey(blank=True, help_text='Destination storage location within the warehouse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='inventory.storagelocation', verbose_name='Destination Location')),
                ('to_warehouse', models.ForeignKey(blank=True, help_text='Destination warehouse. Required for STOCK_IN, TRANSFER, RELEASED.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='inventory.warehouse', verbose_name='Destination Warehouse')),
                ('variant', models.ForeignKey(blank=True, help_text='Optional variant for variant-level movement tracking.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'inventory_stock_movement',
                'ordering': ['-movement_date', '-created_on'],
                'permissions': [('can_create_movement', 'Can create stock movements'), ('can_reverse_movement', 'Can reverse stock movements'), ('can_view_movement_history', 'Can view movement history')],
                'indexes': [models.Index(fields=['product', 'movement_date'], name='idx_movement_product_date'), models.Index(fields=['from_warehouse', 'movement_date'], name='idx_movement_from_wh_date'), models.Index(fields=['to_warehouse', 'movement_date'], name='idx_movement_to_wh_date'), models.Index(fields=['movement_type', 'movement_date'], name='idx_movement_type_date'), models.Index(fields=['reference_type', 'reference_id'], name='idx_movement_reference')],
            },
        ),
    ]
