# Generated by Django 5.2.11 on 2026-03-14 00:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_sp09_stock_movement_model'),
        ('products', '0014_sp07_error_message_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('return_from_customer', 'Return from Customer'), ('return_to_supplier', 'Return to Supplier'), ('damage', 'Damage'), ('theft', 'Theft'), ('correction', 'Correction'), ('expired', 'Expired'), ('production', 'Production'), ('initial', 'Initial Stock'), ('stock_take', 'Stock Take'), ('found', 'Found'), ('lost', 'Lost'), ('transfer', 'Transfer'), ('write_off', 'Write-Off'), ('other', 'Other')], default='', help_text='Reason for this movement.', max_length=30, verbose_name='Reason'),
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(help_text='Descriptive name for this stock take.', max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('reference', models.CharField(db_index=True, help_text='Auto-generated reference (e.g. ST-2026-0001).', max_length=50, unique=True, verbose_name='Reference')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('counting', 'Counting'), ('review', 'Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('scope', models.CharField(choices=[('full', 'Full Count'), ('partial', 'Partial Count'), ('cycle', 'Cycle Count')], default='full', max_length=20, verbose_name='Scope')),
                ('is_blind_count', models.BooleanField(default=False, help_text='If True, counters cannot see expected quantities.', verbose_name='Blind Count')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('approval_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20, verbose_name='Approval Status')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total Items')),
                ('counted_items', models.PositiveIntegerField(default=0, verbose_name='Counted Items')),
                ('items_with_variance', models.PositiveIntegerField(default=0, verbose_name='Items with Variance')),
                ('total_variance_value', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15, verbose_name='Total Variance Value')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_takes', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stock_takes', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_takes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_takes', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock Take',
                'verbose_name_plural': 'Stock Takes',
                'db_table': 'inventory_stock_take',
                'ordering': ['-created_on'],
                'permissions': [('can_view_stocktake', 'Can view stock takes'), ('can_create_stocktake', 'Can create stock takes'), ('can_finalize_stocktake', 'Can finalize stock takes')],
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('expected_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15, verbose_name='Expected Quantity')),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Counted Quantity')),
                ('system_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='System quantity snapshot at count time.', max_digits=15, verbose_name='System Quantity')),
                ('variance_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15, verbose_name='Variance Quantity')),
                ('variance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Variance %')),
                ('cost_per_unit', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15, verbose_name='Cost Per Unit')),
                ('expected_value', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15, verbose_name='Expected Value')),
                ('counted_value', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15, verbose_name='Counted Value')),
                ('variance_value', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15, verbose_name='Variance Value')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('counted', 'Counted'), ('verified', 'Verified'), ('adjusted', 'Adjusted')], default='pending', max_length=20, verbose_name='Status')),
                ('count_sequence', models.PositiveIntegerField(default=0, verbose_name='Count Sequence')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Locked')),
                ('requires_recount', models.BooleanField(default=False, verbose_name='Requires Recount')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('discrepancy_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Discrepancy Reason')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='Counted At')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_stock_items', to=settings.AUTH_USER_MODEL, verbose_name='Counted By')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_take_items', to='inventory.storagelocation', verbose_name='Storage Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_items', to='products.product', verbose_name='Product')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake', verbose_name='Stock Take')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_items', to='products.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Stock Take Item',
                'verbose_name_plural': 'Stock Take Items',
                'db_table': 'inventory_stock_take_item',
                'ordering': ['count_sequence', 'product__name'],
            },
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['warehouse', 'status'], name='idx_st_warehouse_status'),
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['-created_on'], name='idx_st_created'),
        ),
        migrations.AddIndex(
            model_name='stocktakeitem',
            index=models.Index(fields=['stock_take', 'status'], name='idx_sti_take_status'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.UniqueConstraint(fields=('stock_take', 'product', 'variant', 'location'), name='uq_stock_take_product_variant_loc'),
        ),
    ]
