# Generated by Django 5.2.11 on 2026-03-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_sp09_stock_take_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'get_latest_by': 'movement_date', 'ordering': ['-movement_date', '-created_on'], 'permissions': [('can_create_movement', 'Can create stock movements'), ('can_reverse_movement', 'Can reverse stock movements'), ('can_approve_adjustment', 'Can approve stock adjustments'), ('can_view_movement_history', 'Can view movement history')], 'verbose_name': 'Stock Movement', 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('return_from_customer', 'Return from Customer'), ('return_to_supplier', 'Return to Supplier'), ('damage', 'Damage'), ('theft', 'Theft'), ('correction', 'Correction'), ('expired', 'Expired'), ('production', 'Production'), ('initial', 'Initial Stock'), ('stock_take', 'Stock Take'), ('found', 'Found'), ('lost', 'Lost'), ('transfer', 'Transfer'), ('write_off', 'Write-Off'), ('other', 'Other'), ('order_placed', 'Order Placed'), ('order_cancelled', 'Order Cancelled'), ('order_timeout', 'Order Timeout'), ('manual_release', 'Manual Release')], default='', help_text='Reason for this movement.', max_length=30, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('purchase_order', 'Purchase Order'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('stock_take', 'Stock Take'), ('manual', 'Manual')], default='', help_text='Type of the source document (order, PO, adjustment, etc.).', max_length=30, verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='User who reversed this movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_reversed', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By'),
        ),
    ]
