# Generated by Django 5.2.11 on 2026-03-14 08:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_sp09_fix_reversed_by_fk_to_user'),
        ('products', '0014_sp07_error_message_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='abc_classification',
            field=models.CharField(blank=True, default='', help_text='ABC classification for cycle counting priority (A/B/C).', max_length=1, verbose_name='ABC Classification'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='in_transit_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity currently in transit from inter-warehouse transfers.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='In Transit Quantity'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='last_counted_date',
            field=models.DateTimeField(blank=True, help_text='Last time this stock level was physically counted.', null=True, verbose_name='Last Counted Date'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, help_text='When the transfer was physically dispatched.', null=True, verbose_name='Dispatched At'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, help_text='User who dispatched this transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_dispatched', to=settings.AUTH_USER_MODEL, verbose_name='Dispatched By'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='When the transfer was physically received.', null=True, verbose_name='Received At'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='User who confirmed receipt of this transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_received', to=settings.AUTH_USER_MODEL, verbose_name='Received By'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reserved_until',
            field=models.DateTimeField(blank=True, help_text='Expiry time for reservation movements. After this time, reservation can be automatically released.', null=True, verbose_name='Reserved Until'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transit_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='', help_text='Tracking status for transfer movements in transit.', max_length=20, verbose_name='Transit Status'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='item_approval_level',
            field=models.CharField(blank=True, default='', help_text='Level of approval required (auto/manager/director).', max_length=20, verbose_name='Required Approval Level'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='item_approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', help_text="Approval status for this specific item's variance.", max_length=20, verbose_name='Item Approval Status'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='item_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Item Approved At'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='item_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_take_items', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='item_rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Item Rejection Reason'),
        ),
        migrations.CreateModel(
            name='CycleCountSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('abc_classification', models.CharField(choices=[('A', 'A - High Value / High Frequency'), ('B', 'B - Medium Value / Medium Frequency'), ('C', 'C - Low Value / Low Frequency')], default='C', help_text='Priority classification for cycle counting frequency.', max_length=1, verbose_name='ABC Classification')),
                ('count_interval_days', models.PositiveIntegerField(default=180, help_text='Number of days between cycle counts.', verbose_name='Count Interval (Days)')),
                ('last_count_date', models.DateField(blank=True, help_text='Date of the last completed cycle count.', null=True, verbose_name='Last Count Date')),
                ('next_count_date', models.DateField(help_text='Date when the next cycle count is due.', verbose_name='Next Count Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Status')),
                ('last_stock_take', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_schedule', to='inventory.stocktake', verbose_name='Last Stock Take')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_schedules', to='products.product', verbose_name='Product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_schedules', to='products.productvariant', verbose_name='Variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_schedules', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Cycle Count Schedule',
                'verbose_name_plural': 'Cycle Count Schedules',
                'db_table': 'inventory_cycle_count_schedule',
                'ordering': ['next_count_date', 'abc_classification'],
                'indexes': [models.Index(fields=['next_count_date', 'status'], name='idx_cycle_schedule_next_date'), models.Index(fields=['warehouse', 'abc_classification'], name='idx_cycle_schedule_wh_abc')],
                'constraints': [models.UniqueConstraint(fields=('product', 'variant', 'warehouse'), name='uq_cycle_schedule_product_variant_wh')],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('lot_number', models.CharField(db_index=True, help_text='Unique identifier for this lot/batch.', max_length=100, verbose_name='Lot Number')),
                ('original_quantity', models.DecimalField(decimal_places=3, help_text='Quantity originally received in this lot.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Original Quantity')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, help_text='Quantity remaining in this lot.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Remaining Quantity')),
                ('cost_per_unit', models.DecimalField(decimal_places=3, default=0, help_text='Cost per unit for this lot.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cost Per Unit')),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date this lot was received.', verbose_name='Received Date')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date for this lot (if perishable).', null=True, verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('depleted', 'Depleted'), ('expired', 'Expired'), ('on_hold', 'On Hold')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='products.product', verbose_name='Product')),
                ('source_movement', models.ForeignKey(blank=True, help_text='The stock-in movement that created this lot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lots', to='inventory.stockmovement', verbose_name='Source Movement')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='products.productvariant', verbose_name='Variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock Lot',
                'verbose_name_plural': 'Stock Lots',
                'db_table': 'inventory_stock_lot',
                'ordering': ['received_date'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'status'], name='idx_lot_product_wh_status'), models.Index(fields=['expiry_date'], name='idx_lot_expiry_date')],
                'constraints': [models.UniqueConstraint(fields=('lot_number', 'product', 'warehouse'), name='uq_stock_lot_number_product_wh')],
            },
        ),
    ]
