# Generated by Django 5.2.11 on 2026-03-14 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_sp10_stock_alerts_reordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockconfig',
            name='alert_on_critical_stock',
            field=models.BooleanField(blank=True, help_text='Override critical stock alerts. None = inherit.', null=True),
        ),
        migrations.AddField(
            model_name='productstockconfig',
            name='alert_on_low_stock',
            field=models.BooleanField(blank=True, help_text='Override low stock alerts. None = inherit.', null=True),
        ),
        migrations.AddField(
            model_name='productstockconfig',
            name='alert_on_out_of_stock',
            field=models.BooleanField(blank=True, help_text='Override out of stock alerts. None = inherit.', null=True),
        ),
        migrations.AddField(
            model_name='productstockconfig',
            name='calculated_reorder_point',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Auto-calculated reorder point from sales velocity.', null=True),
        ),
        migrations.AlterField(
            model_name='productstockconfig',
            name='safety_stock_days',
            field=models.PositiveIntegerField(default=7, help_text='Days of safety stock to maintain.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
