# Generated by Django 5.2.11 on 2026-03-14 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_sp10_group_a_audit_fixes'),
        ('products', '0014_sp07_error_message_field'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLeadTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_id', models.UUIDField(blank=True, help_text='Reference to the purchase order.', null=True)),
                ('ordered_date', models.DateField(help_text='Date the PO was placed.')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Original expected delivery date.', null=True)),
                ('actual_delivery_date', models.DateField(blank=True, help_text='Actual date goods were received.', null=True)),
                ('days_taken', models.PositiveIntegerField(blank=True, editable=False, help_text='Actual days from order to delivery.', null=True)),
                ('days_late', models.IntegerField(default=0, editable=False, help_text='Days late vs expected (negative = early).')),
                ('on_time', models.BooleanField(default=True, editable=False, help_text='Whether delivery was on time.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text='Specific product (null for general supplier tracking).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_time_logs', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_time_logs', to='vendors.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Lead Time Log',
                'verbose_name_plural': 'Supplier Lead Time Logs',
                'db_table': 'inventory_supplier_lead_time_log',
                'ordering': ['-ordered_date'],
                'indexes': [models.Index(fields=['supplier', '-ordered_date'], name='inventory_s_supplie_9d521c_idx'), models.Index(fields=['product', 'supplier'], name='inventory_s_product_e9ec92_idx')],
            },
        ),
    ]
