export const AUTH_TEST_IDS = {
  loginForm: 'login-form',
  loginEmail: 'login-email',
  loginPassword: 'login-password',
  loginSubmit: 'login-submit',
  loginRememberMe: 'login-remember-me',
  registerForm: 'register-form',
  registerEmail: 'register-email',
  registerPhone: 'register-phone',
  registerFirstName: 'register-first-name',
  registerLastName: 'register-last-name',
  registerPassword: 'register-password',
  registerConfirmPassword: 'register-confirm-password',
  registerTerms: 'register-terms',
  registerSubmit: 'register-submit',
  forgotPasswordForm: 'forgot-password-form',
  forgotPasswordEmail: 'forgot-password-email',
  forgotPasswordSubmit: 'forgot-password-submit',
  otpInput: 'otp-input',
  otpSubmit: 'otp-submit',
  resetPasswordForm: 'reset-password-form',
  resetPasswordNew: 'reset-password-new',
  resetPasswordConfirm: 'reset-password-confirm',
  resetPasswordSubmit: 'reset-password-submit',
  socialGoogle: 'social-google',
  socialFacebook: 'social-facebook',
  logoutButton: 'logout-button',
} as const;
