# Generated by Django 5.2.11 on 2026-02-21 12:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('employee_number', models.CharField(db_index=True, help_text='Unique employee identifier within the tenant.', max_length=50, unique=True, verbose_name='Employee Number')),
                ('first_name', models.CharField(help_text="Employee's first name.", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Employee's last name.", max_length=100, verbose_name='Last Name')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('warehouse', 'Warehouse'), ('accountant', 'Accountant')], db_index=True, default='cashier', help_text='Staff access level. Maps to permissions: admin (full), manager (management), cashier (POS), warehouse (inventory), accountant (accounting).', max_length=20, verbose_name='Role')),
                ('email', models.EmailField(blank=True, default='', help_text="Employee's work email address.", max_length=254, verbose_name='Work Email')),
                ('phone', models.CharField(blank=True, default='', help_text='Primary phone number. Format: +94 XX XXX XXXX.', max_length=20, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, default='', help_text='Mobile phone number. Format: +94 XX XXX XXXX.', max_length=20, verbose_name='Mobile')),
                ('date_of_birth', models.DateField(blank=True, help_text="Employee's date of birth.", null=True, verbose_name='Date of Birth')),
                ('hire_date', models.DateField(blank=True, db_index=True, help_text='Date the employee joined the organisation.', null=True, verbose_name='Hire Date')),
                ('termination_date', models.DateField(blank=True, help_text='Date the employee left (if applicable).', null=True, verbose_name='Termination Date')),
                ('department', models.CharField(blank=True, default='', help_text='Department or team name.', max_length=100, verbose_name='Department')),
                ('position', models.CharField(blank=True, default='', help_text='Job title or position.', max_length=100, verbose_name='Position')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='Current employment status. Affects system access.', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about this employee.', verbose_name='Notes')),
                ('user', models.OneToOneField(blank=True, help_text='The user account linked to this employee. Tenant user is defined in the platform app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'hr_employee',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['role', 'status'], name='idx_employee_role_status'), models.Index(fields=['last_name', 'first_name'], name='idx_employee_name'), models.Index(fields=['status'], name='idx_employee_status')],
            },
        ),
    ]
