# Generated by Django 5.2.11 on 2026-03-24 09:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        ('organization', '0004_departmentmember_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'Regular Day Shift').", max_length=100)),
                ('code', models.CharField(db_index=True, help_text="Unique shift code (e.g., 'SHF-0001').", max_length=20, unique=True)),
                ('shift_type', models.CharField(choices=[('regular', 'Regular'), ('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night'), ('flexible', 'Flexible')], db_index=True, default='regular', help_text='Type of shift.', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default shift for the tenant.')),
                ('start_time', models.TimeField(help_text='Shift start time.')),
                ('end_time', models.TimeField(help_text='Shift end time.')),
                ('break_start', models.TimeField(blank=True, help_text='Break start time.', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Break end time.', null=True)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total work hours (auto-calculated if blank).', max_digits=4, null=True)),
                ('break_duration_minutes', models.PositiveIntegerField(default=0, help_text='Break duration in minutes (auto-calculated if break times set).')),
                ('late_grace_minutes', models.PositiveIntegerField(default=15, help_text='Minutes allowed before marking as late.')),
                ('early_leave_grace_minutes', models.PositiveIntegerField(default=10, help_text='Minutes allowed before marking as early departure.')),
                ('overtime_start_after', models.DecimalField(decimal_places=2, default=8.5, help_text='Overtime begins after this many hours worked.', max_digits=4)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Pay multiplier for overtime hours.', max_digits=3)),
                ('min_hours_for_half_day', models.DecimalField(decimal_places=2, default=4.0, help_text='Minimum hours to count as half-day attendance.', max_digits=4)),
                ('min_hours_for_full_day', models.DecimalField(decimal_places=2, default=7.5, help_text='Minimum hours to count as full-day attendance.', max_digits=4)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='idx_shift_code'), models.Index(fields=['shift_type'], name='idx_shift_type'), models.Index(fields=['status'], name='idx_shift_status')],
            },
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text='Descriptive name for this schedule.', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active.')),
                ('priority', models.PositiveIntegerField(default=50, help_text='Priority for conflict resolution (higher = higher priority).')),
                ('effective_from', models.DateField(help_text='Schedule effective start date.')),
                ('effective_to', models.DateField(blank=True, help_text='Schedule effective end date (null = ongoing).', null=True)),
                ('is_recurring', models.BooleanField(default=True, help_text='Whether this is a recurring weekly schedule.')),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_schedules', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department for department-wide schedule (null for individual).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to='organization.department')),
                ('employee', models.ForeignKey(blank=True, help_text='Employee for individual schedule (null for department-wide).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to='employees.employee')),
                ('shift', models.ForeignKey(help_text='The shift assigned by this schedule.', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='attendance.shift')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['employee', 'effective_from'], name='idx_schedule_emp_from'), models.Index(fields=['department', 'effective_from'], name='idx_schedule_dept_from'), models.Index(fields=['is_active'], name='idx_schedule_active')],
            },
        ),
    ]
