# Generated by Django 5.2.11 on 2026-03-24 09:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial_shift_schedule'),
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('date', models.DateField(db_index=True, help_text='Date of attendance (one record per employee per day).')),
                ('clock_in', models.DateTimeField(blank=True, help_text='Clock-in timestamp.', null=True)),
                ('clock_out', models.DateTimeField(blank=True, help_text='Clock-out timestamp.', null=True)),
                ('clock_in_method', models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('biometric', 'Biometric'), ('manual', 'Manual'), ('import', 'Import')], default='web', help_text='Method used for clock-in.', max_length=20)),
                ('clock_out_method', models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('biometric', 'Biometric'), ('manual', 'Manual'), ('import', 'Import')], default='web', help_text='Method used for clock-out.', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('weekend', 'Weekend')], db_index=True, default='present', help_text='Attendance status for the day.', max_length=20)),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total work hours including overtime.', max_digits=5)),
                ('break_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total break hours taken.', max_digits=4)),
                ('effective_hours', models.DecimalField(decimal_places=2, default=0, help_text='Effective work hours (work_hours - break_hours).', max_digits=5)),
                ('late_minutes', models.PositiveIntegerField(default=0, help_text='Minutes late beyond grace period.')),
                ('early_departure_minutes', models.PositiveIntegerField(default=0, help_text='Minutes of early departure beyond grace period.')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours worked.', max_digits=4)),
                ('overtime_approved', models.BooleanField(default=False, help_text='Whether overtime has been approved.')),
                ('clock_in_location', models.JSONField(blank=True, help_text='GPS location data for clock-in.', null=True)),
                ('clock_out_location', models.JSONField(blank=True, help_text='GPS location data for clock-out.', null=True)),
                ('clock_in_ip', models.GenericIPAddressField(blank=True, help_text='IP address for web-based clock-in.', null=True)),
                ('clock_out_ip', models.GenericIPAddressField(blank=True, help_text='IP address for web-based clock-out.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes for the attendance record.')),
                ('is_regularized', models.BooleanField(default=False, help_text='Whether this record has been regularized.')),
                ('employee', models.ForeignKey(help_text='Employee this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('regularized_by', models.ForeignKey(blank=True, help_text='User who approved the regularization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularized_attendance', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, help_text='The shift this record is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.shift')),
            ],
            options={
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='idx_att_emp_date'), models.Index(fields=['date'], name='idx_att_date'), models.Index(fields=['status'], name='idx_att_status'), models.Index(fields=['employee', 'status'], name='idx_att_emp_status')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
