# Generated by Django 5.2.11 on 2026-03-24 10:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_record'),
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('original_clock_in', models.DateTimeField(blank=True, help_text='Original clock-in time before correction.', null=True)),
                ('original_clock_out', models.DateTimeField(blank=True, help_text='Original clock-out time before correction.', null=True)),
                ('corrected_clock_in', models.DateTimeField(blank=True, help_text='Requested corrected clock-in time.', null=True)),
                ('corrected_clock_out', models.DateTimeField(blank=True, help_text='Requested corrected clock-out time.', null=True)),
                ('reason', models.TextField(help_text='Reason for the regularization request.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_regularizations', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(help_text='The attendance record to correct.', on_delete=django.db.models.deletion.CASCADE, related_name='regularizations', to='attendance.attendancerecord')),
                ('employee', models.ForeignKey(help_text='Employee requesting the correction.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_regularizations', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['employee', 'status'], name='idx_reg_emp_status'), models.Index(fields=['status'], name='idx_reg_status')],
            },
        ),
    ]
