# Generated by Django 5.2.11 on 2026-03-24 10:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_regularization'),
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        ('tenants', '0010_add_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('default_late_grace_minutes', models.PositiveIntegerField(default=15, help_text='Default minutes of grace for late arrival.')),
                ('default_early_leave_grace_minutes', models.PositiveIntegerField(default=10, help_text='Default minutes of grace for early departure.')),
                ('require_overtime_approval', models.BooleanField(default=True, help_text='Whether overtime requires prior approval.')),
                ('max_overtime_hours_per_day', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('max_overtime_hours_per_month', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('weekend_overtime_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('holiday_overtime_multiplier', models.DecimalField(decimal_places=2, default=2.5, max_digits=3)),
                ('enable_geofencing', models.BooleanField(default=False, help_text='Whether GPS geofencing is enabled for check-in.')),
                ('geofence_radius_meters', models.PositiveIntegerField(default=200)),
                ('office_locations', models.JSONField(blank=True, default=dict, help_text='JSON list of office locations with lat/lng/radius.')),
                ('auto_clock_out_time', models.TimeField(blank=True, help_text='Auto clock-out time for forgotten punch-outs (e.g., 23:00).', null=True)),
                ('mark_absent_after_hours', models.PositiveIntegerField(default=4, help_text='Hours after shift start to mark absent if no clock-in.')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('date', models.DateField(db_index=True, help_text='Date of overtime work.')),
                ('planned_hours', models.DecimalField(decimal_places=2, help_text='Planned overtime hours.', max_digits=4)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Actual overtime hours worked.', max_digits=4, null=True)),
                ('reason', models.TextField(help_text='Reason for the overtime request.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_requests', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests', to='attendance.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='idx_ot_emp_date'), models.Index(fields=['status'], name='idx_ot_status')],
            },
        ),
    ]
