# Generated by Django 5.2.11 on 2026-03-24 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_overtime_settings'),
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='auto_absence_marking_enabled',
            field=models.BooleanField(default=True, help_text='Whether automatic absence marking is enabled.'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='auto_approve_overtime_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Auto-approve overtime under this many minutes (0 = disabled).'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='auto_clock_out_enabled',
            field=models.BooleanField(default=True, help_text='Whether auto clock-out is enabled.'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='overtime_multiplier_normal',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Standard overtime multiplier (e.g. 1.5x).', max_digits=3),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='strict_geofencing',
            field=models.BooleanField(default=False, help_text='Block check-in outside geofence (True) or just flag it (False).'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='overtime_approved',
            field=models.BooleanField(default=None, help_text='Overtime approval status: None=pending, True=approved, False=rejected.', null=True),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('work_hours__gte', 0), ('work_hours__lte', 24)), name='check_work_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('break_hours__gte', 0)), name='check_break_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('effective_hours__gte', 0)), name='check_effective_hours_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('overtime_hours__gte', 0)), name='check_overtime_hours_nonneg'),
        ),
    ]
