# Generated by Django 5.2.11 on 2026-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesettings_auto_absence_marking_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='request_number',
            field=models.CharField(blank=True, help_text='Auto-generated request number (OT-YYYYMMDD-NNNN).', max_length=20, unique=True),
        ),
    ]
