# Generated by Django 5.2.11 on 2026-03-23 05:38

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0015_sp10_group_d_supplier_lead_time'),
        ('vendors', '0010_sp10_audit_history_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('po_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated PO number (PO-YYYY-NNNNN)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Vendor'), ('acknowledged', 'Acknowledged'), ('partial_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('vendor_reference', models.CharField(blank=True, default='', help_text="Vendor's own order/reference number", max_length=100)),
                ('order_date', models.DateField(default=datetime.date.today, help_text='Date the PO was created')),
                ('expected_delivery_date', models.DateField(blank=True, db_index=True, help_text='Expected delivery date from vendor', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When vendor acknowledged the order', null=True)),
                ('received_at', models.DateTimeField(blank=True, help_text='When all items were received', null=True)),
                ('ship_to_address', models.TextField(blank=True, default='', help_text='Delivery address')),
                ('shipping_method', models.CharField(blank=True, default='', help_text='Transport method (e.g. Ground, Air Freight)', max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping charges', max_digits=10)),
                ('carrier', models.CharField(blank=True, default='', help_text='Shipping company name', max_length=100)),
                ('tracking_number', models.CharField(blank=True, default='', help_text='Shipment tracking ID', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line item totals', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Order-level discount (monetary)', max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Order-level discount (percentage)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Grand total', max_digits=12)),
                ('currency', models.CharField(default='LKR', help_text='ISO currency code', max_length=3)),
                ('payment_terms', models.CharField(blank=True, default='', help_text='Payment terms description (e.g. Net 30)', max_length=50)),
                ('payment_terms_days', models.IntegerField(blank=True, help_text='Days until payment due', null=True)),
                ('payment_due_date', models.DateField(blank=True, help_text='Payment deadline', null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payments made', max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('vendor_notes', models.TextField(blank=True, default='')),
                ('delivery_instructions', models.TextField(blank=True, default='')),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, default='')),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='purchase_orders/pdfs/%Y/%m/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_version', models.IntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('receiving_warehouse', models.ForeignKey(blank=True, help_text='Destination warehouse for receiving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse')),
                ('vendor', models.ForeignKey(help_text='Supplier for this PO', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status'], name='idx_po_status'), models.Index(fields=['order_date'], name='idx_po_order_date'), models.Index(fields=['expected_delivery_date'], name='idx_po_exp_delivery'), models.Index(fields=['status', 'vendor'], name='idx_po_status_vendor'), models.Index(fields=['status', 'order_date'], name='idx_po_status_date'), models.Index(fields=['vendor', 'order_date'], name='idx_po_vendor_date'), models.Index(fields=['status', 'expected_delivery_date'], name='idx_po_status_exp_del'), models.Index(fields=['payment_status'], name='idx_po_payment_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='po_subtotal_non_negative'), models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='po_tax_non_negative'), models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='po_total_non_negative'), models.CheckConstraint(condition=models.Q(('shipping_cost__gte', 0)), name='po_shipping_non_negative'), models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='po_discount_non_negative'), models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='po_amount_paid_non_negative'), models.CheckConstraint(condition=models.Q(('pdf_version__gte', 1)), name='po_pdf_version_positive')],
            },
        ),
    ]
