# Generated by Django 5.2.11 on 2026-03-23 05:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_sp10_group_d_supplier_lead_time'),
        ('products', '0014_sp07_error_message_field'),
        ('purchases', '0001_sp11_initial_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('vendor_sku', models.CharField(blank=True, default='', max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True, default='')),
                ('is_service', models.BooleanField(default=False)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('quantity_rejected', models.PositiveIntegerField(default=0)),
                ('quantity_cancelled', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('receiving_location', models.CharField(blank=True, default='', max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_line_items', to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchases.purchaseorder')),
                ('receiving_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_line_items', to='inventory.warehouse')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_line_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'PO Line Item',
                'verbose_name_plural': 'PO Line Items',
                'ordering': ['line_number'],
                'indexes': [models.Index(fields=['status'], name='idx_poli_status'), models.Index(fields=['product'], name='idx_poli_product')],
                'unique_together': {('purchase_order', 'line_number')},
            },
        ),
    ]
