# Generated by Django 5.2.11 on 2026-03-23 06:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_sp11_po_line_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('po_number_prefix', models.CharField(default='PO', help_text='Prefix for auto-generated PO numbers', max_length=10)),
                ('requires_approval_above', models.DecimalField(decimal_places=2, default=0, help_text='POs above this amount require approval. 0 = no approval required.', max_digits=12)),
                ('default_payment_terms', models.CharField(blank=True, default='Net 30', max_length=50)),
                ('default_payment_terms_days', models.PositiveIntegerField(default=30)),
                ('default_currency', models.CharField(default='LKR', max_length=3)),
                ('auto_send_email', models.BooleanField(default=False, help_text='Automatically send PO to vendor on approval/send')),
            ],
            options={
                'verbose_name': 'PO Settings',
                'verbose_name_plural': 'PO Settings',
            },
        ),
        migrations.CreateModel(
            name='POHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_history_entries', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO History',
                'verbose_name_plural': 'PO History Entries',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['purchase_order'], name='idx_poh_po'), models.Index(fields=['created_on'], name='idx_poh_changed_at')],
            },
        ),
    ]
