# Generated by Django 5.2.11 on 2026-03-23 06:17

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_sp11_po_history_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('grn_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated GRN number (GRN-YYYY-NNNNN)', max_length=50, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_note_number', models.CharField(blank=True, default='', help_text="Supplier's delivery note reference", max_length=100)),
                ('carrier', models.CharField(blank=True, default='', max_length=100)),
                ('delivery_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('inspection_status', models.CharField(choices=[('pending', 'Pending Inspection'), ('passed', 'Passed'), ('failed', 'Failed'), ('partial', 'Partial Pass')], default='pending', max_length=20)),
                ('inspection_notes', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='purchases.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='GRNLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('quantity_received', models.PositiveIntegerField(help_text='Quantity accepted in this receipt')),
                ('quantity_rejected', models.PositiveIntegerField(default=0, help_text='Quantity rejected in this receipt')),
                ('condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('defective', 'Defective')], default='good', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchases.goodsreceipt')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_line_items', to='purchases.polineitem')),
            ],
            options={
                'verbose_name': 'GRN Line Item',
                'verbose_name_plural': 'GRN Line Items',
                'ordering': ['po_line'],
            },
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['grn_number'], name='idx_grn_number'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['purchase_order'], name='idx_grn_po'),
        ),
    ]
