# Generated by Django 5.2.11 on 2026-03-23 06:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_sp11_grn_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='POTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_phone', models.CharField(blank=True, default='', max_length=20)),
                ('company_email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='po_templates/')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#666666', max_length=7)),
                ('font_family', models.CharField(default='Helvetica', max_length=50)),
                ('show_logo', models.BooleanField(default=True)),
                ('footer_text', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PO Template',
                'verbose_name_plural': 'PO Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
