# Generated by Django 5.2.11 on 2026-03-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_sp10_group_d_supplier_lead_time'),
        ('purchases', '0005_sp11_po_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polineitem',
            name='receiving_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_line_items', to='inventory.storagelocation'),
        ),
        migrations.AlterField(
            model_name='polineitem',
            name='receiving_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_line_items', to='inventory.warehouse'),
        ),
    ]
