# Generated by Django 5.2.11 on 2026-03-23 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_sp10_group_d_supplier_lead_time'),
        ('purchases', '0006_sp11_fix_line_item_warehouse'),
        ('tenants', '0010_add_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grnlineitem',
            options={'ordering': ['line_number', 'po_line'], 'verbose_name': 'GRN Line Item', 'verbose_name_plural': 'GRN Line Items'},
        ),
        migrations.AlterModelOptions(
            name='potemplate',
            options={'ordering': ['-is_default', 'template_name'], 'verbose_name': 'PO Template', 'verbose_name_plural': 'PO Templates'},
        ),
        migrations.RenameField(
            model_name='potemplate',
            old_name='name',
            new_name='template_name',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='delivery_time',
            field=models.TimeField(blank=True, help_text='Time of delivery', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='driver_name',
            field=models.CharField(blank=True, default='', help_text='Name of delivery driver', max_length=100),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='inspected_at',
            field=models.DateTimeField(blank=True, help_text='When the inspection was performed', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='inspected_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_goods_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='inspection_passed',
            field=models.BooleanField(blank=True, help_text='Whether the overall inspection passed', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='GRN lifecycle status', max_length=20),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', help_text='Vehicle/truck registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='line_number',
            field=models.PositiveIntegerField(default=0, help_text='Line item sequence number within the GRN'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='quality_notes',
            field=models.TextField(blank=True, default='', help_text='Quality inspection notes'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='receiving_location',
            field=models.ForeignKey(blank=True, help_text='Storage location where items were placed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_line_items', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='receiving_warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where items were received into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_line_items', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='requires_followup',
            field=models.BooleanField(default=False, help_text='Whether this item requires follow-up action'),
        ),
        migrations.AddField(
            model_name='pohistory',
            name='data_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of PO state at time of change for audit.'),
        ),
        migrations.AddField(
            model_name='posettings',
            name='allow_partial_receiving',
            field=models.BooleanField(default=True, help_text='Allow partial receiving on purchase orders'),
        ),
        migrations.AddField(
            model_name='posettings',
            name='auto_close_on_full_receive',
            field=models.BooleanField(default=False, help_text='Automatically close PO when fully received'),
        ),
        migrations.AddField(
            model_name='posettings',
            name='default_shipping_method',
            field=models.CharField(blank=True, default='', help_text='Default shipping method for new POs', max_length=100),
        ),
        migrations.AddField(
            model_name='posettings',
            name='grn_number_prefix',
            field=models.CharField(default='GRN', help_text='Prefix for auto-generated GRN numbers', max_length=10),
        ),
        migrations.AddField(
            model_name='posettings',
            name='grn_number_sequence',
            field=models.PositiveIntegerField(default=1, help_text='Next GRN sequence number'),
        ),
        migrations.AddField(
            model_name='posettings',
            name='notify_on_acknowledgment',
            field=models.BooleanField(default=True, help_text='Send notification when vendor acknowledges PO'),
        ),
        migrations.AddField(
            model_name='posettings',
            name='notify_on_approval',
            field=models.BooleanField(default=True, help_text='Send notification when PO is approved'),
        ),
        migrations.AddField(
            model_name='posettings',
            name='overdue_reminder_days',
            field=models.PositiveIntegerField(default=3, help_text='Days past expected delivery to send overdue reminders'),
        ),
        migrations.AddField(
            model_name='posettings',
            name='require_vendor_reference',
            field=models.BooleanField(default=False, help_text='Require vendor reference before acknowledging a PO'),
        ),
        migrations.AddField(
            model_name='posettings',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_settings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='company_website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='font_size_body',
            field=models.PositiveIntegerField(default=10, help_text='Font size for body text (pt)'),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='font_size_header',
            field=models.PositiveIntegerField(default=16, help_text='Font size for headers (pt)'),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='header_text',
            field=models.TextField(blank=True, default='', help_text='Custom text to display in the header area'),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='page_size',
            field=models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter')], default='A4', max_length=20),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='paper_orientation',
            field=models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], default='Portrait', max_length=20),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='show_item_codes',
            field=models.BooleanField(default=True, help_text='Show product/SKU codes in items table'),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='show_line_numbers',
            field=models.BooleanField(default=True, help_text='Show line numbers in items table'),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='show_tax_breakdown',
            field=models.BooleanField(default=True, help_text='Show individual tax breakdown in totals'),
        ),
        migrations.AddField(
            model_name='potemplate',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Company tax identification number', max_length=50),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchases.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grnlineitem',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_line_items', to='purchases.polineitem'),
        ),
        migrations.AlterField(
            model_name='pohistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('line_added', 'Line Added'), ('line_updated', 'Line Updated'), ('line_removed', 'Line Removed'), ('closed', 'Closed')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('sent', 'Sent to Vendor'), ('acknowledged', 'Acknowledged'), ('partial_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20),
        ),
    ]
