# Generated by Django 5.2.11 on 2026-03-16 05:36

import apps.quotes.models.quote
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year for this sequence', unique=True)),
                ('last_number', models.IntegerField(default=0, help_text='Last used sequence number')),
            ],
            options={
                'verbose_name': 'Quote Sequence',
                'verbose_name_plural': 'Quote Sequences',
                'db_table': 'quote_sequences',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated quote number (QT-YYYY-NNNNN)', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted')], db_index=True, default='DRAFT', help_text='Current status of the quote', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional descriptive title for the quote', max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(blank=True, help_text='Name for guest customer (if not registered)', max_length=100, null=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Email for guest customer', max_length=254, null=True)),
                ('guest_phone', models.CharField(blank=True, help_text='Phone for guest customer', max_length=20, null=True)),
                ('guest_company', models.CharField(blank=True, help_text='Company name for B2B guest customers', max_length=150, null=True)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date the quote was issued')),
                ('valid_until', models.DateField(blank=True, db_index=True, help_text='Date the quote expires', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When quote was sent to customer (DRAFT → SENT)', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When customer accepted the quote', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When customer rejected the quote', null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='When the quote expired', null=True)),
                ('converted_at', models.DateTimeField(blank=True, help_text='When quote was converted to order', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line items before discount and tax', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount amount (calculated from discount fields)', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total tax/VAT amount', max_digits=12)),
                ('total', models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Final total (subtotal - discount + tax)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for customer (shown in PDF)', null=True)),
                ('terms', models.TextField(blank=True, help_text='Terms and conditions (shown in PDF)', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (staff only, not visible to customer)', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=200, null=True)),
                ('attachment_count', models.IntegerField(default=0, help_text='Number of attachments (denormalized count)')),
                ('currency', models.CharField(choices=[('LKR', 'Sri Lankan Rupee (₨)'), ('USD', 'US Dollar ($)')], db_index=True, default='LKR', help_text='Currency for all amounts in this quote', max_length=3)),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], help_text='Type of header-level discount (percentage or fixed)', max_length=20, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Discount value (percentage amount or fixed currency amount)', max_digits=10)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF file for this quote', max_length=500, null=True, upload_to=apps.quotes.models.quote.quote_pdf_path)),
                ('pdf_generated_at', models.DateTimeField(blank=True, help_text='Timestamp when PDF was last generated', null=True)),
                ('email_sent_to', models.EmailField(blank=True, help_text='Email address where quote was sent', max_length=254, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when quote email was last sent', null=True)),
                ('email_sent_count', models.IntegerField(default=0, help_text='Number of times quote email has been sent')),
                ('email_opened_at', models.DateTimeField(blank=True, help_text='Timestamp when quote email was first opened', null=True)),
                ('email_opened_count', models.IntegerField(default=0, help_text='Number of times quote email has been opened')),
                ('email_last_error', models.TextField(blank=True, help_text='Last error message if email send failed', null=True)),
                ('accepted_by', models.ForeignKey(blank=True, help_text='User who marked this quote as accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_accepted_by', to=settings.AUTH_USER_MODEL)),
                ('converted_to_order', models.ForeignKey(blank=True, help_text='Sales order created from this quote (if converted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_quote', to='orders.order')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Registered customer for this quote', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer')),
                ('sent_by', models.ForeignKey(blank=True, help_text='User who sent this quote to customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quotes',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['customer', 'status'], name='quotes_customer_status_idx'), models.Index(fields=['status', '-created_on'], name='quotes_status_created_idx'), models.Index(fields=['status', 'valid_until'], name='quotes_status_valid_idx'), models.Index(fields=['created_by', 'status'], name='quotes_creator_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='quotes_subtotal_non_negative'), models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='quotes_discount_non_negative'), models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='quotes_tax_non_negative'), models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='quotes_total_non_negative'), models.CheckConstraint(condition=models.Q(('discount_value__gte', 0)), name='quotes_discount_value_non_negative'), models.CheckConstraint(condition=models.Q(('email_sent_count__gte', 0)), name='quotes_email_sent_count_non_negative')],
            },
        ),
    ]
