# Generated by Django 5.2.11 on 2026-03-16 05:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_sp07_error_message_field'),
        ('quotes', '0001_sp04_quote_model_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order of line item')),
                ('product_name', models.CharField(help_text='Product name snapshot at time of quote creation', max_length=255)),
                ('custom_description', models.TextField(blank=True, help_text='Custom description for non-product items')),
                ('custom_sku', models.CharField(blank=True, help_text='Custom SKU for non-product items', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantity of items', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_of_measure', models.CharField(default='unit', help_text='Unit of measure (unit, kg, hour, sqm, etc.)', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per unit (LKR)', max_digits=12)),
                ('original_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original price before discounts', max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for margin calculation', max_digits=12, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], help_text='Type of discount applied', max_length=20, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage or fixed amount', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculated discount amount in LKR', max_digits=12)),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether this item is subject to tax')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate percentage (e.g., 15 for 15% VAT)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculated tax amount in LKR', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total for this line (quantity × price - discount + tax)', max_digits=12)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes or instructions for this line item')),
                ('price_snapshot_at', models.DateTimeField(blank=True, help_text='When product prices were captured', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_line_items', to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotes.quote')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_line_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Quote Line Item',
                'verbose_name_plural': 'Quote Line Items',
                'db_table': 'quotes_quotelineitem',
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['quote', 'position'], name='idx_qli_quote_position')],
            },
        ),
    ]
