# Generated by Django 5.2.11 on 2026-03-16 05:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_sp04_line_item_model'),
        ('tenants', '0010_add_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_latest_revision',
            field=models.BooleanField(default=True, help_text='Whether this is the latest revision'),
        ),
        migrations.AddField(
            model_name='quote',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for quote rejection', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='revision_number',
            field=models.PositiveIntegerField(default=1, help_text='Revision number (1 = original)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='revision_of',
            field=models.ForeignKey(blank=True, help_text='Original quote this is a revision of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='quotes.quote'),
        ),
        migrations.CreateModel(
            name='QuoteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_validity_days', models.PositiveIntegerField(default=30, help_text='Default number of days a quote is valid', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('quote_number_prefix', models.CharField(default='QT', help_text='Prefix for quote numbers', max_length=10)),
                ('quote_number_format', models.CharField(default='{prefix}-{year}-{number:05d}', help_text='Format template for quote numbers', max_length=50)),
                ('auto_expire_enabled', models.BooleanField(default=True, help_text='Automatically expire quotes past validity date')),
                ('require_approval', models.BooleanField(default=False, help_text='Require approval before sending quotes')),
                ('allow_guest_quotes', models.BooleanField(default=True, help_text='Allow quotes for non-registered customers')),
                ('default_terms_and_conditions', models.TextField(blank=True, help_text='Default terms and conditions for new quotes')),
                ('default_notes', models.TextField(blank=True, help_text='Default notes for new quotes')),
                ('default_discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], help_text='Default discount type for new quotes', max_length=20, null=True)),
                ('default_discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Default discount value for new quotes', max_digits=12, null=True)),
                ('send_quote_email_enabled', models.BooleanField(default=True, help_text='Enable sending quote emails')),
                ('send_expiry_reminders', models.BooleanField(default=True, help_text='Send reminders before quotes expire')),
                ('reminder_days_before_expiry', models.PositiveIntegerField(default=3, help_text='Days before expiry to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Quote Settings',
                'verbose_name_plural': 'Quote Settings',
                'db_table': 'quotes_quotesettings',
            },
        ),
        migrations.CreateModel(
            name='QuoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Quote Created'), ('UPDATED', 'Quote Updated'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Customer Accepted'), ('REJECTED', 'Customer Rejected'), ('EXPIRED', 'Quote Expired'), ('CONVERTED', 'Converted to Order'), ('REVISION_CREATED', 'Revision Created'), ('STATUS_CHANGED', 'Status Changed')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quotes.quote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote History',
                'verbose_name_plural': 'Quote Histories',
                'db_table': 'quotes_quotehistory',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['quote', '-timestamp'], name='idx_qh_quote_timestamp'), models.Index(fields=['event_type', '-timestamp'], name='idx_qh_event_timestamp')],
            },
        ),
    ]
