# Generated by Django 5.2.11 on 2026-03-16 06:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_sp04_history_settings_revisions'),
        ('tenants', '0010_add_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Size of generated PDF in bytes', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='pdf_regeneration_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times PDF has been regenerated'),
        ),
        migrations.AddField(
            model_name='quote',
            name='public_token',
            field=models.UUIDField(blank=True, help_text='Public token for unauthenticated quote access / download', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='quote_templates/logos/')),
                ('show_logo', models.BooleanField(default=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_city', models.CharField(blank=True, max_length=100)),
                ('business_postal_code', models.CharField(blank=True, max_length=20)),
                ('business_country', models.CharField(default='Sri Lanka', max_length=100)),
                ('show_business_address', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('show_contact_info', models.BooleanField(default=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=50)),
                ('tax_registration_number', models.CharField(blank=True, max_length=50)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2563eb)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('secondary_color', models.CharField(default='#64748b', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2563eb)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('accent_color', models.CharField(default='#f59e0b', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2563eb)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('text_color', models.CharField(default='#1e293b', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2563eb)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('header_font', models.CharField(choices=[('Helvetica', 'Helvetica'), ('Times-Roman', 'Times Roman'), ('Courier', 'Courier')], default='Helvetica', max_length=50)),
                ('body_font', models.CharField(choices=[('Helvetica', 'Helvetica'), ('Times-Roman', 'Times Roman'), ('Courier', 'Courier')], default='Helvetica', max_length=50)),
                ('font_size', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(14)])),
                ('theme', models.CharField(choices=[('professional', 'Professional'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('classic', 'Classic')], default='professional', max_length=20)),
                ('show_borders', models.BooleanField(default=True)),
                ('show_grid_lines', models.BooleanField(default=False)),
                ('line_spacing', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('relaxed', 'Relaxed')], default='normal', max_length=20)),
                ('footer_text', models.TextField(blank=True)),
                ('show_footer', models.BooleanField(default=True)),
                ('footer_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('show_terms', models.BooleanField(default=True)),
                ('terms_title', models.CharField(default='Terms & Conditions', max_length=100)),
                ('default_thank_you_message', models.TextField(blank=True, default='Thank you for your business!')),
                ('default_payment_instructions', models.TextField(blank=True)),
                ('validity_message_template', models.CharField(default='This quotation is valid until {valid_until}', max_length=200)),
                ('show_signature_line', models.BooleanField(default=True)),
                ('signature_label', models.CharField(default='Authorized Signature', max_length=100)),
                ('authorized_person_name', models.CharField(blank=True, max_length=200)),
                ('authorized_person_title', models.CharField(blank=True, max_length=100)),
                ('layout_options', models.JSONField(blank=True, default=dict)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter'), ('Legal', 'Legal')], default='A4', max_length=20)),
                ('page_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20)),
                ('margin_top', models.PositiveIntegerField(default=20, help_text='Top margin in mm')),
                ('margin_bottom', models.PositiveIntegerField(default=20)),
                ('margin_left', models.PositiveIntegerField(default=20)),
                ('margin_right', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Quote Template',
                'verbose_name_plural': 'Quote Templates',
                'db_table': 'quotes_quotetemplate',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='template',
            field=models.ForeignKey(blank=True, help_text='PDF template used for this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='quotes.quotetemplate'),
        ),
        migrations.AddConstraint(
            model_name='quotetemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_template_name_per_tenant'),
        ),
    ]
