# Generated by Django 5.2.11 on 2026-03-16 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_sp04_template_pdf_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the public quote was last viewed', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the public quote has been viewed'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
