# Generated by Django 5.2.11 on 2026-02-21 12:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('code', models.CharField(db_index=True, help_text='Unique account code within the tenant. Standard chart of accounts numbering (e.g. 1000, 2100).', max_length=20, unique=True, verbose_name='Account Code')),
                ('name', models.CharField(help_text='Human-readable account name.', max_length=200, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], db_index=True, help_text='Category of account: asset, liability, equity, revenue, or expense. Determines reporting position.', max_length=20, verbose_name='Account Type')),
                ('description', models.TextField(blank=True, default='', help_text="Optional description of the account's purpose.", verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the account is currently in use.', verbose_name='Active')),
                ('is_system', models.BooleanField(default=False, help_text='Whether this is a system-generated account.', verbose_name='System Account')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent account for sub-account hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account', verbose_name='Parent Account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounting_account',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('reference_number', models.CharField(db_index=True, help_text='Groups entries into a single balanced transaction. All entries with the same reference must balance.', max_length=50, verbose_name='Reference Number')),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date of the journal entry.', verbose_name='Entry Date')),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount in LKR (₨). Zero if this is a credit entry.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debit (LKR)')),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount in LKR (₨). Zero if this is a debit entry.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Credit (LKR)')),
                ('description', models.TextField(blank=True, default='', help_text='Description of this journal entry line.', verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='draft', help_text='Entry status: draft, posted, or reversed.', max_length=20, verbose_name='Status')),
                ('account', models.ForeignKey(help_text='The account being debited or credited.', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.account', verbose_name='Account')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this journal entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'accounting_journalentry',
                'ordering': ['-entry_date', 'reference_number'],
            },
        ),
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text="Short description of the action performed (e.g. 'created_order', 'updated_product', 'login').", max_length=200, verbose_name='Action')),
                ('actor_name', models.CharField(blank=True, default='', help_text='Cached display name of the actor. Preserved even if the user account is later deleted.', max_length=200, verbose_name='Actor Name')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred.', verbose_name='Timestamp')),
                ('model_name', models.CharField(blank=True, db_index=True, default='', help_text="The model/entity type affected (e.g. 'Order', 'Product').", max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(blank=True, default='', help_text='The ID of the affected object.', max_length=100, verbose_name='Object ID')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context as JSON: IP address, old/new values, request metadata, etc.', verbose_name='Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request, if available.', null=True, verbose_name='IP Address')),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Tenant Audit Log',
                'verbose_name_plural': 'Tenant Audit Logs',
                'db_table': 'accounting_tenantauditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'is_active'], name='idx_account_type_active'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='idx_account_code'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference_number', 'entry_date'], name='idx_journal_ref_date'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['account', 'entry_date'], name='idx_journal_account_date'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['-entry_date'], name='idx_journal_date_desc'),
        ),
        migrations.AddIndex(
            model_name='tenantauditlog',
            index=models.Index(fields=['-timestamp'], name='idx_audit_timestamp_desc'),
        ),
        migrations.AddIndex(
            model_name='tenantauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='idx_audit_action_time'),
        ),
        migrations.AddIndex(
            model_name='tenantauditlog',
            index=models.Index(fields=['actor', 'timestamp'], name='idx_audit_actor_time'),
        ),
        migrations.AddIndex(
            model_name='tenantauditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='idx_audit_model_object'),
        ),
    ]
