# Generated by Django 5.2.11 on 2026-04-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], help_text='The account type this configuration applies to.', max_length=20, unique=True, verbose_name='Account Type')),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], help_text='The normal balance side (DEBIT or CREDIT) for this account type.', max_length=10, verbose_name='Normal Balance')),
                ('code_start', models.IntegerField(help_text='Starting code number for accounts of this type (e.g., 1000).', verbose_name='Code Range Start')),
                ('code_end', models.IntegerField(help_text='Ending code number for accounts of this type (e.g., 1999).', verbose_name='Code Range End')),
                ('display_order', models.SmallIntegerField(help_text='Order in which this type appears in reports and listings.', unique=True, verbose_name='Display Order')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of this account type.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Account Type Configuration',
                'verbose_name_plural': 'Account Type Configurations',
                'db_table': 'accounting_account_type_config',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['type_name'], name='idx_atc_type_name'), models.Index(fields=['code_start', 'code_end'], name='idx_atc_code_range')],
            },
        ),
    ]
