# Generated by Django 5.2.11 on 2026-04-11 05:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_sp08_group_b_mptt_account_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='COATemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('template_name', models.CharField(db_index=True, help_text='Unique name for this COA template.', max_length=100, unique=True, verbose_name='Template Name')),
                ('industry', models.CharField(choices=[('RETAIL', 'Retail Business'), ('SERVICE', 'Service Company'), ('MANUFACTURING', 'Manufacturing'), ('RESTAURANT', 'Restaurant / Hospitality'), ('PROFESSIONAL', 'Professional Services'), ('CONSTRUCTION', 'Construction'), ('NONPROFIT', 'Non-Profit Organization'), ('ECOMMERCE', 'E-Commerce')], db_index=True, help_text='Industry category for this template.', max_length=50, verbose_name='Industry')),
                ('template_accounts', models.JSONField(default=list, help_text='JSON array of account definitions.', verbose_name='Template Accounts')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of this template.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'COA Template',
                'verbose_name_plural': 'COA Templates',
                'db_table': 'accounting_coa_template',
                'ordering': ['template_name'],
            },
        ),
    ]
