# Generated by Django 5.2.11 on 2026-04-11 10:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_sp09_group_a_journal_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Debit amount in LKR (₨). Zero if this is a credit line.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debit Amount')),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Credit amount in LKR (₨). Zero if this is a debit line.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Credit Amount')),
                ('description', models.CharField(blank=True, default='', help_text='Line-level description or memo.', max_length=255, verbose_name='Description')),
                ('sort_order', models.IntegerField(blank=True, default=0, help_text='Display order within the journal entry.', verbose_name='Sort Order')),
                ('account', models.ForeignKey(help_text='The account being debited or credited.', on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='Account')),
                ('journal_entry', models.ForeignKey(help_text='The parent journal entry this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='Journal Entry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'db_table': 'accounting_journal_entry_line',
                'ordering': ['journal_entry', 'sort_order'],
                'indexes': [models.Index(fields=['journal_entry', 'sort_order'], name='idx_jel_entry_order'), models.Index(fields=['account'], name='idx_jel_account')],
            },
        ),
    ]
