# Generated by Django 5.2.11 on 2026-04-11 10:34

import apps.accounting.models.journal_attachment
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_sp09_group_b_journal_entry_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded document file.', upload_to=apps.accounting.models.journal_attachment.journal_attachment_upload_path, verbose_name='File')),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file.', max_length=255, verbose_name='Original Filename')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes.', verbose_name='File Size')),
                ('mime_type', models.CharField(blank=True, default='', help_text='MIME type of the uploaded file.', max_length=100, verbose_name='MIME Type')),
                ('description', models.CharField(blank=True, default='', help_text='Optional description of the attachment.', max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this attachment was uploaded.', verbose_name='Uploaded At')),
                ('journal_entry', models.ForeignKey(help_text='The journal entry this attachment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounting.journalentry', verbose_name='Journal Entry')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this attachment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Journal Entry Attachment',
                'verbose_name_plural': 'Journal Entry Attachments',
                'db_table': 'accounting_journal_entry_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
