# Generated by Django 5.2.11 on 2026-04-11 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_sp09_group_c_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for the template (e.g. 'Monthly Rent Payment').", max_length=100, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, help_text="Detailed description of the template's purpose and usage.", null=True, verbose_name='Description')),
                ('template_lines', models.JSONField(default=dict, help_text='JSON structure defining the entry line items with account codes and amounts.', verbose_name='Template Lines')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('MONTH_END', 'Month-End'), ('PAYROLL', 'Payroll'), ('DEPRECIATION', 'Depreciation'), ('ACCRUALS', 'Accruals'), ('CUSTOM', 'Custom')], db_index=True, default='GENERAL', help_text='Template category for organisation and filtering.', max_length=20, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Journal Entry Template',
                'verbose_name_plural': 'Journal Entry Templates',
                'db_table': 'accounting_journal_entry_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], help_text='How often the entry should be generated.', max_length=20, verbose_name='Frequency')),
                ('description', models.CharField(blank=True, default='', help_text="Description of this recurring entry's purpose.", max_length=255, verbose_name='Description')),
                ('start_date', models.DateField(help_text='Date when recurring entry begins.', verbose_name='Start Date')),
                ('next_run_date', models.DateField(db_index=True, help_text='Next scheduled execution date.', verbose_name='Next Run Date')),
                ('last_run_date', models.DateField(blank=True, help_text='Date of last successful execution.', null=True, verbose_name='Last Run Date')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date; entry deactivates when reached.', null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this recurring entry is active.', verbose_name='Active')),
                ('auto_post', models.BooleanField(default=False, help_text='Automatically post generated entries (skip draft).', verbose_name='Auto-Post')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(help_text='The template used to generate journal entries.', on_delete=django.db.models.deletion.PROTECT, related_name='recurring_entries', to='accounting.journalentrytemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Recurring Entry',
                'verbose_name_plural': 'Recurring Entries',
                'db_table': 'accounting_recurring_entry',
                'ordering': ['next_run_date'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentrytemplate',
            index=models.Index(fields=['category'], name='idx_jet_category'),
        ),
        migrations.AddIndex(
            model_name='recurringentry',
            index=models.Index(fields=['is_active', 'next_run_date'], name='idx_re_active_next_run'),
        ),
    ]
