# Generated by Django 5.2.11 on 2026-04-11 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_sp09_group_d_templates_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of the accounting period.', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Last day of the accounting period.', verbose_name='End Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')], db_index=True, default='OPEN', help_text='Period lifecycle status (Open/Closed/Locked).', max_length=10, verbose_name='Status')),
                ('fiscal_year', models.PositiveIntegerField(help_text='Fiscal year this period belongs to (e.g. 2026).', verbose_name='Fiscal Year')),
                ('period_number', models.PositiveSmallIntegerField(help_text='Period number within the fiscal year (1-12).', verbose_name='Period Number')),
                ('name', models.CharField(blank=True, default='', help_text="Display name (e.g. 'April 2026', 'Q1 2026').", max_length=50, verbose_name='Period Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Accounting Period',
                'verbose_name_plural': 'Accounting Periods',
                'db_table': 'accounting_period',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['fiscal_year', 'period_number'], name='idx_ap_year_period'), models.Index(fields=['start_date', 'end_date'], name='idx_ap_date_range')],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'period_number'), name='uq_accounting_period_year_number')],
            },
        ),
    ]
