# Generated by Django 5.2.11 on 2026-04-11 14:03

import apps.accounting.models.journal_template
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_sp09_group_e_accounting_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentrytemplate',
            name='template_lines',
            field=models.JSONField(default=apps.accounting.models.journal_template._default_template_lines, help_text='JSON structure defining the entry line items with account codes and amounts.', verbose_name='Template Lines'),
        ),
    ]
