# Generated by Django 5.2.11 on 2026-04-11 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_journalentrytemplate_template_lines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text="Descriptive name for the bank account (e.g., 'BOC Business').", max_length=100, verbose_name='Account Name')),
                ('account_number', models.CharField(db_index=True, help_text='Bank account number.', max_length=50, verbose_name='Account Number')),
                ('bank_name', models.CharField(db_index=True, help_text="Name of the bank (e.g., 'Bank of Ceylon').", max_length=200, verbose_name='Bank Name')),
                ('branch_name', models.CharField(blank=True, help_text='Branch name (optional).', max_length=200, null=True, verbose_name='Branch Name')),
                ('branch_code', models.CharField(blank=True, help_text='Branch code (optional).', max_length=20, null=True, verbose_name='Branch Code')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash')], db_index=True, default='CHECKING', help_text='Type of bank account.', max_length=20, verbose_name='Account Type')),
                ('currency', models.CharField(db_index=True, default='LKR', help_text="ISO 4217 currency code (e.g., 'LKR', 'USD').", max_length=3, verbose_name='Currency')),
                ('last_reconciled_date', models.DateField(blank=True, db_index=True, help_text='Date of the last completed reconciliation.', null=True, verbose_name='Last Reconciled Date')),
                ('last_reconciled_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Balance at the last completed reconciliation.', max_digits=20, null=True, verbose_name='Last Reconciled Balance')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this bank account is active for reconciliation.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('gl_account', models.ForeignKey(help_text='Linked General Ledger account from the Chart of Accounts.', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.account', verbose_name='GL Account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'accounting_bank_account',
                'ordering': ['bank_name', 'account_name'],
                'indexes': [models.Index(fields=['bank_name', 'account_number'], name='idx_bank_acct_lookup')],
            },
        ),
    ]
