# Generated by Django 5.2.11 on 2026-04-11 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_format', models.CharField(choices=[('CSV', 'CSV'), ('OFX', 'OFX'), ('MT940', 'MT940')], default='CSV', help_text='File format of the imported statement.', max_length=10, verbose_name='Format')),
                ('start_date', models.DateField(db_index=True, help_text='First transaction date in the statement.', verbose_name='Start Date')),
                ('end_date', models.DateField(db_index=True, help_text='Last transaction date in the statement.', verbose_name='End Date')),
                ('opening_balance', models.DecimalField(decimal_places=2, help_text='Statement opening balance.', max_digits=15, verbose_name='Opening Balance')),
                ('closing_balance', models.DecimalField(decimal_places=2, help_text='Statement closing balance.', max_digits=15, verbose_name='Closing Balance')),
                ('file', models.FileField(blank=True, help_text='Uploaded statement file.', null=True, upload_to='statements/%Y/%m/', verbose_name='Statement File')),
                ('import_status', models.CharField(choices=[('PENDING', 'Pending'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current import processing status.', max_length=20, verbose_name='Import Status')),
                ('import_error', models.TextField(blank=True, help_text='Error message if import failed.', null=True, verbose_name='Import Error')),
                ('import_line_count', models.PositiveIntegerField(default=0, help_text='Number of transaction lines imported.', verbose_name='Imported Lines')),
                ('imported_at', models.DateTimeField(blank=True, help_text='Timestamp when import was completed.', null=True, verbose_name='Imported At')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether this statement has been fully reconciled.', verbose_name='Reconciled')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this statement.', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bank_account', models.ForeignKey(help_text='Bank account this statement belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='accounting.bankaccount', verbose_name='Bank Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements_imported', to=settings.AUTH_USER_MODEL, verbose_name='Imported By')),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'db_table': 'accounting_bank_statement',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(help_text='Sequential line number within the statement.', verbose_name='Line Number')),
                ('transaction_date', models.DateField(db_index=True, help_text='Date the transaction occurred.', verbose_name='Transaction Date')),
                ('value_date', models.DateField(blank=True, help_text='Date the transaction takes effect for interest calculation.', null=True, verbose_name='Value Date')),
                ('description', models.TextField(help_text='Transaction description or narration from the bank.', verbose_name='Description')),
                ('reference', models.CharField(blank=True, help_text='Bank reference number, cheque number, or transfer reference.', max_length=100, null=True, verbose_name='Reference')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Debit (withdrawal) amount.', max_digits=15, verbose_name='Debit')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Credit (deposit) amount.', max_digits=15, verbose_name='Credit')),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Account balance after this transaction.', max_digits=15, null=True, verbose_name='Running Balance')),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('PARTIAL', 'Partial Match'), ('EXCLUDED', 'Excluded')], db_index=True, default='UNMATCHED', help_text='Current reconciliation matching status.', max_length=20, verbose_name='Match Status')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether this line has been reconciled.', verbose_name='Reconciled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('matched_entry', models.ForeignKey(blank=True, help_text='Journal entry matched to this statement line.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='accounting.journalentry', verbose_name='Matched Entry')),
                ('statement', models.ForeignKey(help_text='Parent bank statement.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement', verbose_name='Statement')),
            ],
            options={
                'verbose_name': 'Statement Line',
                'verbose_name_plural': 'Statement Lines',
                'db_table': 'accounting_statement_line',
                'ordering': ['statement', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['bank_account', 'start_date', 'end_date'], name='idx_stmt_bank_period'),
        ),
        migrations.AddIndex(
            model_name='statementline',
            index=models.Index(fields=['transaction_date', 'match_status'], name='idx_stmt_line_date_match'),
        ),
        migrations.AlterUniqueTogether(
            name='statementline',
            unique_together={('statement', 'line_number')},
        ),
    ]
