# Generated by Django 5.2.11 on 2026-04-11 15:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_bankstatement_statementline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable rule name, e.g. 'Exact Match Same Day'.", max_length=200)),
                ('priority', models.IntegerField(default=10, help_text='Rule evaluation order (1-100, lower = higher priority).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('amount_tolerance', models.DecimalField(decimal_places=2, default=0, help_text='Maximum allowed amount difference. 0 = exact match.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_range_days', models.IntegerField(default=0, help_text='Maximum allowed date difference in days. 0 = same day.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('match_reference', models.BooleanField(default=False, help_text='If True, require exact reference/check number match.')),
                ('description_pattern', models.TextField(blank=True, default='', help_text='Regex pattern for description matching. Empty = skip.')),
                ('pattern_flags', models.CharField(blank=True, default='i', help_text='Regex flags: i=IGNORECASE, m=MULTILINE, s=DOTALL.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this rule is used during matching.')),
                ('bank_account', models.ForeignKey(blank=True, help_text='NULL = global rule applying to all accounts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_rules', to='accounting.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='accounting__is_acti_687a2d_idx'), models.Index(fields=['bank_account', 'is_active'], name='accounting__bank_ac_5687d1_idx')],
            },
        ),
    ]
