# Generated by Django 5.2.11 on 2026-04-11 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_matchingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('statement_balance', models.DecimalField(decimal_places=2, help_text='Balance per bank statement.', max_digits=15)),
                ('book_balance', models.DecimalField(decimal_places=2, help_text='Balance per GL account.', max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=0, help_text='statement_balance − book_balance.', max_digits=15)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.bankaccount')),
                ('bank_statement', models.ForeignKey(blank=True, help_text='Linked bank statement (optional for manual reconciliations).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation', to='accounting.bankstatement')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Reconciliation',
                'verbose_name_plural': 'Bank Reconciliations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='accounting.journalentry')),
                ('matched_by', models.ForeignKey(blank=True, help_text='User who created manual match (null for AUTO).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.reconciliation')),
                ('statement_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='accounting.statementline')),
            ],
            options={
                'verbose_name': 'Reconciliation Item',
                'verbose_name_plural': 'Reconciliation Items',
                'ordering': ['matched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['status', 'bank_account'], name='accounting__status_e911cc_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['bank_account', 'start_date', 'end_date'], name='accounting__bank_ac_38b1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['reconciliation', 'statement_line'], name='accounting__reconci_538629_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['match_type'], name='accounting__match_t_884a71_idx'),
        ),
    ]
