# Generated by Django 5.2.11 on 2026-04-11 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_reconciliationadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='name',
            field=models.CharField(blank=True, help_text="Descriptive identifier (e.g., 'December 2025 Statement').", max_length=200, verbose_name='Statement Name'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when reconciliation was completed.', null=True, verbose_name='Reconciled At'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_statements', to=settings.AUTH_USER_MODEL, verbose_name='Reconciled By'),
        ),
        migrations.AddField(
            model_name='statementline',
            name='description_clean',
            field=models.TextField(blank=True, help_text='Normalized description for matching.', null=True, verbose_name='Cleaned Description'),
        ),
        migrations.AddField(
            model_name='statementline',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External system reference identifier.', max_length=100, null=True, verbose_name='External Reference'),
        ),
        migrations.AddField(
            model_name='statementline',
            name='memo',
            field=models.TextField(blank=True, help_text='User annotations during reconciliation.', null=True, verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='statementline',
            name='posting_date',
            field=models.DateField(blank=True, help_text='Date the bank processed the transaction.', null=True, verbose_name='Posting Date'),
        ),
        migrations.AddField(
            model_name='statementline',
            name='reference_type',
            field=models.CharField(blank=True, help_text='Categorisation of reference (e.g., CHEQUE, TRANSFER, CARD).', max_length=30, null=True, verbose_name='Reference Type'),
        ),
    ]
