# Generated by Django 5.2.11 on 2026-04-12 11:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_add_report_config_and_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_registration_no', models.CharField(blank=True, help_text='VAT registration number issued by IRD (format: XXXXXXXXX-7000).', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='VAT number must be in format XXXXXXXXX-7000 (9 digits, hyphen, 7000).', regex='^\\d{9}-7000$')], verbose_name='VAT Registration Number')),
                ('is_svat_registered', models.BooleanField(default=False, help_text='Whether the business is registered under Simplified VAT scheme.', verbose_name='SVAT Registered')),
                ('vat_filing_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], help_text='VAT filing frequency: Monthly (>75M turnover) or Quarterly (SVAT 12M-75M).', max_length=20, null=True, verbose_name='VAT Filing Period')),
                ('epf_registration_no', models.CharField(blank=True, help_text='EPF registration number issued by Central Bank (format: E/XXXXXX).', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='EPF number must be in format E/XXXXXX (E/ prefix followed by 6 digits).', regex='^E/\\d{6}$')], verbose_name='EPF Registration Number')),
                ('etf_registration_no', models.CharField(blank=True, help_text='ETF registration number issued by ETF Board (6-digit numeric).', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='ETF number must be a 6-digit numeric sequence.', regex='^\\d{6}$')], verbose_name='ETF Registration Number')),
                ('tin_number', models.CharField(blank=True, help_text='Employer TIN issued by Inland Revenue Department (9-digit numeric).', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='TIN must be a 9-digit numeric sequence.', regex='^\\d{9}$')], verbose_name='Tax Identification Number (TIN)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
                'db_table': 'accounting_tax_configuration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxPeriodRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('vat', 'Value Added Tax (VAT)'), ('paye', 'Pay As You Earn (PAYE)'), ('epf', 'Employees Provident Fund (EPF)'), ('etf', 'Employees Trust Fund (ETF)'), ('wht', 'Withholding Tax (WHT)')], db_index=True, max_length=10)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('period_number', models.PositiveSmallIntegerField(help_text='Month (1-12) for monthly, quarter (1-4) for quarterly, 1 for annual.')),
                ('start_date', models.DateField(verbose_name='Period Start Date')),
                ('end_date', models.DateField(verbose_name='Period End Date')),
                ('due_date', models.DateField(help_text='Deadline for filing the return with the tax authority.', verbose_name='Filing Due Date')),
                ('filing_status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('filed', 'Filed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_records', to='accounting.taxconfiguration')),
            ],
            options={
                'verbose_name': 'Tax Period Record',
                'verbose_name_plural': 'Tax Period Records',
                'db_table': 'accounting_tax_period_record',
                'ordering': ['year', 'period_number'],
                'constraints': [models.UniqueConstraint(fields=('tax_configuration', 'tax_type', 'year', 'period_number'), name='unique_tax_period')],
            },
        ),
    ]
