# Generated by Django 5.2.11 on 2026-04-12 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_tax_configuration_and_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VATReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated reference (VAT-YYYYMM-XXXXX).', max_length=30, unique=True)),
                ('output_vat', models.DecimalField(decimal_places=2, default=0, help_text='Total VAT collected on sales (8% standard rate).', max_digits=15, verbose_name='Output VAT')),
                ('input_vat', models.DecimalField(decimal_places=2, default=0, help_text='Total claimable VAT paid on purchases.', max_digits=15, verbose_name='Input VAT')),
                ('net_vat_payable', models.DecimalField(decimal_places=2, default=0, help_text='Output VAT minus Input VAT. Negative = refund position.', max_digits=15, verbose_name='Net VAT Payable')),
                ('line_items', models.JSONField(blank=True, default=dict, help_text='Detailed transaction breakdown by category.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('filed', 'Filed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('filed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_vat_returns', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vat_returns', to='accounting.taxperiodrecord')),
            ],
            options={
                'verbose_name': 'VAT Return',
                'verbose_name_plural': 'VAT Returns',
                'db_table': 'accounting_vat_return',
                'ordering': ['-period__year', '-period__period_number'],
            },
        ),
    ]
