# Generated by Django 5.2.11 on 2026-04-12 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_vat_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAYEReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated reference (PAYE-YYYYMM-XXXXX).', max_length=30, unique=True)),
                ('total_employees', models.PositiveIntegerField(default=0, help_text='Count of employees paid during the period.', verbose_name='Total Employees')),
                ('total_remuneration', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all gross salaries (basic + allowances + bonuses).', max_digits=15, verbose_name='Total Remuneration')),
                ('total_paye_deducted', models.DecimalField(decimal_places=2, default=0, help_text='Sum of PAYE tax deducted from all employees.', max_digits=15, verbose_name='Total PAYE Deducted')),
                ('employee_details', models.JSONField(blank=True, default=dict, help_text='Per-employee breakdown: NIC, salary, taxable income, PAYE, YTD.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('filed', 'Filed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('filed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paye_returns', to='accounting.taxperiodrecord')),
            ],
            options={
                'verbose_name': 'PAYE Return',
                'verbose_name_plural': 'PAYE Returns',
                'db_table': 'accounting_paye_return',
                'ordering': ['-period__year', '-period__period_number'],
            },
        ),
    ]
