# Generated by Django 5.2.11 on 2026-04-12 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_paye_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPFReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated reference (EPF-YYYYMM-XXXXX).', max_length=30, unique=True)),
                ('total_employee_contribution', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=15, verbose_name='Employee Contribution (8%)')),
                ('total_employer_contribution', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=15, verbose_name='Employer Contribution (12%)')),
                ('total_contribution', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=15, verbose_name='Total Contribution (20%)')),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('employee_schedule', models.JSONField(blank=True, default=list, help_text='Per-employee EPF contribution breakdown.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('filed', 'Filed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('filed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epf_returns', to='accounting.taxperiodrecord')),
            ],
            options={
                'verbose_name': 'EPF Return',
                'verbose_name_plural': 'EPF Returns',
                'db_table': 'accounting_epf_return',
                'ordering': ['-period__year', '-period__period_number'],
            },
        ),
        migrations.CreateModel(
            name='ETFReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated reference (ETF-YYYYMM-XXXXX).', max_length=30, unique=True)),
                ('total_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total ETF Contribution (3%)')),
                ('total_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Gross Salary Base')),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('employee_schedule', models.JSONField(blank=True, default=dict, help_text='Per-employee ETF contribution breakdown.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('filed', 'Filed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('filed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etf_returns', to='accounting.taxperiodrecord')),
            ],
            options={
                'verbose_name': 'ETF Return',
                'verbose_name_plural': 'ETF Returns',
                'db_table': 'accounting_etf_return',
                'ordering': ['-period__year', '-period__period_number'],
            },
        ),
    ]
