# Generated by Django 5.2.11 on 2026-04-12 13:30

import apps.accounting.models.tax_submission
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_epf_etf_returns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_reference', models.CharField(blank=True, help_text='Acknowledgment number from tax authority.', max_length=100, null=True, unique=True)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time the return was filed with the authority.')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Return Filed'), ('ACCEPTED', 'Accepted & Processed'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], db_index=True, default='SUBMITTED', max_length=20)),
                ('confirmation_document', models.FileField(blank=True, help_text='Official confirmation document from tax authority (max 10 MB).', null=True, upload_to=apps.accounting.models.tax_submission.tax_submission_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'tiff'])])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_submissions', to=settings.AUTH_USER_MODEL)),
                ('tax_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounting.taxperiodrecord')),
            ],
            options={
                'verbose_name': 'Tax Submission',
                'verbose_name_plural': 'Tax Submissions',
                'db_table': 'accounting_tax_submission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
