"""
Reorder suggestion model for automated and manual reorder recommendations.

Tracks purchase suggestions with urgency levels, calculation details,
and lifecycle management (pending → converted/dismissed/expired).
"""

from decimal import Decimal

from django.conf import settings
from django.db import models
from django.utils import timezone

from apps.core.mixins import UUIDMixin
from apps.inventory.alerts.constants import (
    SUGGESTION_STATUS_CONVERTED,
    SUGGESTION_STATUS_DISMISSED,
    SUGGESTION_STATUS_PENDING,
    SUGGESTION_STATUS_CHOICES,
    URGENCY_CHOICES,
    URGENCY_CRITICAL,
    URGENCY_HIGH,
    URGENCY_LOW,
    URGENCY_MEDIUM,
)


class ReorderSuggestionManager(models.Manager):
    """Custom manager for ReorderSuggestion queries."""

    def get_pending(self):
        """Return all pending suggestions."""
        return self.get_queryset().filter(status=SUGGESTION_STATUS_PENDING)

    def get_by_urgency(self, urgency):
        """Return pending suggestions for a given urgency level."""
        return self.get_pending().filter(urgency=urgency)

    def get_for_product(self, product, warehouse=None):
        """Return pending suggestions for a product, optionally per warehouse."""
        qs = self.get_pending().filter(product=product)
        if warehouse is not None:
            qs = qs.filter(warehouse=warehouse)
        return qs

    def get_critical(self):
        """Return pending suggestions with critical urgency."""
        return self.get_by_urgency(URGENCY_CRITICAL)

    def get_converted(self):
        """Return suggestions that have been converted to POs."""
        return self.get_queryset().filter(status=SUGGESTION_STATUS_CONVERTED)

    def get_dismissed(self):
        """Return dismissed suggestions."""
        return self.get_queryset().filter(status=SUGGESTION_STATUS_DISMISSED)

    def mark_expired_suggestions(self, expiry_days=30):
        """Mark old pending suggestions as expired."""
        from apps.inventory.alerts.constants import SUGGESTION_STATUS_EXPIRED

        cutoff = timezone.now() - timezone.timedelta(days=expiry_days)
        expired = self.get_pending().filter(created_at__lt=cutoff)
        count = expired.update(
            status=SUGGESTION_STATUS_EXPIRED,
            status_changed_at=timezone.now(),
        )
        return count


class ReorderSuggestion(UUIDMixin, models.Model):
    """
    Reorder suggestion generated by the stock monitoring system.

    Tracks the recommended reorder quantity, urgency, calculation
    details, and lifecycle (pending → converted_to_po / dismissed / expired).
    """

    objects = ReorderSuggestionManager()

    # ── Relationships ───────────────────────────────────────────
    product = models.ForeignKey(
        "products.Product",
        on_delete=models.CASCADE,
        related_name="reorder_suggestions",
    )
    variant = models.ForeignKey(
        "products.ProductVariant",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="reorder_suggestions",
    )
    warehouse = models.ForeignKey(
        "inventory.Warehouse",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reorder_suggestions",
    )
    suggested_supplier = models.ForeignKey(
        "vendors.Supplier",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reorder_suggestions",
        help_text="Supplier recommended for this order.",
    )

    # ── Quantity & Stock Fields ─────────────────────────────────
    suggested_qty = models.DecimalField(
        max_digits=15,
        decimal_places=3,
        help_text="Recommended order quantity.",
    )
    minimum_order_qty = models.DecimalField(
        max_digits=15,
        decimal_places=3,
        default=Decimal("1"),
        help_text="Minimum order quantity from supplier.",
    )
    current_stock = models.DecimalField(
        max_digits=15,
        decimal_places=3,
        help_text="Stock level when suggestion was generated.",
    )

    # ── Urgency ─────────────────────────────────────────────────
    urgency = models.CharField(
        max_length=20,
        choices=URGENCY_CHOICES,
        default=URGENCY_MEDIUM,
    )

    # ── Calculation Fields ──────────────────────────────────────
    days_until_stockout = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Estimated days until out-of-stock.",
    )
    daily_velocity = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        null=True,
        blank=True,
        help_text="Average daily sales rate.",
    )
    safety_stock = models.DecimalField(
        max_digits=15,
        decimal_places=3,
        null=True,
        blank=True,
        help_text="Calculated safety stock buffer.",
    )
    eoq = models.DecimalField(
        max_digits=15,
        decimal_places=3,
        null=True,
        blank=True,
        help_text="Economic Order Quantity.",
    )
    reorder_point = models.DecimalField(
        max_digits=15,
        decimal_places=3,
        null=True,
        blank=True,
        help_text="Reorder point used for suggestion.",
    )

    # ── Cost Fields (LKR) ──────────────────────────────────────
    estimated_cost = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Total estimated cost in LKR.",
    )
    unit_cost = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Per-unit cost in LKR.",
    )

    # ── Detail Fields ───────────────────────────────────────────
    notes = models.TextField(blank=True, default="")
    calculation_details = models.JSONField(
        default=dict,
        blank=True,
        help_text="Full calculation breakdown.",
    )
    auto_generated = models.BooleanField(
        default=True,
        help_text="True if system-generated, False if manual.",
    )

    # ── Status Lifecycle ────────────────────────────────────────
    status = models.CharField(
        max_length=20,
        choices=SUGGESTION_STATUS_CHOICES,
        default=SUGGESTION_STATUS_PENDING,
    )
    status_changed_at = models.DateTimeField(null=True, blank=True)
    status_changed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reorder_status_changes",
    )
    dismissal_reason = models.TextField(blank=True, default="")
    converted_po_id = models.UUIDField(
        null=True,
        blank=True,
        help_text="ID of the purchase order created from this suggestion.",
    )

    # ── Timestamps ──────────────────────────────────────────────
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Reorder Suggestion"
        verbose_name_plural = "Reorder Suggestions"
        db_table = "inventory_reorder_suggestion"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["product", "status"], name="idx_reorder_prod_status"),
            models.Index(fields=["urgency", "-created_at"], name="idx_reorder_urgency"),
            models.Index(fields=["status", "-created_at"], name="idx_reorder_status"),
        ]

    def __str__(self):
        return (
            f"Reorder: {self.product} – {self.suggested_qty} units "
            f"({self.get_urgency_display()})"
        )

    # ── Lifecycle Methods ───────────────────────────────────────

    def mark_converted(self, po_id, user=None):
        """Mark suggestion as converted to a purchase order."""
        self.status = SUGGESTION_STATUS_CONVERTED
        self.converted_po_id = po_id if not isinstance(po_id, str) else po_id
        self.status_changed_at = timezone.now()
        self.status_changed_by = user
        self.save(
            update_fields=[
                "status", "converted_po_id", "status_changed_at",
                "status_changed_by", "updated_at",
            ]
        )

    def mark_dismissed(self, reason="", user=None):
        """Mark suggestion as dismissed."""
        self.status = SUGGESTION_STATUS_DISMISSED
        self.dismissal_reason = reason
        self.status_changed_at = timezone.now()
        self.status_changed_by = user
        self.save(
            update_fields=[
                "status", "dismissal_reason", "status_changed_at",
                "status_changed_by", "updated_at",
            ]
        )

    def is_expired(self, expiry_days=30):
        """Check if suggestion is older than expiry period."""
        if self.status != SUGGESTION_STATUS_PENDING:
            return False
        cutoff = timezone.now() - timezone.timedelta(days=expiry_days)
        return self.created_at < cutoff

    def can_convert(self):
        """Check if suggestion can be converted to a PO."""
        if self.status != SUGGESTION_STATUS_PENDING:
            return False, f"Status is '{self.get_status_display()}', must be Pending."
        if self.suggested_supplier is None:
            return False, "No supplier assigned."
        if self.suggested_qty <= 0:
            return False, "Suggested quantity must be > 0."
        return True, "OK"
