# Generated by Django 5.2.11 on 2026-04-12 18:11

import apps.dashboard.models.dashboard_layout
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the KPI', max_length=100, verbose_name='KPI Name')),
                ('code', models.CharField(help_text='Unique identifier code for the KPI (e.g., SALES_DAILY_REVENUE)', max_length=50, unique=True, verbose_name='KPI Code')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of what this KPI measures', verbose_name='Description')),
                ('category', models.CharField(choices=[('SALES', 'Sales & Revenue'), ('INVENTORY', 'Inventory & Stock'), ('FINANCIAL', 'Financial Performance'), ('HR', 'Human Resources'), ('CUSTOMER', 'Customer Metrics'), ('OPERATIONS', 'Operations & Efficiency'), ('COMPLIANCE', 'Compliance & Regulatory')], help_text='KPI category for dashboard organization', max_length=20, verbose_name='Category')),
                ('default_widget_type', models.CharField(choices=[('NUMBER', 'Single Number'), ('CHART', 'Chart Display'), ('TABLE', 'Table Display'), ('GAUGE', 'Gauge / Meter'), ('TREND', 'Trend with Sparkline')], default='NUMBER', help_text='Default widget type for displaying this KPI', max_length=20, verbose_name='Default Widget Type')),
                ('calculation_method', models.CharField(help_text='Calculator class method reference (e.g., SalesKPICalculator.calculate_daily_revenue)', max_length=100, verbose_name='Calculation Method')),
                ('format_type', models.CharField(choices=[('currency', 'Currency (LKR)'), ('number', 'Number'), ('percent', 'Percentage'), ('decimal', 'Decimal'), ('count', 'Count')], default='number', help_text='Display format for the KPI value', max_length=20, verbose_name='Format Type')),
                ('required_permission', models.CharField(blank=True, default='', help_text='Permission required to view this KPI (blank = visible to all authenticated users)', max_length=100, verbose_name='Required Permission')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this KPI is currently active', verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within category', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI Definition',
                'verbose_name_plural': 'KPI Definitions',
                'db_table': 'dashboard_kpi_definition',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Dashboard', help_text='Name for this dashboard layout', max_length=100, verbose_name='Layout Name')),
                ('widgets', models.JSONField(default=apps.dashboard.models.dashboard_layout._default_widgets, help_text='JSON configuration of widget positions and settings', verbose_name='Widget Configuration')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default dashboard layout", verbose_name='Default Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Dashboard Layout',
                'verbose_name_plural': 'Dashboard Layouts',
                'db_table': 'dashboard_layout',
            },
        ),
        migrations.CreateModel(
            name='KPIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_threshold', models.DecimalField(decimal_places=2, help_text='Value that triggers a warning alert', max_digits=15, verbose_name='Warning Threshold')),
                ('critical_threshold', models.DecimalField(decimal_places=2, help_text='Value that triggers a critical alert', max_digits=15, verbose_name='Critical Threshold')),
                ('comparison', models.CharField(choices=[('lt', 'Less Than'), ('gt', 'Greater Than'), ('lte', 'Less Than or Equal'), ('gte', 'Greater Than or Equal')], default='lt', help_text='How to compare the KPI value against thresholds', max_length=10, verbose_name='Comparison Operator')),
                ('notify_email', models.BooleanField(default=False, help_text='Send email when threshold is breached', verbose_name='Email Notification')),
                ('notify_dashboard', models.BooleanField(default=True, help_text='Show notification on dashboard when threshold is breached', verbose_name='Dashboard Notification')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is currently active', verbose_name='Active')),
                ('last_triggered', models.DateTimeField(blank=True, help_text='When this alert was last triggered', null=True, verbose_name='Last Triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.kpidefinition', verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'KPI Alert',
                'verbose_name_plural': 'KPI Alerts',
                'db_table': 'dashboard_kpi_alert',
            },
        ),
    ]
