# Generated by Django 5.2.11 on 2026-04-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidefinition',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places (0-4)', verbose_name='Decimal Places'),
        ),
        migrations.AddField(
            model_name='kpidefinition',
            name='show_thousand_separator',
            field=models.BooleanField(default=True, help_text='Add separators for thousands (e.g., 1,000,000)', verbose_name='Thousand Separator'),
        ),
        migrations.AlterField(
            model_name='kpidefinition',
            name='required_permission',
            field=models.CharField(blank=True, default='', help_text='Permission codename required to view this KPI (blank = visible to all authenticated users)', max_length=100, verbose_name='Required Permission'),
        ),
    ]
