# Generated by Django 5.2.11 on 2026-04-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_format_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpialert',
            name='consecutive_breaches',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive times the threshold was breached', verbose_name='Consecutive Breaches'),
        ),
        migrations.AddField(
            model_name='kpialert',
            name='cooldown_period_minutes',
            field=models.PositiveIntegerField(default=1440, help_text='Minimum minutes between repeated notifications (default 24h)', verbose_name='Cooldown (minutes)'),
        ),
        migrations.AddField(
            model_name='kpialert',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Short name for this alert rule', max_length=100, verbose_name='Alert Name'),
        ),
    ]
