# Generated by Django 5.2.11 on 2026-03-10 04:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('codename', models.CharField(db_index=True, help_text="Unique permission identifier (e.g. 'orders.create').", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name.', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of what this permission grants.')),
                ('resource', models.CharField(db_index=True, help_text="Resource this permission applies to (e.g. 'orders', 'inventory').", max_length=50)),
                ('action', models.CharField(help_text="Action this permission grants (e.g. 'create', 'view', 'update', 'delete', 'export').", max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this permission is currently active.')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'users_permission',
                'ordering': ['resource', 'action'],
                'indexes': [models.Index(fields=['resource', 'action'], name='idx_perm_resource_action')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(db_index=True, help_text='Human-readable role name.', max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe role identifier.', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text="Description of this role's purpose and scope.")),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted by tenants.')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted to this role.', related_name='roles', to='users.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'users_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', help_text='UI colour-scheme preference.', max_length=20)),
                ('items_per_page', models.PositiveSmallIntegerField(default=25, help_text='Default number of rows to display in list views.')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for important events.')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive browser push notifications.')),
                ('dashboard_layout', models.JSONField(blank=True, default=dict, help_text='Serialised dashboard widget layout (JSON).')),
                ('sidebar_collapsed', models.BooleanField(default=False, help_text='Whether the sidebar is collapsed by default.')),
                ('user', models.OneToOneField(help_text='The platform user whose preferences these are.', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'users_userpreferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('display_name', models.CharField(blank=True, default='', help_text='Preferred display name within this tenant.', max_length=150)),
                ('job_title', models.CharField(blank=True, default='', help_text="Job title / designation within the tenant's organisation.", max_length=100)),
                ('department', models.CharField(blank=True, default='', help_text="Department or team within the tenant's organisation.", max_length=100)),
                ('phone', models.CharField(blank=True, default='', help_text='Direct phone number in +94 (Sri Lanka) format.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Sri Lankan phone number in +94 format.', regex='^\\+94\\s?\\d{2}\\s?\\d{3}\\s?\\d{4}$')])),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture.', null=True, upload_to='users/avatars/%Y/%m/')),
                ('timezone', models.CharField(default='Asia/Colombo', help_text="IANA timezone identifier (e.g. 'Asia/Colombo').", max_length=50)),
                ('locale', models.CharField(default='en', help_text="Locale code for formatting (e.g. 'en', 'si', 'ta').", max_length=10)),
                ('bio', models.TextField(blank=True, default='', help_text='Short bio or description.')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the most recent login.', null=True)),
                ('user', models.OneToOneField(help_text='The platform user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'users_userprofile',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this role was assigned.')),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the user's primary role.")),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The user who assigned this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='The role assigned to the user.', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role')),
                ('user_profile', models.ForeignKey(help_text='The user profile this role is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'db_table': 'users_userrole',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to this user profile.', related_name='user_profiles', through='users.UserRole', to='users.role'),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('account_locked', 'Account Locked')], db_index=True, help_text='Type of authentication event.', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at the time of the event.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser / client user-agent string.')),
                ('success', models.BooleanField(default=True, help_text='Whether the authentication event was successful.')),
                ('failure_reason', models.CharField(blank=True, default='', help_text='Reason for failure (when success=False).', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the authentication event occurred.')),
                ('user', models.ForeignKey(help_text='The user who performed this authentication event.', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
                'db_table': 'users_loginhistory',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='idx_login_history_user_time'), models.Index(fields=['event_type', '-timestamp'], name='idx_login_history_event_time'), models.Index(fields=['ip_address'], name='idx_login_history_ip')],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('slug',), name='unique_active_role_slug'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user_profile', 'role'), name='unique_user_role'),
        ),
    ]
