# Generated by Django 5.2.11 on 2026-02-21 12:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text='Legal or trading name of the supplier.', max_length=255, unique=True, verbose_name='Supplier Name')),
                ('contact_person', models.CharField(blank=True, default='', help_text='Name of the primary contact at the supplier.', max_length=255, verbose_name='Contact Person')),
                ('email', models.EmailField(blank=True, default='', help_text='Primary email address for the supplier.', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', help_text='Primary phone number (+94 XX XXX XXXX format).', max_length=30, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, default='', help_text='Mobile phone number.', max_length=30, verbose_name='Mobile')),
                ('website', models.URLField(blank=True, default='', help_text='Supplier website URL.', verbose_name='Website')),
                ('address_line_1', models.CharField(blank=True, default='', help_text='Primary business address line.', max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, default='', help_text='Secondary address line.', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, default='', max_length=100, verbose_name='State / Province')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='Sri Lanka', max_length=100, verbose_name='Country')),
                ('tax_id', models.CharField(blank=True, db_index=True, default='', help_text='Sri Lankan business registration number (BRN) or tax identification number (TIN).', max_length=50, verbose_name='Tax ID / BRN')),
                ('vat_number', models.CharField(blank=True, default='', help_text='VAT registration number (if applicable).', max_length=50, verbose_name='VAT Number')),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days'), ('cod', 'Cash on Delivery')], default='net_30', help_text='Agreed payment terms with the supplier.', max_length=20, verbose_name='Payment Terms')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this supplier is active for purchase orders.', verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about this supplier.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'vendors_supplier',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_supplier_active'), models.Index(fields=['email'], name='idx_supplier_email'), models.Index(fields=['payment_terms'], name='idx_supplier_payment_terms')],
            },
        ),
    ]
