# Generated by Django 5.2.11 on 2026-03-23 00:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('vendor_code', models.CharField(blank=True, db_index=True, default='', help_text='Auto-generated unique vendor code (VND-NNNNN).', max_length=20, unique=True, verbose_name='Vendor Code')),
                ('company_name', models.CharField(help_text='Legal or trading name of the vendor.', max_length=200, verbose_name='Company Name')),
                ('display_name', models.CharField(blank=True, default='', help_text='Short display name for the vendor.', max_length=200, verbose_name='Display Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('pending_approval', 'Pending Approval')], db_index=True, default='pending_approval', max_length=30, verbose_name='Status')),
                ('vendor_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('importer', 'Importer'), ('service', 'Service Provider')], default='manufacturer', max_length=30, verbose_name='Vendor Type')),
                ('business_registration', models.CharField(blank=True, default='', help_text='Business registration number.', max_length=50, verbose_name='Business Registration')),
                ('tax_id', models.CharField(blank=True, db_index=True, default='', help_text='Tax identification number (TIN/BRN).', max_length=50, verbose_name='Tax ID')),
                ('is_local_vendor', models.BooleanField(default=True, help_text='Whether this is a local (Sri Lankan) vendor.', verbose_name='Local Vendor')),
                ('country', models.CharField(default='Sri Lanka', max_length=100, verbose_name='Country')),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='District')),
                ('province', models.CharField(blank=True, default='', max_length=100, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('primary_email', models.EmailField(blank=True, db_index=True, default='', max_length=255, verbose_name='Primary Email')),
                ('secondary_email', models.EmailField(blank=True, default='', max_length=255, verbose_name='Secondary Email')),
                ('primary_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Primary Phone')),
                ('secondary_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Secondary Phone')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='Mobile')),
                ('fax', models.CharField(blank=True, default='', max_length=20, verbose_name='Fax')),
                ('website', models.URLField(blank=True, default='', max_length=255, verbose_name='Website')),
                ('payment_terms_days', models.IntegerField(default=30, help_text='Number of days for payment after invoice.', verbose_name='Payment Terms (Days)')),
                ('payment_terms_description', models.CharField(blank=True, default='', max_length=100, verbose_name='Payment Terms Description')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Credit Limit')),
                ('currency', models.CharField(default='LKR', max_length=3, verbose_name='Currency')),
                ('requires_purchase_order', models.BooleanField(default=True, verbose_name='Requires Purchase Order')),
                ('accepts_returns', models.BooleanField(default=True, verbose_name='Accepts Returns')),
                ('default_lead_time_days', models.IntegerField(default=7, verbose_name='Default Lead Time (Days)')),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Minimum Order Value')),
                ('minimum_order_quantity', models.IntegerField(blank=True, null=True, verbose_name='Minimum Order Quantity')),
                ('order_multiple', models.IntegerField(blank=True, null=True, verbose_name='Order Multiple')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal Notes')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='Rating')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Total Orders')),
                ('total_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Spend')),
                ('last_rating_update', models.DateTimeField(blank=True, null=True, verbose_name='Last Rating Update')),
                ('is_preferred_vendor', models.BooleanField(default=False, verbose_name='Preferred Vendor')),
                ('first_order_date', models.DateField(blank=True, null=True, verbose_name='First Order Date')),
                ('last_order_date', models.DateField(blank=True, null=True, verbose_name='Last Order Date')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/', verbose_name='Logo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors_vendor',
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['vendor_code'], name='idx_vendor_code'), models.Index(fields=['company_name'], name='idx_vendor_company'), models.Index(fields=['status'], name='idx_vendor_status'), models.Index(fields=['primary_email'], name='idx_vendor_email'), models.Index(fields=['status', 'vendor_type'], name='idx_vendor_status_type')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('vendor_code', ''), _negated=True), fields=('vendor_code',), name='uq_vendor_code_nonempty')],
            },
        ),
    ]
