# Generated by Django 5.2.11 on 2026-03-23 00:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_sp10_group_a_vendor_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('address_type', models.CharField(choices=[('main', 'Main Office'), ('warehouse', 'Warehouse'), ('billing', 'Billing Address'), ('shipping', 'Shipping Address')], default='main', max_length=30)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(default='Sri Lanka', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Address',
                'verbose_name_plural': 'Vendor Addresses',
                'db_table': 'vendors_vendor_address',
                'ordering': ['-is_default', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='VendorBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(blank=True, default='', max_length=11)),
                ('branch_code', models.CharField(blank=True, default='', max_length=20)),
                ('iban', models.CharField(blank=True, default='', max_length=34)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bank_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Bank Account',
                'verbose_name_plural': 'Vendor Bank Accounts',
                'db_table': 'vendors_vendor_bank_account',
                'ordering': ['-is_default', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('sales', 'Sales Representative'), ('accounts', 'Accounts Manager'), ('logistics', 'Logistics Coordinator'), ('manager', 'Manager'), ('support', 'Technical Support'), ('other', 'Other')], default='sales', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Contact',
                'verbose_name_plural': 'Vendor Contacts',
                'db_table': 'vendors_vendor_contact',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
    ]
