# Generated by Django 5.2.11 on 2026-03-23 00:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_sp07_error_message_field'),
        ('vendors', '0003_sp10_group_b_contacts_bank_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(max_length=200)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_price_lists_created', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Price List',
                'verbose_name_plural': 'Vendor Price Lists',
                'db_table': 'vendors_vendor_price_list',
                'ordering': ['-is_current', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='VendorPriceListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_qty', models.IntegerField(default=1)),
                ('max_qty', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendors.vendorpricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_price_list_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Vendor Price List Item',
                'verbose_name_plural': 'Vendor Price List Items',
                'db_table': 'vendors_vendor_price_list_item',
                'ordering': ['product'],
                'constraints': [models.UniqueConstraint(fields=('price_list', 'product'), name='uq_price_list_product')],
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('vendor_sku', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_product_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('bulk_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bulk_qty', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('min_order_qty', models.IntegerField(default=1)),
                ('order_multiple', models.IntegerField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('last_ordered_date', models.DateField(blank=True, null=True)),
                ('last_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Product',
                'verbose_name_plural': 'Vendor Products',
                'db_table': 'vendors_vendor_product',
                'ordering': ['vendor', 'product'],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'product'), name='uq_vendor_product')],
            },
        ),
    ]
