# Generated by Django 5.2.11 on 2026-03-23 00:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_sp10_group_c_vendor_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('comm_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('meeting', 'Meeting'), ('site_visit', 'Site Visit'), ('other', 'Other')], default='email', max_length=30, verbose_name='Communication Type')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('contact_date', models.DateTimeField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, default='')),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_communications', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Communication',
                'verbose_name_plural': 'Vendor Communications',
                'db_table': 'vendors_vendor_communication',
                'ordering': ['-contact_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='On-time delivery percentage (0-100).', max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quality score percentage (0-100).', max_digits=5)),
                ('avg_response_time_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average response time in hours.', max_digits=10)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overall rating (0.00-5.00).', max_digits=3)),
                ('total_orders_count', models.IntegerField(default=0)),
                ('orders_on_time', models.IntegerField(default=0)),
                ('orders_late', models.IntegerField(default=0)),
                ('items_received', models.IntegerField(default=0)),
                ('items_defective', models.IntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_perf_calculations', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Performance',
                'verbose_name_plural': 'Vendor Performance Records',
                'db_table': 'vendors_vendor_performance',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'period_start', 'period_end'), name='uq_vendor_performance_period')],
            },
        ),
    ]
