# Generated by Django 5.2.11 on 2026-03-23 01:01

import apps.vendors.models.vendor_document
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_sp10_group_d_performance_communication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('certificate', 'Certificate'), ('price_list', 'Price List'), ('license', 'License'), ('other', 'Other')], default='contract', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.vendors.models.vendor_document.vendor_document_upload_path)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vendor_documents', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Document',
                'verbose_name_plural': 'Vendor Documents',
                'db_table': 'vendors_vendor_document',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='VendorHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('change_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], default='update', max_length=20)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_changes', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor History',
                'verbose_name_plural': 'Vendor Histories',
                'db_table': 'vendors_vendor_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
