# Generated by Django 5.2.11 on 2026-03-23 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_sp10_group_e_documents_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_type'], name='idx_vendor_type'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['rating'], name='idx_vendor_rating'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_preferred_vendor'], name='idx_vendor_preferred'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_preferred_vendor', 'rating'], name='idx_vendor_preferred_rating'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='vendor_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(condition=models.Q(('payment_terms_days__gte', 0)), name='vendor_payment_terms_positive'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0), ('credit_limit__isnull', True), _connector='OR'), name='vendor_credit_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(condition=models.Q(('default_lead_time_days__gte', 0)), name='vendor_lead_time_positive'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('tax_id',), name='vendor_tax_id_unique'),
        ),
    ]
