# Generated by Django 5.2.11 on 2026-03-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_sp10_audit_indexes_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcontact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='role',
            field=models.CharField(choices=[('sales', 'Sales Representative'), ('accounts', 'Accounts Manager'), ('logistics', 'Logistics Coordinator'), ('manager', 'Manager'), ('support', 'Technical Support'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
