# Generated by Django 5.2.11 on 2026-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_sp10_audit_contact_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorcommunication',
            old_name='comm_type',
            new_name='communication_type',
        ),
        migrations.AddField(
            model_name='vendorcommunication',
            name='is_follow_up_complete',
            field=models.BooleanField(default=False),
        ),
    ]
