# Generated by Django 5.2.11 on 2026-03-23 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_sp10_audit_communication_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendorhistory',
            index=models.Index(fields=['vendor'], name='idx_vh_vendor'),
        ),
        migrations.AddIndex(
            model_name='vendorhistory',
            index=models.Index(fields=['changed_at'], name='idx_vh_changed_at'),
        ),
    ]
