# Generated by Django 5.2.11 on 2026-02-19 07:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('platform_name', models.CharField(default='LankaCommerce Cloud', help_text='Display name of the platform shown across the UI.', max_length=150)),
                ('logo_url', models.URLField(blank=True, default='', help_text='URL to the platform logo image.', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('primary_color', models.CharField(default='#1E40AF', help_text='Primary brand color in hex format (e.g. #1E40AF).', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #1E40AF).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('support_email', models.EmailField(default='support@lankacommerce.lk', help_text='Primary support email address displayed to users.', max_length=254)),
                ('support_phone', models.CharField(default='+94 11 000 0000', help_text='Support phone number in +94 (Sri Lanka) format.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Sri Lankan phone number in +94 format.', regex='^\\+94\\s?\\d{2}\\s?\\d{3}\\s?\\d{4}$')])),
                ('default_timezone', models.CharField(default='Asia/Colombo', help_text='Platform default timezone. Uses Asia/Colombo for Sri Lanka.', max_length=50)),
                ('default_currency', models.CharField(default='LKR', help_text='Default currency code (ISO 4217). LKR for Sri Lankan Rupee (₨).', max_length=3)),
                ('enable_webstore', models.BooleanField(default=True, help_text='Enable the public webstore/e-commerce storefront globally.')),
                ('enable_api_access', models.BooleanField(default=True, help_text='Enable REST API access for tenants.')),
                ('enable_multi_currency', models.BooleanField(default=False, help_text='Enable multi-currency support across the platform.')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When enabled, the platform displays a maintenance page to all non-admin users.')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default tax rate as a percentage (e.g. 15.00 for 15%).', max_digits=5)),
                ('tax_inclusive_pricing', models.BooleanField(default=True, help_text='When True, displayed prices include tax. Standard practice in Sri Lanka.')),
                ('billing_currency', models.CharField(default='LKR', help_text='Currency used for platform billing and invoices (ISO 4217).', max_length=3)),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Enable email notifications for platform events.')),
                ('enable_sms_notifications', models.BooleanField(default=False, help_text='Enable SMS notifications. Requires SMS provider integration.')),
                ('notification_sender_email', models.EmailField(default='noreply@lankacommerce.lk', help_text='Default sender email address for platform notifications.', max_length=254)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_platformsetting',
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('email', models.EmailField(db_index=True, help_text='Email address used as the login identifier.', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', help_text="User's first name.", max_length=150)),
                ('last_name', models.CharField(blank=True, default='', help_text="User's last name.", max_length=150)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number in +94 (Sri Lanka) format.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Sri Lankan phone number in +94 format.', regex='^\\+94\\s?\\d{2}\\s?\\d{3}\\s?\\d{4}$')])),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('platform_admin', 'Platform Admin'), ('support', 'Support'), ('viewer', 'Viewer')], db_index=True, default='viewer', help_text="Platform role determining the user's access level. Super Admin has full access, Viewer is read-only.", max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user account is active. Deactivate instead of deleting accounts.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user can access the Django admin site.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time when the user account was created.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Platform User',
                'verbose_name_plural': 'Platform Users',
                'db_table': 'platform_platformuser',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('action', models.CharField(choices=[('CRUD', [('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')]), ('Authentication', [('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed')]), ('Lifecycle', [('activate', 'Activate'), ('deactivate', 'Deactivate')]), ('Data', [('import_data', 'Import Data'), ('export_data', 'Export Data')]), ('Configuration', [('config_change', 'Config Change')])], db_index=True, help_text='The type of action performed. Categorized into CRUD, Authentication, Lifecycle, Data, and Configuration.', max_length=20)),
                ('resource_type', models.CharField(db_index=True, help_text='The type of resource acted upon (e.g. subscription_plan, feature_flag, tenant, platform_user, platform_setting).', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', help_text='The primary key of the affected resource, stored as a string to accommodate both UUID and integer keys.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of the action performed.', max_length=1000)),
                ('actor_email', models.CharField(blank=True, default='', help_text='Denormalized email of the actor at the time of the action. Preserved even if the user account is deleted.', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client that initiated the action. Supports both IPv4 and IPv6 addresses.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured metadata providing additional context for the action. Examples: changed field values, request parameters, error details, previous state snapshots.')),
                ('user_agent', models.CharField(blank=True, default='', help_text='Browser or client user agent string.', max_length=500)),
                ('actor', models.ForeignKey(blank=True, help_text='The platform user who performed the action. Null if the user has been deleted or the action was performed by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'platform_auditlog',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('key', models.CharField(db_index=True, help_text='Unique identifier for the feature flag. Use lowercase snake_case with a module prefix (e.g. webstore.live_chat).', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for the feature flag.', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Description of what this feature flag controls.', max_length=500)),
                ('rollout_percentage', models.IntegerField(default=0, help_text='Percentage of tenants that receive this feature (0-100). 0 = disabled for all, 100 = enabled for all. Values between allow gradual rollout.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_public', models.BooleanField(default=False, help_text='Whether this flag is visible to tenant administrators. Non-public flags are managed only by platform admins.')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'platform_featureflag',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='idx_feature_flag_key'), models.Index(fields=['is_active'], name='idx_feature_flag_active'), models.Index(fields=['is_active', 'is_public'], name='idx_feature_flag_active_public')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text="Display name of the subscription plan (e.g., 'Starter', 'Pro').", max_length=100, unique=True, verbose_name='Plan name')),
                ('slug', models.SlugField(help_text='URL-safe identifier, auto-generated from plan name.', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the plan and its features.', verbose_name='Description')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, help_text='Monthly subscription price in Sri Lankan Rupees (₨).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly price (LKR)')),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, help_text='Annual subscription price in Sri Lankan Rupees (₨).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual price (LKR)')),
                ('default_billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', help_text='Default billing interval when a tenant subscribes to this plan.', max_length=10, verbose_name='Default billing cycle')),
                ('is_free', models.BooleanField(default=False, help_text='Whether this plan is free (no payment required).', verbose_name='Free plan')),
                ('has_trial', models.BooleanField(default=True, help_text='Whether this plan offers a trial period before billing starts.', verbose_name='Has trial period')),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='Number of trial days before billing begins.', verbose_name='Trial days')),
                ('max_users', models.IntegerField(default=1, help_text='Maximum number of users allowed. Use -1 for unlimited.', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Max users')),
                ('max_products', models.IntegerField(default=100, help_text='Maximum number of products allowed. Use -1 for unlimited.', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Max products')),
                ('max_locations', models.IntegerField(default=1, help_text='Maximum number of store locations allowed. Use -1 for unlimited.', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Max locations')),
                ('storage_limit_mb', models.IntegerField(default=512, help_text='Maximum storage in megabytes. Use -1 for unlimited.', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Storage limit (MB)')),
                ('max_monthly_transactions', models.IntegerField(default=1000, help_text='Maximum transactions per month. Use -1 for unlimited.', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Max monthly transactions')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Whether this plan is archived (hidden from new subscriptions).', verbose_name='Archived')),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='Whether this plan is visible on the public pricing page.', verbose_name='Publicly visible')),
                ('feature_keys', models.JSONField(blank=True, default=list, help_text='List of enabled feature keys for this plan. Example: ["multi_currency", "api_access"].', verbose_name='Feature keys')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordering for plan display (lower numbers appear first).', verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'monthly_price'],
                'indexes': [models.Index(fields=['is_active', 'is_public', 'display_order'], name='idx_subplan_active_order'), models.Index(fields=['slug'], name='idx_subplan_slug'), models.Index(fields=['is_archived', 'is_active'], name='idx_subplan_archived')],
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Billing amount in LKR (Sri Lankan Rupees, ₨).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount in LKR applied to this billing record.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount (amount + tax) in LKR.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='LKR', help_text='ISO 4217 currency code. Defaults to LKR.', max_length=3)),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique invoice number for this billing record. Format: INV-YYYYMM-NNNNN.', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes or comments for this billing record.', max_length=1000)),
                ('business_registration_number', models.CharField(blank=True, default='', help_text='Sri Lanka Business Registration Number for tax compliance. Formats: PV12345, PB12345, GA12345.', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid Sri Lanka Business Registration Number. Accepted formats: PV12345, PB12345, GA12345, or numeric.', regex='^[A-Z]{2}\\d{5,}$|^\\d{5,}$')])),
                ('brn_validated', models.BooleanField(default=False, help_text='Whether the BRN has been validated.')),
                ('brn_validated_on', models.DateTimeField(blank=True, help_text='Timestamp when the BRN was last validated.', null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', help_text='Billing cycle for this record (monthly or annual).', max_length=10)),
                ('period_start', models.DateField(help_text='Start date of the billing period.')),
                ('period_end', models.DateField(help_text='End date of the billing period.')),
                ('due_date', models.DateField(help_text='Payment due date for this billing record.')),
                ('billing_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current payment status: pending, paid, overdue, cancelled, or refunded.', max_length=20)),
                ('paid_on', models.DateTimeField(blank=True, help_text='Timestamp when payment was received.', null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this billing record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='tenants.tenant')),
                ('subscription_plan', models.ForeignKey(blank=True, help_text='The subscription plan associated with this billing record. Null if the plan has been deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='platform.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Billing Record',
                'verbose_name_plural': 'Billing Records',
                'db_table': 'platform_billingrecord',
                'ordering': ['-period_start', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_enabled', models.BooleanField(help_text='Whether the feature is enabled for this tenant. True = force-enable, False = force-disable. This value supersedes the global flag state.')),
                ('reason', models.TextField(blank=True, default='', help_text='Optional explanation for why this override was created. Useful for auditing and understanding override decisions.', max_length=500)),
                ('feature_flag', models.ForeignKey(help_text='The feature flag being overridden for this tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_overrides', to='platform.featureflag')),
                ('tenant', models.ForeignKey(help_text='The tenant this override applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Feature Override',
                'verbose_name_plural': 'Tenant Feature Overrides',
                'db_table': 'platform_tenantfeatureoverride',
                'ordering': ['tenant', 'feature_flag'],
            },
        ),
        migrations.AddIndex(
            model_name='platformuser',
            index=models.Index(fields=['email'], name='idx_platform_user_email'),
        ),
        migrations.AddIndex(
            model_name='platformuser',
            index=models.Index(fields=['is_active', 'is_staff'], name='idx_platform_user_active_staff'),
        ),
        migrations.AddIndex(
            model_name='platformuser',
            index=models.Index(fields=['role'], name='idx_platform_user_role'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='idx_auditlog_action'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type'], name='idx_auditlog_resource_type'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='idx_auditlog_resource'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='idx_auditlog_actor'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_on'], name='idx_auditlog_created'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_on'], name='idx_auditlog_action_created'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['tenant', '-period_start'], name='idx_billing_tenant_period'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['billing_status'], name='idx_billing_status'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['invoice_number'], name='idx_billing_invoice'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['tenant', 'billing_status'], name='idx_billing_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['due_date', 'billing_status'], name='idx_billing_due_status'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['-created_on'], name='idx_billing_created'),
        ),
        migrations.AddIndex(
            model_name='tenantfeatureoverride',
            index=models.Index(fields=['tenant', 'feature_flag'], name='idx_override_tenant_flag'),
        ),
        migrations.AddIndex(
            model_name='tenantfeatureoverride',
            index=models.Index(fields=['feature_flag'], name='idx_override_flag'),
        ),
        migrations.AddIndex(
            model_name='tenantfeatureoverride',
            index=models.Index(fields=['tenant'], name='idx_override_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantfeatureoverride',
            unique_together={('tenant', 'feature_flag')},
        ),
    ]
