export const CMS_TEST_IDS = {
  pageLayout: 'cms-page-layout',
  pageHeader: 'cms-page-header',
  pageContent: 'cms-page-content',
  richContent: 'cms-rich-content',
  aboutPage: 'about-page',
  aboutHero: 'about-hero',
  aboutStory: 'about-story',
  aboutValues: 'about-values',
  contactPage: 'contact-page',
  contactForm: 'contact-form',
  contactInfo: 'contact-info',
  faqPage: 'faq-page',
  faqSearch: 'faq-search',
  faqAccordion: 'faq-accordion',
  termsPage: 'terms-page',
  privacyPage: 'privacy-page',
  returnsPage: 'returns-page',
  shippingPage: 'shipping-page',
  blogList: 'blog-list',
  blogGrid: 'blog-grid',
  blogPostCard: 'blog-post-card',
  blogDetail: 'blog-detail',
  blogShare: 'blog-share',
  tableOfContents: 'table-of-contents',
} as const;
