# Generated by Django 5.2.11 on 2026-02-21 12:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('order_number', models.CharField(db_index=True, help_text='Unique order identifier within the tenant. Uses tenant-specific prefix + sequence.', max_length=50, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', help_text='Current status in the order workflow.', max_length=20, verbose_name='Order Status')),
                ('order_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time the order was placed (Asia/Colombo).', verbose_name='Order Date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all order item amounts before tax and discount.', max_digits=10, verbose_name='Subtotal (LKR)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount for the order.', max_digits=10, verbose_name='Tax Amount (LKR)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount applied to the order.', max_digits=10, verbose_name='Discount Amount (LKR)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final amount payable (subtotal + tax - discount).', max_digits=10, verbose_name='Total Amount (LKR)')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this order.', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(help_text='The customer who placed this order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders_order',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, help_text='Number of units ordered. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit at the time of order, in LKR (₨).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price (LKR)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to this line item, in LKR (₨).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount (LKR)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount for this line item, in LKR (₨).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax Amount (LKR)')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='Total amount for this line item, in LKR (₨).', max_digits=10, verbose_name='Line Total (LKR)')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this line item.', verbose_name='Notes')),
                ('order', models.ForeignKey(help_text='The parent order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(help_text='The product being ordered.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'orders_orderitem',
                'ordering': ['created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'order_date'], name='idx_order_status_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='idx_order_customer_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_date'], name='idx_order_date_desc'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='idx_orderitem_order_product'),
        ),
    ]
