# Generated by Django 5.2.11 on 2026-03-16 15:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_sp05_group_b_line_item_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('order_number_prefix', models.CharField(default='ORD', max_length=10)),
                ('order_number_separator', models.CharField(default='-', max_length=5)),
                ('order_number_padding', models.IntegerField(default=5)),
                ('include_year_in_number', models.BooleanField(default=True)),
                ('auto_confirm_pos_orders', models.BooleanField(default=True)),
                ('auto_confirm_webstore_orders', models.BooleanField(default=False)),
                ('auto_confirm_manual_orders', models.BooleanField(default=False)),
                ('auto_confirm_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-confirm orders below this value.', max_digits=12, null=True)),
                ('auto_reserve_stock', models.BooleanField(default=True)),
                ('allow_backorders', models.BooleanField(default=False)),
                ('allow_partial_fulfillment', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='LKR', max_length=3)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_inclusive_pricing', models.BooleanField(default=False)),
                ('require_approval_above', models.DecimalField(blank=True, decimal_places=2, help_text='Orders above this amount require manager approval.', max_digits=12, null=True)),
                ('allow_order_editing', models.BooleanField(default=True)),
                ('lock_after_confirmation', models.BooleanField(default=False)),
                ('default_shipping_method', models.CharField(blank=True, default='', max_length=50)),
                ('default_payment_terms', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Order Settings',
                'verbose_name_plural': 'Order Settings',
                'db_table': 'orders_ordersettings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='duplicated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicated_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('event_type', models.CharField(choices=[('created', 'Order Created'), ('status_changed', 'Status Changed'), ('confirmed', 'Order Confirmed'), ('processing', 'Processing Started'), ('shipped', 'Order Shipped'), ('delivered', 'Order Delivered'), ('completed', 'Order Completed'), ('cancelled', 'Order Cancelled'), ('returned', 'Order Returned'), ('field_updated', 'Field Updated'), ('line_item_added', 'Line Item Added'), ('line_item_updated', 'Line Item Updated'), ('line_item_removed', 'Line Item Removed'), ('discount_applied', 'Discount Applied'), ('discount_removed', 'Discount Removed'), ('tax_recalculated', 'Tax Recalculated'), ('totals_recalculated', 'Totals Recalculated'), ('payment_received', 'Payment Received'), ('payment_refunded', 'Payment Refunded'), ('stock_reserved', 'Stock Reserved'), ('stock_released', 'Stock Released'), ('fulfillment_started', 'Fulfillment Started'), ('fulfillment_completed', 'Fulfillment Completed'), ('shipment_created', 'Shipment Created'), ('note_added', 'Note Added'), ('customer_notified', 'Customer Notified'), ('duplicated', 'Order Duplicated'), ('converted_from_quote', 'Converted From Quote'), ('converted_from_pos', 'Converted From POS'), ('imported', 'Order Imported'), ('locked', 'Order Locked'), ('unlocked', 'Order Unlocked')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('actor_name', models.CharField(blank=True, default='', max_length=200)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_actions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order Histories',
                'db_table': 'orders_orderhistory',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['order', '-created_on'], name='idx_orderhist_order_date'), models.Index(fields=['event_type'], name='idx_orderhist_event_type')],
            },
        ),
    ]
