# Generated by Django 5.2.11 on 2026-03-16 15:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_sp10_group_d_supplier_lead_time'),
        ('orders', '0004_sp05_group_c_history_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('fulfillment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('picking', 'Picking'), ('picked', 'Picked'), ('packing', 'Packing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('carrier', models.CharField(blank=True, default='', max_length=50)),
                ('tracking_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('tracking_url', models.URLField(blank=True, default='', max_length=500)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('delivery_confirmed', models.BooleanField(default=False)),
                ('delivery_recipient', models.CharField(blank=True, default='', max_length=200)),
                ('delivery_signature', models.TextField(blank=True, default='')),
                ('delivery_photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg', max_digits=8, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='{"length": cm, "width": cm, "height": cm}')),
                ('volumetric_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requires_special_handling', models.BooleanField(default=False)),
                ('special_handling_notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fulfillments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='orders.order')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_fulfillments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Fulfillment',
                'verbose_name_plural': 'Fulfillments',
                'db_table': 'orders_fulfillment',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantity being fulfilled in this shipment.', max_digits=12)),
                ('bin_location', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('qc_passed', models.BooleanField(blank=True, null=True)),
                ('qc_notes', models.TextField(blank=True, default='')),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.fulfillment')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_fulfillment_items', to=settings.AUTH_USER_MODEL)),
                ('order_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_items', to='orders.orderlineitem')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_fulfillment_items', to=settings.AUTH_USER_MODEL)),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_fulfillment_items', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_line_items', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Fulfillment Line Item',
                'verbose_name_plural': 'Fulfillment Line Items',
                'db_table': 'orders_fulfillmentlineitem',
                'ordering': ['order_line_item__position'],
            },
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['order', 'status'], name='idx_fulfillment_order_status'),
        ),
        migrations.AlterUniqueTogether(
            name='fulfillmentlineitem',
            unique_together={('fulfillment', 'order_line_item')},
        ),
    ]
