# Generated by Django 5.2.11 on 2026-03-16 15:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_sp05_group_d_fulfillment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('return_number', models.CharField(help_text='Auto-generated: RET-{YEAR}-{SEQ}', max_length=50, unique=True, verbose_name='Return Number')),
                ('reason', models.CharField(choices=[('defective', 'Defective'), ('wrong_item', 'Wrong Item'), ('changed_mind', 'Changed Mind'), ('not_as_described', 'Not As Described'), ('better_price', 'Better Price'), ('duplicate', 'Duplicate Order'), ('other', 'Other')], default='other', max_length=30)),
                ('reason_detail', models.TextField(blank=True, default='', help_text='Additional details about the return reason.')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('refunded', 'Refunded')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_shipping', models.BooleanField(default=False, help_text='Whether shipping costs are included in the refund.')),
                ('refund_method', models.CharField(blank=True, choices=[('original_payment', 'Original Payment Method'), ('store_credit', 'Store Credit'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='', max_length=30)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order', verbose_name='Order')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_returns', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order_return',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('condition', models.CharField(blank=True, choices=[('unopened', 'Unopened'), ('opened', 'Opened'), ('damaged', 'Damaged')], default='', max_length=20)),
                ('inspected', models.BooleanField(default=False)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True, default='')),
                ('unit_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('restocking_fee_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_restored', models.BooleanField(default=False)),
                ('stock_restored_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_return_items', to=settings.AUTH_USER_MODEL)),
                ('order_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.orderlineitem', verbose_name='Order Line Item')),
                ('order_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_line_items', to='orders.orderreturn', verbose_name='Return')),
            ],
            options={
                'db_table': 'orders_return_line_item',
            },
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['order', 'status'], name='idx_return_order_status'),
        ),
        migrations.AlterUniqueTogether(
            name='returnlineitem',
            unique_together={('order_return', 'order_line_item')},
        ),
    ]
