# Generated by Django 5.2.11 on 2026-03-17 01:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_sp05_group_a_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lock_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='lock_reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='source',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('api', 'API'), ('system', 'System'), ('import', 'Import')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='allow_manual_price_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='auto_cancel_unpaid_after_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='cancel_on_insufficient_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='default_priority',
            field=models.CharField(blank=True, default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='high_value_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='order_number_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='require_approval_for_discounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='require_manager_approval_for_high_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='require_payment_for_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='reset_numbering_yearly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='send_confirmation_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='send_shipping_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='show_unit_price_to_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='use_sequential_numbering',
            field=models.BooleanField(default=True),
        ),
    ]
