# Generated by Django 5.2.11 on 2026-03-17 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_sp05_group_c_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='carrier_service',
            field=models.CharField(blank=True, default='', help_text='Specific carrier service level (e.g. Express, Standard)', max_length=100),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fulfillments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='customer_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='customs_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='customs_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='delivery_failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='delivery_status',
            field=models.CharField(blank=True, default='', help_text='Last known delivery status from carrier', max_length=50),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='estimated_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='is_fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='last_tracking_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='number_of_packages',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='package_type',
            field=models.CharField(blank=True, default='', help_text='e.g. box, envelope, pallet', max_length=50),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='requires_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=5),
        ),
        migrations.AddField(
            model_name='fulfillmentlineitem',
            name='condition',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('defective', 'Defective')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='fulfillmentlineitem',
            name='damage_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('partially_fulfilled', 'Partially Fulfilled'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', max_length=30, verbose_name='Order Status'),
        ),
    ]
