# Generated by Django 5.2.11 on 2026-03-17 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_sp05_group_d_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='approval_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='refund_reference',
            field=models.CharField(blank=True, default='', help_text='Payment gateway refund reference/transaction ID.', max_length=100),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='return_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of return shipping (charged to customer or refunded).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
