# Generated by Django 5.2.11 on 2026-03-25 05:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        ('organization', '0004_departmentmember_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPFSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('employee_rate', models.DecimalField(decimal_places=2, default=8.0, help_text='Employee EPF contribution rate (default 8%).', max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Employer EPF contribution rate (default 12%).', max_digits=5)),
                ('max_contribution_ceiling', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly contribution ceiling (null = no ceiling).', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these EPF settings are currently active.')),
                ('effective_from', models.DateField(blank=True, help_text='Date from which these rates are effective.', null=True)),
            ],
            options={
                'verbose_name': 'EPF Settings',
                'verbose_name_plural': 'EPF Settings',
            },
        ),
        migrations.CreateModel(
            name='ETFSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('employer_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Employer ETF contribution rate (default 3%).', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these ETF settings are currently active.')),
                ('effective_from', models.DateField(blank=True, help_text='Date from which this rate is effective.', null=True)),
            ],
            options={
                'verbose_name': 'ETF Settings',
                'verbose_name_plural': 'ETF Settings',
            },
        ),
        migrations.CreateModel(
            name='PAYETaxSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('tax_year', models.PositiveIntegerField(help_text='Tax year (e.g. 2024) these slabs apply to.')),
                ('from_amount', models.DecimalField(decimal_places=2, help_text='Starting annual amount for this slab.', max_digits=12)),
                ('to_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Ending annual amount (null = no upper limit).', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate percentage for this slab.', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tax slab is currently active.')),
            ],
            options={
                'verbose_name': 'PAYE Tax Slab',
                'verbose_name_plural': 'PAYE Tax Slabs',
                'ordering': ['tax_year', 'from_amount'],
            },
        ),
        migrations.CreateModel(
            name='TaxExemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(help_text="Exemption name (e.g. 'Personal Relief').", max_length=100)),
                ('code', models.CharField(help_text='Unique code for the exemption.', max_length=20, unique=True)),
                ('annual_amount', models.DecimalField(decimal_places=2, help_text='Annual exemption amount.', max_digits=12)),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Monthly exemption amount (annual / 12).', max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this exemption is currently applicable.')),
                ('description', models.TextField(blank=True, default='', help_text='Description of the exemption and its legal basis.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text="Component name (e.g. 'Basic Salary', 'Transport Allowance').", max_length=100)),
                ('code', models.CharField(help_text="Unique uppercase code (e.g. 'BASIC', 'EPF_EE').", max_length=20, unique=True)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('EMPLOYER_CONTRIBUTION', 'Employer Contribution')], help_text='Whether this is an earning, deduction, or employer contribution.', max_length=25)),
                ('category', models.CharField(choices=[('BASIC', 'Basic Salary'), ('ALLOWANCE', 'Allowance'), ('BONUS', 'Bonus'), ('STATUTORY', 'Statutory'), ('LOAN', 'Loan Deduction'), ('TAX', 'Tax'), ('OTHER', 'Other')], help_text='Category classification for grouping and reporting.', max_length=20)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE_OF_BASIC', 'Percentage of Basic Salary'), ('PERCENTAGE_OF_GROSS', 'Percentage of Gross Salary'), ('FORMULA', 'Formula-based')], default='FIXED', help_text='How the component amount is calculated.', max_length=25)),
                ('default_value', models.DecimalField(decimal_places=2, default=0, help_text='Default fixed amount (used when calculation_type is FIXED).', max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage value (used for PERCENTAGE_OF_BASIC or PERCENTAGE_OF_GROSS).', max_digits=5)),
                ('formula', models.TextField(blank=True, default='', help_text='Custom formula expression (used when calculation_type is FORMULA).')),
                ('is_taxable', models.BooleanField(default=True, help_text='Include in PAYE taxable income calculation.')),
                ('is_epf_applicable', models.BooleanField(default=False, help_text='Include in EPF base calculation (8% employee + 12% employer).')),
                ('is_fixed', models.BooleanField(default=True, help_text='Fixed monthly amount (False = attendance/variable-based).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this component is currently available for use.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for payslip display (lower = higher on payslip).')),
                ('description', models.TextField(blank=True, default='', help_text='Description of the component and its purpose.')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='idx_component_code'), models.Index(fields=['component_type'], name='idx_component_type'), models.Index(fields=['category'], name='idx_component_category')],
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('previous_basic', models.DecimalField(decimal_places=2, help_text='Previous basic salary amount.', max_digits=12)),
                ('new_basic', models.DecimalField(decimal_places=2, help_text='New basic salary amount.', max_digits=12)),
                ('previous_gross', models.DecimalField(decimal_places=2, default=0, help_text='Previous gross salary amount.', max_digits=12)),
                ('new_gross', models.DecimalField(decimal_places=2, default=0, help_text='New gross salary amount.', max_digits=12)),
                ('effective_date', models.DateField(help_text='Date from which the new salary is effective.')),
                ('change_reason', models.CharField(choices=[('ANNUAL_INCREMENT', 'Annual Increment'), ('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer'), ('RESTRUCTURE', 'Restructuring'), ('CORRECTION', 'Correction'), ('OTHER', 'Other')], default='OTHER', help_text='Reason for the salary change.', max_length=20)),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional notes about the salary change.')),
                ('employee', models.ForeignKey(help_text='The employee whose salary changed.', on_delete=django.db.models.deletion.PROTECT, related_name='salary_history', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Salary histories',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(help_text="Template name (e.g. 'Executive Package', 'Junior Staff').", max_length=100)),
                ('code', models.CharField(help_text="Unique code for the template (e.g. 'EXEC', 'JR_STAFF').", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the salary template.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this template is currently available.')),
                ('designation', models.ForeignKey(blank=True, help_text='Optional designation this template is tied to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_templates', to='organization.designation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(help_text="Grade name (e.g. 'Grade 1 - Entry Level').", max_length=100)),
                ('code', models.CharField(help_text="Unique grade code (e.g. 'G1', 'G2').", max_length=20, unique=True)),
                ('level', models.PositiveIntegerField(default=1, help_text='Numeric level for ordering (1 = lowest, higher = senior).')),
                ('min_salary', models.DecimalField(decimal_places=2, help_text='Minimum basic salary for this grade.', max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, help_text='Maximum basic salary for this grade.', max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this grade is currently in use.')),
                ('template', models.ForeignKey(blank=True, help_text='Default salary template for this grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='payroll.salarytemplate')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Monthly basic salary amount.', max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, help_text='Calculated gross salary (basic + all earnings).', max_digits=12)),
                ('effective_from', models.DateField(help_text='Date from which this salary is effective.')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this salary is effective (null = ongoing).', null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text="Whether this is the employee's current active salary.")),
                ('employee', models.ForeignKey(help_text='The employee this salary is assigned to.', on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employees.employee')),
                ('template', models.ForeignKey(blank=True, help_text='Salary template used (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_salaries', to='payroll.salarytemplate')),
            ],
            options={
                'verbose_name_plural': 'Employee salaries',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Actual amount for this component.', max_digits=12)),
                ('employee_salary', models.ForeignKey(help_text='The employee salary this component belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='payroll.employeesalary')),
                ('component', models.ForeignKey(help_text='The salary component.', on_delete=django.db.models.deletion.PROTECT, related_name='employee_usages', to='payroll.salarycomponent')),
            ],
            options={
                'unique_together': {('employee_salary', 'component')},
            },
        ),
        migrations.CreateModel(
            name='TemplateComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.DecimalField(decimal_places=2, default=0, help_text='Default amount for this component in this template.', max_digits=12)),
                ('can_override', models.BooleanField(default=True, help_text='Whether this value can be overridden per employee.')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed value when overriding.', max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed value when overriding.', max_digits=12, null=True)),
                ('component', models.ForeignKey(help_text='The salary component being included.', on_delete=django.db.models.deletion.CASCADE, related_name='template_usages', to='payroll.salarycomponent')),
                ('template', models.ForeignKey(help_text='The salary template this component belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarytemplate')),
            ],
            options={
                'ordering': ['component__display_order'],
                'unique_together': {('template', 'component')},
            },
        ),
    ]
