# Generated by Django 5.2.11 on 2026-03-25 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecomponent',
            options={'ordering': ['display_order', 'component__display_order']},
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the grade, typical roles, and requirements.'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for display in UI and reports (lower = first).'),
        ),
        migrations.AddField(
            model_name='templatecomponent',
            name='is_mandatory',
            field=models.BooleanField(default=True, help_text='Whether this component must be included in employee salary.'),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum basic salary for this grade (null for unlimited).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='templatecomponent',
            name='component',
            field=models.ForeignKey(help_text='The salary component being included.', on_delete=django.db.models.deletion.PROTECT, related_name='template_usages', to='payroll.salarycomponent'),
        ),
    ]
