# Generated by Django 5.2.11 on 2026-03-25 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_group_b_audit_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this salary record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='revision_number',
            field=models.IntegerField(default=1, help_text='Revision number for tracking salary versions.'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='revision_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for this salary revision.'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='salary_grade',
            field=models.ForeignKey(blank=True, help_text='Salary grade/band for this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_salaries', to='payroll.salarygrade'),
        ),
        migrations.AddField(
            model_name='employeesalarycomponent',
            name='calculated_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='System-calculated amount before any override.', max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalarycomponent',
            name='is_overridden',
            field=models.BooleanField(default=False, help_text='Whether this amount was manually overridden from the template default.'),
        ),
        migrations.AddField(
            model_name='employeesalarycomponent',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes about this component value or override.'),
        ),
        migrations.AddField(
            model_name='employeesalarycomponent',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage used if component is percentage-based.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who made this salary change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='salary',
            field=models.ForeignKey(blank=True, help_text='The salary record this history entry relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='payroll.employeesalary'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='effective_from',
            field=models.DateField(db_index=True, help_text='Date from which this salary is effective.'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='effective_to',
            field=models.DateField(blank=True, db_index=True, help_text='Date until which this salary is effective (null = ongoing).', null=True),
        ),
    ]
