# Generated by Django 5.2.11 on 2026-03-25 09:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_group_c_audit_fixes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epfsettings',
            options={'ordering': ['-effective_from'], 'verbose_name': 'EPF Settings', 'verbose_name_plural': 'EPF Settings'},
        ),
        migrations.AlterModelOptions(
            name='etfsettings',
            options={'ordering': ['-effective_from'], 'verbose_name': 'ETF Settings', 'verbose_name_plural': 'ETF Settings'},
        ),
        migrations.AlterModelOptions(
            name='payetaxslab',
            options={'ordering': ['tax_year', 'order'], 'verbose_name': 'PAYE Tax Slab', 'verbose_name_plural': 'PAYE Tax Slabs'},
        ),
        migrations.AlterModelOptions(
            name='taxexemption',
            options={'ordering': ['name'], 'verbose_name': 'Tax Exemption', 'verbose_name_plural': 'Tax Exemptions'},
        ),
        migrations.AddField(
            model_name='payetaxslab',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Date from which these slabs become effective.', null=True),
        ),
        migrations.AddField(
            model_name='payetaxslab',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Date when these slabs expire (null = currently active).', null=True),
        ),
        migrations.AddField(
            model_name='payetaxslab',
            name='order',
            field=models.IntegerField(default=0, help_text='Slab sequence number (0, 1, 2, ...) for progressive calculation order.'),
        ),
        migrations.AddField(
            model_name='taxexemption',
            name='exemption_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Relief'), ('SPOUSE', 'Spouse Relief'), ('CHILD', 'Child Relief'), ('DISABLED_CHILD', 'Disabled Child Relief'), ('OTHER', 'Other Exemption')], default='OTHER', help_text='Category of this exemption.', max_length=50),
        ),
        migrations.AddField(
            model_name='taxexemption',
            name='max_claims',
            field=models.IntegerField(blank=True, help_text='Maximum number of times this exemption can be claimed. Leave empty for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='taxexemption',
            name='tax_year',
            field=models.IntegerField(default=2024, help_text='Tax year for which this exemption is applicable (e.g. 2024).'),
        ),
        migrations.AlterField(
            model_name='epfsettings',
            name='employee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Employee EPF contribution rate as percentage (e.g., 8.00 for 8%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='epfsettings',
            name='employer_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Employer EPF contribution rate as percentage (e.g., 12.00 for 12%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='epfsettings',
            name='max_contribution_ceiling',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly earnings amount for EPF calculation. Leave empty for no ceiling.', max_digits=12, null=True, verbose_name='Maximum Contribution Ceiling'),
        ),
        migrations.AlterField(
            model_name='etfsettings',
            name='employer_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Employer ETF contribution rate as percentage (e.g., 3.00 for 3%).', max_digits=5, verbose_name='Employer Rate (%)'),
        ),
        migrations.AlterField(
            model_name='payetaxslab',
            name='from_amount',
            field=models.DecimalField(decimal_places=2, help_text='Annual income starting from this amount (inclusive).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payetaxslab',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 6.00 for 6%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payetaxslab',
            name='to_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual income up to this amount (inclusive). Leave empty for top slab.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='taxexemption',
            name='annual_amount',
            field=models.DecimalField(decimal_places=2, help_text='Annual exemption amount in LKR.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='taxexemption',
            name='code',
            field=models.CharField(help_text="Unique code for programmatic reference (e.g. 'PERSONAL').", max_length=50),
        ),
        migrations.AlterField(
            model_name='taxexemption',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monthly exemption amount (usually annual / 12).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='taxexemption',
            name='name',
            field=models.CharField(help_text="Exemption name (e.g. 'Personal Relief').", max_length=200),
        ),
    ]
