# Generated by Django 5.2.11 on 2026-03-25 10:24

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_group_d_audit_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('effective_from', models.DateField(default=datetime.date.today, help_text='Date from which these settings are effective.')),
                ('notification_email', models.EmailField(blank=True, default='', help_text='Email address for payroll notifications.', max_length=254)),
                ('default_pay_day', models.PositiveSmallIntegerField(default=25, help_text='Default day of the month for salary payments (1-31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('adjust_for_weekends', models.BooleanField(default=True, help_text='If True, adjust pay date when it falls on a weekend.')),
                ('attendance_cutoff_day', models.PositiveSmallIntegerField(default=20, help_text='Day of month for attendance data cutoff (1-31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('use_cutoff_period', models.BooleanField(default=False, help_text='If True, use cutoff-based periods instead of calendar months.')),
                ('require_approval', models.BooleanField(default=True, help_text='Whether payroll requires approval before finalization.')),
                ('min_approvals', models.PositiveSmallIntegerField(default=1, help_text='Minimum number of approvals required.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('auto_create_period', models.BooleanField(default=False, help_text='Automatically create payroll periods each month.')),
                ('auto_create_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month to auto-create the next period (1-28).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('create_months_ahead', models.PositiveSmallIntegerField(default=1, help_text='How many months ahead to auto-create periods.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('approvers', models.ManyToManyField(blank=True, help_text='Users authorized to approve payroll.', related_name='payroll_approver_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Settings',
                'verbose_name_plural': 'Payroll Settings',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('period_month', models.PositiveSmallIntegerField(help_text='Month of the payroll period (1-12).')),
                ('period_year', models.PositiveSmallIntegerField(help_text='Year of the payroll period (e.g. 2025).')),
                ('name', models.CharField(blank=True, help_text="Auto-generated period name (e.g. 'January 2025').", max_length=50)),
                ('start_date', models.DateField(help_text='First day of the payroll period.')),
                ('end_date', models.DateField(help_text='Last day of the payroll period.')),
                ('pay_date', models.DateField(help_text='Scheduled payment date for this period.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('REVERSED', 'Reversed')], default='DRAFT', help_text='Current processing status of this period.', max_length=20)),
                ('total_working_days', models.DecimalField(decimal_places=2, default=0, help_text='Total working days in this period (excludes weekends).', max_digits=5)),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this period is locked for modifications.')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when the period was locked.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes for this payroll period.')),
                ('locked_by', models.ForeignKey(blank=True, help_text='User who locked this period.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-period_year', '-period_month'],
                'indexes': [models.Index(fields=['status'], name='idx_payperiod_status'), models.Index(fields=['period_year', 'period_month'], name='idx_payperiod_ym')],
                'unique_together': {('period_month', 'period_year')},
            },
        ),
    ]
