# Generated by Django 5.2.11 on 2026-03-25 10:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        ('payroll', '0005_sp06_payroll_period_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('run_number', models.PositiveIntegerField(default=1, help_text='Processing sequence number (increments for correction runs).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', help_text='Current processing status of this run.', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when processing began.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when processing completed.', null=True)),
                ('total_employees', models.PositiveIntegerField(default=0, help_text='Number of employees processed in this run.')),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all employee gross salaries.', max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all employee deductions.', max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all employee net salaries.', max_digits=15)),
                ('total_epf_employee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of employee EPF contributions (8%).', max_digits=12)),
                ('total_epf_employer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of employer EPF contributions (12%).', max_digits=12)),
                ('total_etf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of employer ETF contributions (3%).', max_digits=12)),
                ('total_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of PAYE tax deductions.', max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when the run was approved.', null=True)),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Count of employees that failed processing.')),
                ('errors', models.JSONField(blank=True, default=list, help_text='Error details for failed employee processing.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this run.')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the payroll run.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(help_text='The payroll period this run processes.', on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='payroll.payrollperiod')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who initiated the processing.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('salary_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen copy of salary structure at processing time.')),
                ('days_worked', models.PositiveIntegerField(default=0, help_text='Number of days the employee was present.')),
                ('days_absent', models.PositiveIntegerField(default=0, help_text='Number of absent days (paid leave like sick leave).')),
                ('unpaid_leave_days', models.PositiveIntegerField(default=0, help_text='Number of unpaid (no-pay) leave days.')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total overtime hours worked.', max_digits=6)),
                ('late_count', models.PositiveIntegerField(default=0, help_text='Number of late arrivals.')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual basic salary for this period (may be pro-rated).', max_digits=15)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated overtime payment.', max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings before deductions.', max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all deductions.', max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final take-home salary (gross - deductions).', max_digits=15)),
                ('epf_employee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employee EPF contribution (8%).', max_digits=12)),
                ('epf_employer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employer EPF contribution (12%).', max_digits=12)),
                ('etf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employer ETF contribution (3%).', max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PAYE income tax deduction.', max_digits=12)),
                ('bank_account', models.JSONField(blank=True, default=dict, help_text='Snapshot of employee bank account details at processing time.')),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Transaction reference number after payment.', max_length=100)),
                ('payment_date', models.DateField(blank=True, help_text='Date when payment was made.', null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('ON_HOLD', 'On Hold')], default='PENDING', help_text='Payment status for this employee.', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this record has been verified.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes for this employee payroll record.')),
                ('employee', models.ForeignKey(help_text='The employee this payroll record is for.', on_delete=django.db.models.deletion.PROTECT, related_name='employee_payrolls', to='employees.employee')),
                ('employee_salary', models.ForeignKey(blank=True, help_text='Salary record used for calculation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='payroll.employeesalary')),
                ('payroll_run', models.ForeignKey(help_text='The payroll run this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_payrolls', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'Employee Payroll',
                'verbose_name_plural': 'Employee Payrolls',
                'ordering': ['employee'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['status'], name='idx_payrun_status'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('payroll_period', 'run_number')},
        ),
        migrations.AddIndex(
            model_name='employeepayroll',
            index=models.Index(fields=['payment_status'], name='idx_emppay_pmtstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='employeepayroll',
            unique_together={('payroll_run', 'employee')},
        ),
    ]
