# Generated by Django 5.2.11 on 2026-03-25 10:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_sp06_payroll_run_employee_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('line_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('EMPLOYER_CONTRIBUTION', 'Employer Contribution'), ('ADJUSTMENT', 'Adjustment')], help_text='Whether this is an earning, deduction, contribution, or adjustment.', max_length=30)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original component amount from salary structure.', max_digits=12)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount after attendance-based calculations.', max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pro-rata or other adjustments (can be negative).', max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final amount after all adjustments (appears on payslip).', max_digits=12)),
                ('description', models.CharField(blank=True, default='', help_text='Display name for payslip (defaults to component name).', max_length=200)),
                ('calculation_notes', models.JSONField(blank=True, default=dict, help_text='Calculation details for auditing.')),
                ('component', models.ForeignKey(help_text='The salary component this line item represents.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_line_items', to='payroll.salarycomponent')),
                ('employee_payroll', models.ForeignKey(help_text='The employee payroll record this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payroll.employeepayroll')),
            ],
            options={
                'verbose_name': 'Payroll Line Item',
                'verbose_name_plural': 'Payroll Line Items',
                'ordering': ['line_type', 'component'],
            },
        ),
    ]
