# Generated by Django 5.2.11 on 2026-03-25 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_sp06_payroll_line_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPFContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('epf_number', models.CharField(blank=True, default='', max_length=20)),
                ('epf_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total EPF-applicable earnings used as the calculation base.', max_digits=15)),
                ('base_calculation_details', models.JSONField(blank=True, help_text='Breakdown of components that make up the EPF base.', null=True)),
                ('employee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employee EPF contribution (default 8%).', max_digits=15)),
                ('employer_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employer EPF contribution (default 12%).', max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total EPF contribution (employee + employer).', max_digits=15)),
                ('employee_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('calculation_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('employee_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epf_contributions', to='payroll.employeepayroll')),
            ],
            options={
                'verbose_name': 'EPF Contribution',
                'verbose_name_plural': 'EPF Contributions',
                'db_table': 'payroll_epf_contribution',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='ETFContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('etf_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ETF-applicable earnings base (same as EPF base).', max_digits=15)),
                ('base_calculation_details', models.JSONField(blank=True, help_text='Breakdown of components that make up the ETF base.', null=True)),
                ('employer_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employer ETF contribution (default 3%).', max_digits=15)),
                ('etf_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('calculation_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('employee_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etf_contributions', to='payroll.employeepayroll')),
            ],
            options={
                'verbose_name': 'ETF Contribution',
                'verbose_name_plural': 'ETF Contributions',
                'db_table': 'payroll_etf_contribution',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='PAYECalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('gross_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly gross income.', max_digits=15)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual taxable income after exemptions.', max_digits=15)),
                ('epf_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employee EPF contribution (tax-deductible).', max_digits=15)),
                ('exemptions', models.JSONField(blank=True, help_text='Breakdown of tax exemptions applied.', null=True)),
                ('tax_slabs_applied', models.JSONField(blank=True, help_text='Tax slab breakdown showing income and tax per slab.', null=True)),
                ('monthly_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ytd_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Year-to-date gross income.', max_digits=15)),
                ('ytd_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Year-to-date tax paid.', max_digits=15)),
                ('annual_projected_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Projected annual tax based on current month.', max_digits=15)),
                ('calculation_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('employee_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paye_calculations', to='payroll.employeepayroll')),
            ],
            options={
                'verbose_name': 'PAYE Calculation',
                'verbose_name_plural': 'PAYE Calculations',
                'db_table': 'payroll_paye_calculation',
                'ordering': ['-calculation_date'],
            },
        ),
    ]
