# Generated by Django 5.2.11 on 2026-03-25 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_sp06_epf_etf_paye_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FINALIZED', 'Finalized'), ('REVERSED', 'Reversed')], default='DRAFT', help_text='Current processing status of this period.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FINALIZED', 'Finalized'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', help_text='Current processing status of this run.', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSED', 'Processed'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FINALIZED', 'Finalized'), ('REVERSED', 'Reversed'), ('CORRECTED', 'Correction Applied'), ('PAID', 'Marked as Paid'), ('BANK_FILE_GENERATED', 'Bank File Generated')], db_index=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payroll.payrollrun')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_history_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll History',
                'verbose_name_plural': 'Payroll Histories',
                'db_table': 'payroll_history',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['payroll_run', '-performed_at'], name='idx_payhistory_run_date'), models.Index(fields=['performed_by'], name='idx_payhistory_user')],
            },
        ),
    ]
