# Generated by Django 5.2.11 on 2026-03-25 20:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_sp06_approval_finalization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayroll',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether this record is locked (set during finalization).'),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='is_reversed',
            field=models.BooleanField(default=False, help_text='Whether this record has been reversed.'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='bank_file_generated',
            field=models.BooleanField(default=False, help_text='Whether bank file has been generated for this run.'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the run was finalized.', null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='User who finalized the payroll run.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was recorded.', null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Actual date payment was made.', null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text='Bank transaction reference for payment.', max_length=100),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the run was rejected.', null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected the payroll run.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the run was reversed.', null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='User who reversed the payroll run.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the run was submitted for approval.', null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted the run for approval.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this period is locked for modifications.'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text="Auto-generated period name (e.g. 'January 2025').", max_length=50),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_working_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total working days in this period (excludes weekends and public holidays).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='attendance_cutoff_day',
            field=models.PositiveSmallIntegerField(default=20, help_text='Day of month for attendance data cutoff (1-28).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='create_months_ahead',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many months ahead to auto-create periods (0-3).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='default_pay_day',
            field=models.PositiveSmallIntegerField(default=25, help_text='Default day of the month for salary payments (1-28).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
