# Generated by Django 5.2.11 on 2026-03-23 19:12

import apps.employees.models.employee
import apps.employees.validators.nic_validator
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('employee_id', models.CharField(blank=True, db_index=True, help_text='Auto-generated employee identifier (EMP-0001 format).', max_length=20, unique=True, verbose_name='Employee ID')),
                ('first_name', models.CharField(help_text="Employee's given name.", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Employee's family name.", max_length=100, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, default='', help_text="Employee's middle name or initial.", max_length=100, verbose_name='Middle Name')),
                ('preferred_name', models.CharField(blank=True, default='', help_text='Nickname or preferred name for informal use.', max_length=100, verbose_name='Preferred Name')),
                ('profile_photo', models.ImageField(blank=True, help_text="Employee's profile photograph.", null=True, upload_to=apps.employees.models.employee.employee_photo_path, verbose_name='Profile Photo')),
                ('nic_number', models.CharField(blank=True, db_index=True, help_text='Sri Lanka NIC number (old: 912345678V, new: 199112345678).', max_length=15, null=True, unique=True, validators=[apps.employees.validators.nic_validator.validate_nic], verbose_name='NIC Number')),
                ('date_of_birth', models.DateField(blank=True, help_text="Employee's date of birth.", null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], default='', help_text="Employee's gender.", max_length=20, verbose_name='Gender')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='', help_text="Employee's marital status.", max_length=20, verbose_name='Marital Status')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('probation', 'Probation')], db_index=True, default='full_time', help_text='Type of employment (full-time, part-time, contract, etc.).', max_length=20, verbose_name='Employment Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], db_index=True, default='active', help_text='Current employment status.', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal HR notes about this employee.', verbose_name='Notes')),
                ('user', models.OneToOneField(blank=True, help_text='Optional link to a user account for system access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees_employee',
                'ordering': ['employee_id'],
                'indexes': [models.Index(fields=['employee_id'], name='idx_emp_employee_id'), models.Index(fields=['status'], name='idx_emp_status'), models.Index(fields=['nic_number'], name='idx_emp_nic_number'), models.Index(fields=['last_name', 'first_name'], name='idx_emp_name'), models.Index(fields=['employment_type', 'status'], name='idx_emp_type_status')],
            },
        ),
    ]
