# Generated by Django 5.2.11 on 2026-03-23 19:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_sp01_employee_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Official work email address.', max_length=255, verbose_name='Work Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, default='', help_text='Mobile number in +94 XX XXX XXXX format.', max_length=20, verbose_name='Mobile Phone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, default='', help_text='Personal email address (optional).', max_length=255, verbose_name='Personal Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Home or landline number.', max_length=20, verbose_name='Phone (Landline)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(blank=True, default='', help_text='Office/work phone number.', max_length=20, verbose_name='Work Phone'),
        ),
        migrations.CreateModel(
            name='EmployeeFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text='Full name of the family member.', max_length=200, verbose_name='Name')),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('other', 'Other')], help_text='Relationship to the employee.', max_length=20, verbose_name='Relationship')),
                ('date_of_birth', models.DateField(blank=True, help_text="Family member's date of birth.", null=True, verbose_name='Date of Birth')),
                ('occupation', models.CharField(blank=True, default='', help_text="Family member's occupation.", max_length=100, verbose_name='Occupation')),
                ('is_dependent', models.BooleanField(default=False, help_text='Whether this family member is a dependent for benefits.', verbose_name='Is Dependent')),
                ('phone', models.CharField(blank=True, default='', help_text="Family member's phone number.", max_length=20, verbose_name='Phone')),
                ('employee', models.ForeignKey(help_text='Employee this family member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'db_table': 'employees_family',
                'ordering': ['employee', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text='Full name of the emergency contact.', max_length=200, verbose_name='Contact Name')),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('other', 'Other')], help_text='Relationship to the employee.', max_length=20, verbose_name='Relationship')),
                ('phone', models.CharField(help_text='Contact phone number.', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, default='', help_text='Contact email address (optional).', max_length=255, verbose_name='Email')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Contact priority (1 = highest).', verbose_name='Priority')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about this contact.', verbose_name='Notes')),
                ('employee', models.ForeignKey(help_text='Employee this emergency contact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'db_table': 'employees_emergency_contact',
                'ordering': ['employee', 'priority'],
                'indexes': [models.Index(fields=['employee', 'priority'], name='idx_emp_emergency_priority')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('address_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('work', 'Work')], default='permanent', help_text='Type of address (permanent, temporary, work).', max_length=20, verbose_name='Address Type')),
                ('line1', models.CharField(help_text='Street address or house number.', max_length=255, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, default='', help_text='Apartment, suite, or additional address info.', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(help_text='City or town name.', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, default='', help_text='Postal/zip code.', max_length=10, verbose_name='Postal Code')),
                ('province', models.CharField(blank=True, choices=[('western', 'Western'), ('central', 'Central'), ('southern', 'Southern'), ('northern', 'Northern'), ('eastern', 'Eastern'), ('north_western', 'North Western'), ('north_central', 'North Central'), ('uva', 'Uva'), ('sabaragamuwa', 'Sabaragamuwa')], default='', help_text='Sri Lanka province.', max_length=30, verbose_name='Province')),
                ('district', models.CharField(blank=True, default='', help_text='District within the province.', max_length=100, verbose_name='District')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary address.', verbose_name='Primary Address')),
                ('employee', models.ForeignKey(help_text='Employee this address belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Address',
                'verbose_name_plural': 'Employee Addresses',
                'db_table': 'employees_address',
                'ordering': ['employee', '-is_primary', 'address_type'],
                'indexes': [models.Index(fields=['employee', 'address_type'], name='idx_emp_addr_type')],
            },
        ),
    ]
