# Generated by Django 5.2.11 on 2026-03-23 19:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_sp01_contact_address_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='confirmation_date',
            field=models.DateField(blank=True, help_text='Date of employment confirmation after probation.', null=True, verbose_name='Confirmation Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Department name (will be FK in SubPhase-02).', max_length=100, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Job title/designation (will be FK in SubPhase-02).', max_length=100, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_interview_notes',
            field=models.TextField(blank=True, default='', help_text='Notes from exit interview.', verbose_name='Exit Interview Notes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date the employee joined the organisation.', null=True, verbose_name='Hire Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Direct manager/reporting supervisor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notice_period',
            field=models.PositiveIntegerField(blank=True, help_text='Notice period in days.', null=True, verbose_name='Notice Period (Days)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, help_text='Date probation period ends.', null=True, verbose_name='Probation End Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(blank=True, help_text='Date resignation was submitted.', null=True, verbose_name='Resignation Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for resignation.', verbose_name='Resignation Reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Date employment was terminated.', null=True, verbose_name='Termination Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for termination.', verbose_name='Termination Reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_from_home_eligible',
            field=models.BooleanField(default=False, help_text='Whether employee is eligible for work from home.', verbose_name='WFH Eligible'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, default='', help_text='Office or work location name.', max_length=200, verbose_name='Work Location'),
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('effective_date', models.DateField(db_index=True, help_text='Date when the change became effective.', verbose_name='Effective Date')),
                ('change_type', models.CharField(choices=[('promotion', 'Promotion'), ('transfer', 'Transfer'), ('demotion', 'Demotion'), ('salary_change', 'Salary Change'), ('role_change', 'Role Change')], help_text='Type of employment change.', max_length=20, verbose_name='Change Type')),
                ('from_department', models.CharField(blank=True, default='', max_length=100, verbose_name='From Department')),
                ('to_department', models.CharField(blank=True, default='', max_length=100, verbose_name='To Department')),
                ('from_designation', models.CharField(blank=True, default='', max_length=100, verbose_name='From Designation')),
                ('to_designation', models.CharField(blank=True, default='', max_length=100, verbose_name='To Designation')),
                ('previous_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Previous Salary')),
                ('new_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='New Salary')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about this change.', verbose_name='Notes')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made this change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('employee', models.ForeignKey(help_text='Employee this history entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='employees.employee', verbose_name='Employee')),
                ('from_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from_manager', to='employees.employee', verbose_name='Previous Manager')),
                ('to_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to_manager', to='employees.employee', verbose_name='New Manager')),
            ],
            options={
                'verbose_name': 'Employment History',
                'verbose_name_plural': 'Employment Histories',
                'db_table': 'employees_employment_history',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['employee', 'effective_date'], name='idx_emp_hist_date'), models.Index(fields=['change_type'], name='idx_emp_hist_type')],
            },
        ),
    ]
