# Generated by Django 5.2.11 on 2026-03-24 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_sp01_documents_bank_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefamily',
            options={'ordering': ['employee', 'relationship'], 'verbose_name': 'Family Member', 'verbose_name_plural': 'Family Members'},
        ),
        migrations.AddField(
            model_name='employee',
            name='counter_offer_accepted',
            field=models.BooleanField(default=False, help_text='Whether the counter offer was accepted.', verbose_name='Counter Offer Accepted'),
        ),
        migrations.AddField(
            model_name='employee',
            name='counter_offer_made',
            field=models.BooleanField(default=False, help_text='Whether a counter offer was made.', verbose_name='Counter Offer Made'),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_interview_date',
            field=models.DateField(blank=True, help_text='Date of exit interview.', null=True, verbose_name='Exit Interview Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='final_settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of final settlement.', max_digits=12, null=True, verbose_name='Final Settlement Amount'),
        ),
        migrations.AddField(
            model_name='employee',
            name='final_settlement_paid',
            field=models.BooleanField(default=False, help_text='Whether the final settlement has been paid.', verbose_name='Settlement Paid'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Quick filter for active/inactive employees.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_working_date',
            field=models.DateField(blank=True, help_text="Employee's last working date.", null=True, verbose_name='Last Working Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marriage_date',
            field=models.DateField(blank=True, help_text='Date of marriage.', null=True, verbose_name='Marriage Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notice_period_waived',
            field=models.BooleanField(default=False, help_text='Whether the notice period has been waived.', verbose_name='Notice Period Waived'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_extension',
            field=models.CharField(blank=True, help_text='Internal phone extension number.', max_length=10, null=True, verbose_name='Phone Extension'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_letter_received',
            field=models.BooleanField(default=False, help_text='Whether the resignation letter was received.', verbose_name='Resignation Letter Received'),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_name',
            field=models.CharField(blank=True, help_text="Name of the employee's spouse.", max_length=200, null=True, verbose_name='Spouse Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='terminated_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the termination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_employees', to=settings.AUTH_USER_MODEL, verbose_name='Terminated By'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about the termination.', verbose_name='Termination Notes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('branch', 'Branch'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('field', 'Field'), ('client_site', 'Client Site')], default='', help_text='Type of work location (office, remote, hybrid, etc.).', max_length=20, verbose_name='Work Location Type'),
        ),
        migrations.AddField(
            model_name='employeeaddress',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about this address.', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='employeebankaccount',
            name='bank_code',
            field=models.CharField(blank=True, default='', help_text='Bank code (e.g., CBSL bank code)', max_length=20),
        ),
        migrations.AddField(
            model_name='employeebankaccount',
            name='currency',
            field=models.CharField(blank=True, default='LKR', help_text='Account currency (ISO 4217 code)', max_length=3),
        ),
        migrations.AddField(
            model_name='employeebankaccount',
            name='iban',
            field=models.CharField(blank=True, default='', help_text='International Bank Account Number', max_length=34),
        ),
        migrations.AddField(
            model_name='employeebankaccount',
            name='is_international',
            field=models.BooleanField(default=False, help_text='Whether this is an international bank account'),
        ),
        migrations.AddField(
            model_name='employeebankaccount',
            name='routing_number',
            field=models.CharField(blank=True, default='', help_text='Bank routing number', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the document has been verified'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_employee_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeefamily',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about this family member.', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='change_reason',
            field=models.CharField(blank=True, choices=[('performance', 'Performance'), ('restructuring', 'Restructuring'), ('business_needs', 'Business Needs'), ('skill_development', 'Skill Development'), ('employee_request', 'Employee Request'), ('retention', 'Retention'), ('cost_optimization', 'Cost Optimization'), ('market_adjustment', 'Market Adjustment'), ('annual_review', 'Annual Review'), ('other', 'Other')], default='', help_text='Reason for this change.', max_length=30, verbose_name='Change Reason'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='change_reason_detail',
            field=models.TextField(blank=True, default='', help_text='Detailed explanation for this change.', verbose_name='Change Reason Detail'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('relative', 'Relative'), ('other', 'Other')], help_text='Relationship to the employee.', max_length=20, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('probation', 'Probation'), ('temporary', 'Temporary'), ('consultant', 'Consultant')], db_index=True, default='full_time', help_text='Type of employment (full-time, part-time, contract, etc.).', max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('performance', 'Performance'), ('misconduct', 'Misconduct'), ('redundancy', 'Redundancy'), ('mutual', 'Mutual Agreement'), ('contract_end', 'Contract End'), ('resignation', 'Resignation'), ('other', 'Other')], default='', help_text='Reason for termination.', max_length=30, verbose_name='Termination Reason'),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='relationship',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('relative', 'Relative'), ('other', 'Other')], help_text='Relationship to the employee.', max_length=20, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='change_type',
            field=models.CharField(choices=[('promotion', 'Promotion'), ('transfer', 'Transfer'), ('demotion', 'Demotion'), ('salary_change', 'Salary Change'), ('role_change', 'Role Change'), ('hire', 'Hire'), ('manager_change', 'Manager Change'), ('probation_confirmation', 'Probation Confirmation'), ('resignation', 'Resignation'), ('termination', 'Termination')], help_text='Type of employment change.', max_length=30, verbose_name='Change Type'),
        ),
        migrations.AlterUniqueTogether(
            name='employmenthistory',
            unique_together={('employee', 'effective_date', 'change_type')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['date_of_birth'], name='idx_emp_dob'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='idx_emp_hire_date'),
        ),
        migrations.AddIndex(
            model_name='employeefamily',
            index=models.Index(fields=['employee', 'is_dependent'], name='idx_emp_family_dependent'),
        ),
    ]
