# Generated by Django 5.2.11 on 2026-03-24 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_sp01_audit_fixes'),
        ('organization', '0002_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, help_text="Employee's job designation/position.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.designation', verbose_name='Designation'),
        ),
    ]
