# Generated by Django 5.2.11 on 2026-03-20 03:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0008_sp08_group_f'),
        ('tenants', '0010_add_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('default_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Default credit limit for new accounts (LKR).', max_digits=12)),
                ('default_payment_terms_days', models.PositiveIntegerField(default=30, help_text='Default payment terms in days (Net 30).')),
                ('default_grace_period_days', models.PositiveIntegerField(default=5, help_text='Default grace period in days.')),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Default annual interest rate (%).', max_digits=5)),
                ('min_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Minimum credit limit allowed (LKR).', max_digits=12)),
                ('max_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('5000000.00'), help_text='Maximum credit limit allowed (LKR).', max_digits=12)),
                ('auto_approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Credit limits below this are auto-approved (LKR).', max_digits=12)),
                ('requires_manager_approval_above', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Requires manager approval above this amount (LKR).', max_digits=12)),
                ('auto_suspend_after_late_payments', models.PositiveIntegerField(default=3, help_text='Auto-suspend after X late payments.')),
                ('auto_suspend_risk_score', models.PositiveIntegerField(default=80, help_text='Auto-suspend if risk score exceeds this.')),
                ('days_before_overdue_notification', models.PositiveIntegerField(default=3, help_text='Send notification X days before due date.')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Credit Settings',
                'verbose_name_plural': 'Credit Settings',
                'db_table': 'credit_settings',
            },
        ),
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('pending_approval', 'Pending Approval')], db_index=True, default='pending_approval', help_text='Current credit account status.', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum credit allowed (LKR).', max_digits=12)),
                ('available_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Currently available credit (LKR).', max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current amount owed (LKR).', max_digits=12)),
                ('payment_terms_days', models.PositiveIntegerField(default=30, help_text='Payment due in X days (e.g., Net 30).')),
                ('grace_period_days', models.PositiveIntegerField(default=5, help_text='Grace period before late fees apply.')),
                ('interest_rate_annual', models.DecimalField(blank=True, decimal_places=2, default=Decimal('18.00'), help_text='Annual interest rate for overdue amounts (%).', max_digits=5, null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the credit account was approved.', null=True)),
                ('suspended_at', models.DateTimeField(blank=True, help_text='When the credit account was suspended.', null=True)),
                ('suspended_reason', models.TextField(blank=True, default='', help_text='Reason for credit suspension.')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about this credit account.')),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of last payment received.', null=True)),
                ('last_purchase_date', models.DateField(blank=True, help_text='Date of last credit purchase.', null=True)),
                ('next_payment_due', models.DateField(blank=True, help_text='Next payment due date.', null=True)),
                ('account_opened_date', models.DateField(auto_now_add=True, help_text='When credit account was opened.')),
                ('risk_score', models.PositiveIntegerField(default=50, help_text='Risk score 0-100 (higher = riskier).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('late_payment_count', models.PositiveIntegerField(default=0, help_text='Number of late payments.')),
                ('default_count', models.PositiveIntegerField(default=0, help_text='Number of payment defaults (90+ days overdue).')),
                ('total_payments_made', models.PositiveIntegerField(default=0, help_text='Total number of payments received.')),
                ('on_time_payment_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage of on-time payments.', max_digits=5)),
                ('last_assessment_date', models.DateField(blank=True, help_text='When risk was last assessed.', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this credit account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_accounts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='customers.customer')),
                ('suspended_by', models.ForeignKey(blank=True, help_text='User who suspended this credit account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_credit_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Credit Account',
                'verbose_name_plural': 'Customer Credit Accounts',
                'db_table': 'credit_customer_credit',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CreditApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('requested_credit_limit', models.DecimalField(decimal_places=2, help_text='Requested credit limit (LKR).', max_digits=12)),
                ('request_type', models.CharField(choices=[('new_account', 'New Account'), ('limit_increase', 'Limit Increase'), ('limit_decrease', 'Limit Decrease'), ('reactivation', 'Reactivation')], default='new_account', help_text='Type of credit request.', max_length=20)),
                ('request_reason', models.TextField(blank=True, default='', help_text='Reason for credit request.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='', help_text="Manager's notes on approval decision.")),
                ('previous_credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Previous credit limit (for limit changes).', max_digits=12, null=True)),
                ('supporting_documents', models.JSONField(blank=True, default=list, help_text='List of supporting document references.')),
                ('is_auto_approved', models.BooleanField(default=False, help_text='Whether this was auto-approved.')),
                ('auto_approval_reason', models.CharField(blank=True, default='', help_text='Reason for auto-approval.', max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Request priority.', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_approvals', to='customers.customer')),
                ('requested_by', models.ForeignKey(help_text='User who submitted the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_credit_approvals', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='credit.customercredit')),
            ],
            options={
                'verbose_name': 'Credit Approval Request',
                'verbose_name_plural': 'Credit Approval Requests',
                'db_table': 'credit_approval_workflow',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['status'], name='credit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['next_payment_due'], name='credit_next_due_idx'),
        ),
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['risk_score'], name='credit_risk_score_idx'),
        ),
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['status', 'outstanding_balance'], name='credit_status_balance_idx'),
        ),
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['status', 'next_payment_due'], name='credit_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='creditapprovalworkflow',
            index=models.Index(fields=['status', '-requested_at'], name='credit_approval_status_idx'),
        ),
        migrations.AddIndex(
            model_name='creditapprovalworkflow',
            index=models.Index(fields=['customer', 'status'], name='credit_approval_cust_idx'),
        ),
    ]
