# Generated by Django 5.2.11 on 2026-03-20 03:37

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_sp09_group_a_credit_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('transaction_number', models.CharField(help_text='Unique transaction number (CT-YYYY-NNNNN).', max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('credit_purchase', 'Credit Purchase'), ('payment', 'Payment'), ('adjustment', 'Adjustment'), ('interest', 'Interest'), ('write_off', 'Write Off')], help_text='Type of credit transaction.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (LKR).', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Credit balance after transaction (LKR).', max_digits=12)),
                ('reference_type', models.CharField(blank=True, default='', help_text='Type of reference document (Order, Invoice, etc.).', max_length=50)),
                ('reference_id', models.UUIDField(blank=True, help_text='ID of reference document.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about transaction.')),
                ('payment_method', models.CharField(blank=True, default='', help_text='Payment method (for payment transactions).', max_length=50)),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Payment reference (cheque number, transaction ID).', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', help_text='Transaction status.', max_length=20)),
                ('is_reversed', models.BooleanField(default=False, help_text='Whether this transaction has been reversed.')),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_days', models.PositiveIntegerField(blank=True, null=True)),
                ('interest_rate_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When transaction occurred.')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date (for credit purchases).', null=True)),
                ('paid_date', models.DateField(blank=True, help_text='When payment was made.', null=True)),
                ('effective_date', models.DateField(default=datetime.date.today, help_text='Date when transaction takes effect.')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credit.customercredit')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'db_table': 'credit_transaction',
                'ordering': ['-transaction_date', '-created_on'],
                'indexes': [models.Index(fields=['transaction_date'], name='credit_txn_date_idx'), models.Index(fields=['due_date'], name='credit_txn_due_idx'), models.Index(fields=['credit_account', 'transaction_date'], name='credit_txn_acct_date_idx'), models.Index(fields=['transaction_type'], name='credit_txn_type_idx')],
            },
        ),
    ]
