# Generated by Django 5.2.11 on 2026-03-20 03:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_sp09_group_b_transactions'),
        ('customers', '0008_sp08_group_f'),
        ('tenants', '0010_add_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1, help_text='Points awarded per Rs. 100 spent.', max_digits=5)),
                ('min_purchase_for_points', models.DecimalField(decimal_places=2, default=0, help_text='Minimum purchase amount to earn points.', max_digits=10)),
                ('points_expiry_months', models.PositiveIntegerField(blank=True, help_text='Months until earned points expire. Null = never expire.', null=True)),
                ('min_points_for_redemption', models.PositiveIntegerField(default=100, help_text='Minimum points required for redemption.')),
                ('redemption_value_per_point', models.DecimalField(decimal_places=2, default=1, help_text='Discount value per point redeemed (Rs.).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'credit_loyalty_program',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=0, help_text='Numeric level for ordering (higher = better tier).')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1, help_text='Points earning multiplier for this tier.', max_digits=4)),
                ('min_points_required', models.IntegerField(default=0, help_text='Minimum lifetime points to qualify for this tier.')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the entry-level tier.')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='credit.loyaltyprogram')),
            ],
            options={
                'db_table': 'credit_loyalty_tier',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('enrolled_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('pending_approval', 'Pending Approval')], default='active', max_length=20)),
                ('points_balance', models.IntegerField(default=0)),
                ('lifetime_points_earned', models.IntegerField(default=0)),
                ('total_points_redeemed', models.IntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('tier_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('tier_expiry_date', models.DateField(blank=True, null=True)),
                ('tier_upgraded_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='customers.customer')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_accounts', to='credit.loyaltyprogram')),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_members', to='credit.loyaltytier')),
            ],
            options={
                'verbose_name_plural': 'Customer loyalty accounts',
                'db_table': 'credit_customer_loyalty',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('expire', 'Expire'), ('bonus', 'Bonus'), ('adjustment', 'Adjustment')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for earn/bonus, negative for redeem/expire.')),
                ('balance_after', models.IntegerField(help_text='Points balance snapshot after this transaction.')),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date when earned points expire.', null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('adjustment_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_adjustments', to=settings.AUTH_USER_MODEL)),
                ('customer_loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='credit.customerloyalty')),
            ],
            options={
                'db_table': 'credit_points_transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='loyaltyprogram',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_program_tenant_active'),
        ),
        migrations.AddIndex(
            model_name='loyaltytier',
            index=models.Index(fields=['program', 'level'], name='idx_tier_program_level'),
        ),
        migrations.AddIndex(
            model_name='customerloyalty',
            index=models.Index(fields=['status'], name='idx_loyalty_status'),
        ),
        migrations.AddIndex(
            model_name='customerloyalty',
            index=models.Index(fields=['points_balance'], name='idx_loyalty_points'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['customer_loyalty', '-transaction_date'], name='idx_pts_txn_loyalty_date'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['reference_id'], name='idx_pts_txn_reference'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['transaction_type', 'is_expired'], name='idx_pts_txn_type_expired'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['expiry_date'], name='idx_pts_txn_expiry'),
        ),
    ]
