# Generated by Django 5.2.11 on 2026-03-20 03:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_sp09_group_c_loyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloyalty',
            name='anniversary_rewards_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='last_anniversary_reward_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='last_birthday_reward_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='loyalty/tier_badges/'),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tier discount percentage on purchases.', max_digits=5),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='early_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='min_spend_required',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum lifetime spend (Rs.) to qualify for this tier.', max_digits=12),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loyaltytier',
            name='min_points_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum lifetime points to qualify for this tier.'),
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('reward_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('bonus_points', 'Bonus Points'), ('free_product', 'Free Product'), ('discount_voucher', 'Discount Voucher'), ('free_shipping', 'Free Shipping'), ('tier_upgrade', 'Tier Upgrade'), ('referral', 'Referral')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='credit.loyaltyprogram')),
            ],
            options={
                'db_table': 'credit_loyalty_rewards',
                'unique_together': {('program', 'reward_type')},
            },
        ),
    ]
