# Generated by Django 5.2.11 on 2026-03-20 04:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_sp09_group_d_tiers_rewards'),
        ('customers', '0008_sp08_group_f'),
        ('products', '0014_sp07_error_message_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current available store credit balance.', max_digits=10)),
                ('total_issued', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime accumulated credits issued.', max_digits=10)),
                ('total_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime accumulated credits used.', max_digits=10)),
                ('currency', models.CharField(default='LKR', help_text='Currency code for credits.', max_length=3)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original amount when first issued.', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this credit account.')),
                ('created_from', models.CharField(choices=[('refund', 'Refund'), ('gift', 'Gift Credit'), ('promotional', 'Promotional Credit'), ('adjustment', 'Manual Adjustment'), ('compensation', 'Compensation'), ('loyalty_conversion', 'Loyalty Points Conversion')], default='adjustment', help_text='Source of the credit.', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Reference to source (order ID, invoice, etc.).', max_length=100)),
                ('last_transaction_at', models.DateTimeField(blank=True, help_text='Last credit transaction timestamp.', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date when credit expires (null = never expires).', null=True)),
                ('grace_period_days', models.IntegerField(default=0, help_text='Days of grace period after expiry date.')),
                ('expiry_reminder_sent', models.BooleanField(default=False, help_text='Whether expiry reminder has been sent.')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_credit', to='customers.customer')),
                ('issued_by', models.ForeignKey(blank=True, help_text='User who issued this credit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Credit',
                'verbose_name_plural': 'Store Credits',
                'db_table': 'credit_store_credits',
                'ordering': ['-balance', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='StoreCreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('transaction_type', models.CharField(choices=[('issue', 'Issue Credit'), ('redeem', 'Redeem Credit'), ('expire', 'Expire Credit'), ('adjust', 'Manual Adjustment'), ('refund', 'Refund to Original Payment')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for issuance, negative for redemption.', max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Order ID, invoice reference, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('store_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credit.storecredit')),
            ],
            options={
                'verbose_name': 'Store Credit Transaction',
                'verbose_name_plural': 'Store Credit Transactions',
                'db_table': 'credit_store_credit_transactions',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PointsPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('multiplier', 'Point Multiplier'), ('flat_bonus', 'Flat Bonus Points'), ('category_bonus', 'Category Bonus'), ('spend_threshold', 'Spend Threshold'), ('first_purchase', 'First Purchase'), ('birthday_month', 'Birthday Month')], db_index=True, max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Point multiplier (e.g. 2.0 for double points).', max_digits=5)),
                ('bonus_points', models.IntegerField(default=0, help_text='Flat bonus points to award.')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum purchase amount to qualify.', max_digits=10)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Flexible JSON configuration for promotion rules.')),
                ('valid_from', models.DateTimeField(help_text='Promotion start date/time.')),
                ('valid_to', models.DateTimeField(help_text='Promotion end date/time.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Categories this promotion applies to.', related_name='points_promotions', to='products.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Products this promotion applies to.', related_name='points_promotions', to='products.product')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='credit.loyaltyprogram')),
                ('tier_required', models.ForeignKey(blank=True, help_text='Tier required to participate (null = all tiers).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_promotions', to='credit.loyaltytier')),
            ],
            options={
                'verbose_name': 'Points Promotion',
                'verbose_name_plural': 'Points Promotions',
                'db_table': 'credit_points_promotions',
                'ordering': ['-valid_from', 'name'],
                'indexes': [models.Index(fields=['program', 'is_active'], name='credit_poin_program_9cd46a_idx'), models.Index(fields=['valid_from', 'valid_to'], name='credit_poin_valid_f_cfb88e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['created_from'], name='credit_stor_created_319bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['expiry_date'], name='credit_stor_expiry__fe9be4_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredittransaction',
            index=models.Index(fields=['store_credit', '-created_on'], name='credit_stor_store_c_a9fa62_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredittransaction',
            index=models.Index(fields=['reference'], name='credit_stor_referen_040a42_idx'),
        ),
    ]
