# Generated by Django 5.2.11 on 2026-03-21 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_sp09_group_e_store_credit_promos'),
        ('customers', '0008_sp08_group_f'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['outstanding_balance'], name='credit_balance_idx'),
        ),
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['status', 'risk_score'], name='credit_status_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='customercredit',
            index=models.Index(fields=['customer', 'status'], name='credit_customer_status_idx'),
        ),
    ]
