export const PORTAL_TEST_IDS = {
  sidebar: 'portal-sidebar',
  dashboard: 'portal-dashboard',
  welcomeCard: 'welcome-card',
  statsGrid: 'stats-grid',
  recentOrders: 'recent-orders',
  ordersList: 'orders-list',
  orderCard: 'order-card',
  orderTracking: 'order-tracking',
  addressGrid: 'address-grid',
  addressCard: 'address-card',
  addressForm: 'address-form',
  wishlistGrid: 'wishlist-grid',
  wishlistCard: 'wishlist-card',
  reviewList: 'review-list',
  reviewCard: 'review-card',
  profileForm: 'profile-form',
  changePasswordForm: 'change-password-form',
  notificationSettings: 'notification-settings',
  deleteAccountButton: 'delete-account-button',
} as const;
