# Generated by Django 5.2.11 on 2026-03-24 04:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_sp01_audit_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text="Department name, e.g. 'Human Resources'.", max_length=100)),
                ('code', models.CharField(help_text="Unique department code, e.g. 'DEPT-HR'.", max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', help_text='Operational status of the department.', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of department responsibilities.')),
                ('mission_statement', models.TextField(blank=True, default='', help_text='Department mission statement and objectives.')),
                ('location', models.CharField(blank=True, default='', help_text="Location or campus name, e.g. 'Colombo Head Office'.", max_length=100)),
                ('building', models.CharField(blank=True, default='', help_text='Building name or number.', max_length=50)),
                ('floor', models.CharField(blank=True, default='', help_text="Floor information, e.g. '3rd Floor'.", max_length=20)),
                ('email', models.EmailField(blank=True, default='', help_text='Department email address.', max_length=100)),
                ('phone', models.CharField(blank=True, default='', help_text='Department phone number.', max_length=20)),
                ('extension', models.CharField(blank=True, default='', help_text='Internal phone extension.', max_length=10)),
                ('cost_center', models.CharField(blank=True, default='', help_text='Cost center code for financial tracking.', max_length=20)),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Annual budget amount.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='LKR', help_text='ISO 4217 currency code for the budget.', max_length=3)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('manager', models.ForeignKey(blank=True, help_text='Employee who manages this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Parent department. Null indicates a root department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='idx_dept_code'), models.Index(fields=['status'], name='idx_dept_status'), models.Index(fields=['name'], name='idx_dept_name'), models.Index(fields=['parent'], name='idx_dept_parent'), models.Index(fields=['manager'], name='idx_dept_manager'), models.Index(fields=['cost_center'], name='idx_dept_cost_center'), models.Index(fields=['tree_id', 'lft'], name='organization_department_tr4348')],
            },
        ),
    ]
