# Generated by Django 5.2.11 on 2026-03-24 04:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('title', models.CharField(help_text="Job title, e.g. 'Software Engineer'.", max_length=100)),
                ('code', models.CharField(help_text="Unique designation code, e.g. 'SE'.", max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', help_text='Whether this designation is active.', max_length=20)),
                ('level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive')], db_index=True, default='entry', help_text='Seniority level (entry → executive).', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Position overview and summary.')),
                ('responsibilities', models.TextField(blank=True, default='', help_text='Key duties and accountabilities.')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary for this position.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary for this position.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='LKR', help_text='ISO 4217 currency code for salary.', max_length=3)),
                ('qualifications', models.TextField(blank=True, default='', help_text='Educational and professional qualifications required.')),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Minimum years of experience required.', null=True)),
                ('is_manager', models.BooleanField(default=False, help_text='Whether this designation has managerial authority.')),
                ('department', models.ForeignKey(blank=True, help_text='Department this designation belongs to (null = org-wide).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='organization.department')),
                ('reports_to', models.ForeignKey(blank=True, help_text='Superior designation this position reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='organization.designation')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['code'], name='idx_desig_code'), models.Index(fields=['status'], name='idx_desig_status'), models.Index(fields=['level'], name='idx_desig_level'), models.Index(fields=['title'], name='idx_desig_title'), models.Index(fields=['department'], name='idx_desig_dept'), models.Index(fields=['is_manager'], name='idx_desig_manager')],
            },
        ),
    ]
