# Generated by Django 5.2.11 on 2026-03-24 04:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        ('organization', '0002_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_acting', models.BooleanField(default=False, help_text='Whether this is an acting/interim head.')),
                ('start_date', models.DateField(help_text='Date the head tenure began.')),
                ('end_date', models.DateField(blank=True, help_text='Date the head tenure ended (null = currently serving).', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional appointment notes.')),
                ('appointed_by', models.ForeignKey(blank=True, help_text='User who made the appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head_appointments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department this head record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='organization.department')),
                ('employee', models.ForeignKey(help_text='Employee serving as department head.', on_delete=django.db.models.deletion.CASCADE, related_name='head_positions', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Department Head',
                'verbose_name_plural': 'Department Heads',
                'ordering': ['department', '-start_date'],
                'indexes': [models.Index(fields=['department', 'end_date'], name='idx_dhead_dept_end')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('role', models.CharField(choices=[('member', 'Member'), ('lead', 'Lead'), ('deputy_manager', 'Deputy Manager')], default='member', help_text='Role within the department (member, lead, deputy_manager).', max_length=20)),
                ('is_primary', models.BooleanField(default=True, help_text="Whether this is the employee's primary department.")),
                ('joined_date', models.DateField(help_text='Date the employee joined this department.')),
                ('left_date', models.DateField(blank=True, help_text='Date the employee left this department (null = still active).', null=True)),
                ('department', models.ForeignKey(help_text='Department the employee belongs/belonged to.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.department')),
                ('employee', models.ForeignKey(help_text='Employee who is/was a member.', on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Department Member',
                'verbose_name_plural': 'Department Members',
                'ordering': ['-joined_date'],
                'indexes': [models.Index(fields=['employee', 'department'], name='idx_dmember_emp_dept'), models.Index(fields=['department', 'left_date'], name='idx_dmember_dept_left')],
            },
        ),
    ]
