# Generated by Django 5.2.11 on 2026-03-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        ('organization', '0003_departmenthead_departmentmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmember',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional membership information.'),
        ),
        migrations.AlterField(
            model_name='departmentmember',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Whether this is the employee's primary department."),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['status', 'parent'], name='idx_dept_status_parent'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['department', 'status'], name='idx_desig_dept_status'),
        ),
        migrations.AddConstraint(
            model_name='departmentmember',
            constraint=models.UniqueConstraint(condition=models.Q(('left_date__isnull', True)), fields=('employee', 'department'), name='uq_active_member_per_dept'),
        ),
    ]
