# Generated by Django 5.2.11 on 2026-03-12 01:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_add_display_order_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(db_index=True, help_text="Name of the attribute group (e.g., 'Technical Specifications')", max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this attribute group')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which groups are displayed (lower numbers first)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Attribute Group',
                'verbose_name_plural': 'Attribute Groups',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(db_index=True, help_text='Name of the attribute (e.g., Color, Weight, Size)', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name)', max_length=100, unique=True)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('multiselect', 'Multi-Select'), ('boolean', 'Boolean'), ('date', 'Date')], db_index=True, help_text='Type of attribute (text, number, select, multiselect, boolean, date)', max_length=20)),
                ('unit', models.CharField(blank=True, default='', help_text='Unit of measure (e.g., kg, cm, GB, LKR) — for NUMBER type', max_length=20)),
                ('is_required', models.BooleanField(db_index=True, default=False, help_text='Whether this attribute must have a value when creating products')),
                ('is_filterable', models.BooleanField(db_index=True, default=False, help_text='Include in webstore faceted search filters')),
                ('is_searchable', models.BooleanField(db_index=True, default=False, help_text='Include attribute values in search indexing')),
                ('is_comparable', models.BooleanField(default=False, help_text='Show in product comparison tables')),
                ('is_visible_on_product', models.BooleanField(default=True, help_text='Display this attribute on product detail pages')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which attribute is displayed (lower numbers first)')),
                ('validation_regex', models.CharField(blank=True, default='', help_text="Regex pattern for validating TEXT attributes (e.g., '^[A-Z0-9-]+$')", max_length=255)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum allowed value for NUMBER attributes', max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum allowed value for NUMBER attributes', max_digits=20, null=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories this attribute applies to', related_name='attributes', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('group', models.ForeignKey(blank=True, help_text='Optional group for organizing attributes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='attributes.attributegroup')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('value', models.CharField(db_index=True, help_text="Internal value (e.g., 'red', 'large', 'cotton')", max_length=100)),
                ('label', models.CharField(help_text="Display label (e.g., 'Bright Red', 'Extra Large')", max_length=100)),
                ('color_code', models.CharField(blank=True, default='', help_text='Hex color code for swatches (e.g., #FF0000)', max_length=7)),
                ('image', models.ImageField(blank=True, help_text='Optional image for visual selection (e.g., fabric textures)', null=True, upload_to='attributes/options/')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which option is displayed (lower numbers first)')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Whether this is the default selected option')),
                ('attribute', models.ForeignKey(help_text='Attribute this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='attributes.attribute')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Attribute Option',
                'verbose_name_plural': 'Attribute Options',
                'ordering': ['display_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='attributegroup',
            index=models.Index(fields=['is_active', 'display_order'], name='attrs_grp_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['attribute_type'], name='attrs_attr_type_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['is_filterable'], name='attrs_attr_filterable_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['group', 'display_order'], name='attrs_attr_grp_order_idx'),
        ),
        migrations.AddIndex(
            model_name='attributeoption',
            index=models.Index(fields=['attribute', 'display_order'], name='attrs_opt_attr_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together={('attribute', 'value')},
        ),
    ]
