# Generated by Django 5.2.11 on 2026-02-21 12:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('first_name', models.CharField(blank=True, default='', help_text="Customer's first name (for individuals).", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', help_text="Customer's last name (for individuals).", max_length=100, verbose_name='Last Name')),
                ('business_name', models.CharField(blank=True, default='', help_text='Company or business name (for business/wholesale customers).', max_length=255, verbose_name='Business Name')),
                ('email', models.EmailField(blank=True, default='', help_text='Primary email address for the customer.', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', help_text='Primary phone number (+94 XX XXX XXXX format).', max_length=30, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, default='', help_text='Mobile phone number.', max_length=30, verbose_name='Mobile')),
                ('billing_address_line_1', models.CharField(blank=True, default='', help_text='Primary billing address line.', max_length=255, verbose_name='Billing Address Line 1')),
                ('billing_address_line_2', models.CharField(blank=True, default='', help_text='Secondary billing address line.', max_length=255, verbose_name='Billing Address Line 2')),
                ('billing_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Billing City')),
                ('billing_state_province', models.CharField(blank=True, default='', max_length=100, verbose_name='Billing State / Province')),
                ('billing_postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Billing Postal Code')),
                ('billing_country', models.CharField(default='Sri Lanka', max_length=100, verbose_name='Billing Country')),
                ('shipping_address_line_1', models.CharField(blank=True, default='', help_text='Primary shipping address line.', max_length=255, verbose_name='Shipping Address Line 1')),
                ('shipping_address_line_2', models.CharField(blank=True, default='', help_text='Secondary shipping address line.', max_length=255, verbose_name='Shipping Address Line 2')),
                ('shipping_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Shipping City')),
                ('shipping_state_province', models.CharField(blank=True, default='', max_length=100, verbose_name='Shipping State / Province')),
                ('shipping_postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Shipping Postal Code')),
                ('shipping_country', models.CharField(default='Sri Lanka', max_length=100, verbose_name='Shipping Country')),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business / Corporate'), ('wholesale', 'Wholesale Buyer'), ('vip', 'VIP Customer')], db_index=True, default='individual', help_text='Classification: individual, business, wholesale, or VIP.', max_length=20, verbose_name='Customer Type')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this customer is active for transactions.', verbose_name='Active')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowed in LKR (₨). 0 = no credit.', max_digits=10, verbose_name='Credit Limit (LKR)')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding balance owed by the customer in LKR (₨).', max_digits=10, verbose_name='Current Balance (LKR)')),
                ('tax_id', models.CharField(blank=True, default='', help_text='Business registration number or tax identification.', max_length=50, verbose_name='Tax ID / BRN')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about this customer.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers_customer',
                'ordering': ['first_name', 'last_name', 'business_name'],
                'indexes': [models.Index(fields=['customer_type', 'is_active'], name='idx_customer_type_active'), models.Index(fields=['email'], name='idx_customer_email'), models.Index(fields=['phone'], name='idx_customer_phone')],
            },
        ),
    ]
