# Generated by Django 5.2.11 on 2026-03-17 11:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['display_name', 'first_name', 'last_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='accepts_marketing',
            field=models.BooleanField(default=False, help_text='Whether the customer opted in for marketing.', verbose_name='Accepts Marketing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_registration',
            field=models.CharField(blank=True, default='', help_text='Business registration number.', max_length=100, verbose_name='Company Registration'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this customer record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, default='', help_text='Auto-generated unique code (e.g. CUST-00001).', max_length=50, unique=True, verbose_name='Customer Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Customer date of birth (individuals).', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customer',
            name='department_code',
            field=models.CharField(blank=True, default='', help_text='Department code (for government / corporate).', max_length=50, verbose_name='Department Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='department_name',
            field=models.CharField(blank=True, default='', help_text='Department name (for government / corporate).', max_length=200, verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Computed display name for lists and reports.', max_length=200, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_purchase_date',
            field=models.DateField(blank=True, help_text='Date of first purchase (set once, immutable).', null=True, verbose_name='First Purchase Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes (not visible to customer).', null=True, verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_contact_date',
            field=models.DateField(blank=True, help_text='Date of most recent contact with customer.', null=True, verbose_name='Last Contact Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_marketing_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Marketing Email Sent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_purchase_date',
            field=models.DateField(blank=True, help_text='Date of most recent purchase.', null=True, verbose_name='Last Purchase Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_email_count',
            field=models.IntegerField(default=0, help_text='Number of marketing emails sent to this customer.', verbose_name='Marketing Email Count'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_opt_in_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Marketing Opt-In Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_opt_out_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Marketing Opt-Out Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_follow_up_date',
            field=models.DateField(blank=True, help_text='Scheduled follow-up date for CRM.', null=True, verbose_name='Next Follow-Up Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_count',
            field=models.IntegerField(default=0, help_text='Total number of orders placed.', verbose_name='Order Count'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization_name',
            field=models.CharField(blank=True, default='', help_text='Organization name (for non-profit / government).', max_length=200, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current outstanding balance.', max_digits=15, verbose_name='Outstanding Balance (LKR)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Customer profile image (JPEG/PNG, max 2MB).', null=True, upload_to='customers/profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_number',
            field=models.CharField(blank=True, default='', help_text='Official registration number.', max_length=100, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('pos', 'POS'), ('webstore', 'Webstore'), ('import', 'Import')], default='manual', help_text='How this customer was acquired.', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('archived', 'Archived')], db_index=True, default='active', help_text='Customer account status.', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_exempt_status',
            field=models.BooleanField(default=False, help_text='Whether the customer is exempt from tax.', verbose_name='Tax Exempt'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative payment amount.', max_digits=15, verbose_name='Total Payments (LKR)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative purchase amount.', max_digits=15, verbose_name='Total Purchases (LKR)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT Registration Number.', max_length=50, null=True, verbose_name='VAT Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit allowed in LKR. NULL = no credit.', max_digits=15, null=True, verbose_name='Credit Limit (LKR)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance owed by the customer.', max_digits=15, verbose_name='Current Balance (LKR)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('wholesale', 'Wholesale Buyer'), ('vip', 'VIP Customer'), ('government', 'Government'), ('nonprofit', 'Non-Profit')], db_index=True, default='individual', help_text='Classification: individual, business, wholesale, VIP, government, non-profit.', max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email address for the customer.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, help_text='Secondary / mobile phone number.', max_length=30, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about customer (visible to all staff).', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number (+94 XX XXX XXXX format).', max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Sri Lanka Tax Identification Number (TIN).', max_length=50, null=True, verbose_name='Tax ID / TIN'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_code'], name='idx_customer_code'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name'], name='idx_customer_name'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['display_name'], name='idx_customer_display'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='idx_customer_status'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_on'], name='idx_customer_created'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_purchase_date'], name='idx_customer_last_purchase'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['outstanding_balance'], name='idx_customer_outstanding'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['source'], name='idx_customer_source'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['next_follow_up_date'], name='idx_customer_follow_up'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['total_purchases'], name='idx_customer_total_purchases'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('total_purchases__gte', 0)), name='positive_total_purchases'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('total_payments__gte', 0)), name='positive_total_payments'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0), ('credit_limit__isnull', True), _connector='OR'), name='positive_credit_limit'),
        ),
    ]
