# Generated by Django 5.2.11 on 2026-03-17 12:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_sp08_group_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('address_type', models.CharField(choices=[('billing', 'Billing Address'), ('shipping', 'Shipping Address'), ('home', 'Home Address'), ('work', 'Work Address'), ('other', 'Other')], default='billing', help_text='Purpose of this address.', max_length=20, verbose_name='Address Type')),
                ('address_line_1', models.CharField(help_text='House number, street name.', max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, default='', help_text='Additional location details.', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(help_text='City or town name.', max_length=100, verbose_name='City')),
                ('district', models.CharField(blank=True, default='', help_text='Sri Lanka District (e.g., Colombo District).', max_length=100, verbose_name='District')),
                ('province', models.CharField(blank=True, default='', help_text='Sri Lanka Province (e.g., Western Province).', max_length=100, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, default='', help_text='Sri Lanka postal codes are 5 digits.', max_length=10, verbose_name='Postal Code')),
                ('country', models.CharField(default='Sri Lanka', max_length=100, verbose_name='Country')),
                ('is_default_billing', models.BooleanField(default=False, help_text='Mark as default billing address.', verbose_name='Default Billing')),
                ('is_default_shipping', models.BooleanField(default=False, help_text='Mark as default shipping address.', verbose_name='Default Shipping')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'db_table': 'customers_customer_address',
                'ordering': ['-is_default_billing', '-is_default_shipping', '-created_on'],
                'indexes': [models.Index(fields=['customer', 'address_type'], name='idx_addr_customer_type'), models.Index(fields=['district'], name='idx_addr_district'), models.Index(fields=['province'], name='idx_addr_province')],
            },
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('phone_type', models.CharField(choices=[('mobile', 'Mobile'), ('landline', 'Landline'), ('whatsapp', 'WhatsApp'), ('work', 'Work'), ('other', 'Other')], default='mobile', help_text='Type of phone number.', max_length=20, verbose_name='Phone Type')),
                ('phone_number', models.CharField(help_text='Format: +94 77 123 4567', max_length=20, verbose_name='Phone Number')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary phone number.', verbose_name='Primary')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this phone number has been verified.', verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp of phone verification.', null=True, verbose_name='Verified At')),
                ('is_whatsapp', models.BooleanField(default=False, help_text='Whether this number has WhatsApp.', verbose_name='WhatsApp')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Phone',
                'verbose_name_plural': 'Customer Phones',
                'db_table': 'customers_customer_phone',
                'ordering': ['-is_primary', '-created_on'],
                'indexes': [models.Index(fields=['customer', 'phone_type'], name='idx_phone_customer_type'), models.Index(fields=['phone_number'], name='idx_phone_number')],
            },
        ),
    ]
