# Generated by Django 5.2.11 on 2026-03-17 12:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_sp08_group_b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('field_name', models.CharField(help_text='Name of the field that was changed.', max_length=100, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='New Value')),
                ('change_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('status_change', 'Status Change'), ('merge', 'Merged')], default='update', max_length=20, verbose_name='Change Type')),
            ],
            options={
                'verbose_name': 'Customer History',
                'verbose_name_plural': 'Customer History',
                'db_table': 'customers_customer_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('customer_code_prefix', models.CharField(default='CUST', help_text='Prefix for auto-generated customer codes (e.g. CUST).', max_length=10, verbose_name='Customer Code Prefix')),
                ('customer_code_start', models.IntegerField(default=1, help_text='Starting sequence number for new customer codes.', verbose_name='Customer Code Start')),
                ('require_email', models.BooleanField(default=False, help_text='Require email address when creating a customer.', verbose_name='Require Email')),
                ('require_phone', models.BooleanField(default=False, help_text='Require phone number when creating a customer.', verbose_name='Require Phone')),
                ('default_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('archived', 'Archived')], default='active', help_text='Default status for newly created customers.', max_length=20, verbose_name='Default Status')),
                ('allow_duplicate_email', models.BooleanField(default=False, help_text='Allow multiple customers with the same email.', verbose_name='Allow Duplicate Email')),
                ('allow_duplicate_phone', models.BooleanField(default=True, help_text='Allow multiple customers with the same phone number.', verbose_name='Allow Duplicate Phone')),
            ],
            options={
                'verbose_name': 'Customer Settings',
                'verbose_name_plural': 'Customer Settings',
                'db_table': 'customers_customer_settings',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, help_text='Auto-populated search vector for PostgreSQL FTS.', null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_customer_search_vector'),
        ),
        migrations.AddField(
            model_name='customerhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='customerhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddIndex(
            model_name='customerhistory',
            index=models.Index(fields=['customer', '-changed_at'], name='idx_history_customer_date'),
        ),
        migrations.AddIndex(
            model_name='customerhistory',
            index=models.Index(fields=['change_type'], name='idx_history_change_type'),
        ),
        migrations.AddIndex(
            model_name='customerhistory',
            index=models.Index(fields=['changed_by'], name='idx_history_changed_by'),
        ),
    ]
