# Generated by Django 5.2.11 on 2026-03-17 14:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_sp08_group_c_search_trigger'),
        ('invoices', '0007_sp06_audit_group_c'),
        ('orders', '0010_sp05_group_e_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('phone_call', 'Phone Call'), ('sms', 'SMS'), ('visit', 'Visit'), ('note', 'Note'), ('other', 'Other')], default='note', help_text='Type of communication.', max_length=20, verbose_name='Type')),
                ('subject', models.CharField(blank=True, default='', help_text='Brief subject line for the communication.', max_length=200, verbose_name='Subject')),
                ('content', models.TextField(blank=True, default='', help_text='Full communication content or notes.', verbose_name='Content')),
                ('communication_date', models.DateTimeField(auto_now_add=True, verbose_name='Communication Date')),
                ('follow_up_date', models.DateField(blank=True, help_text='Scheduled follow-up date.', null=True, verbose_name='Follow-Up Date')),
                ('follow_up_completed', models.BooleanField(default=False, verbose_name='Follow-Up Completed')),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_communications', to=settings.AUTH_USER_MODEL, verbose_name='Contacted By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='customers.customer', verbose_name='Customer')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_communications', to='invoices.invoice', verbose_name='Related Invoice')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_communications', to='orders.order', verbose_name='Related Order')),
            ],
            options={
                'verbose_name': 'Customer Communication',
                'verbose_name_plural': 'Customer Communications',
                'db_table': 'customers_customer_communication',
                'ordering': ['-communication_date'],
                'indexes': [models.Index(fields=['customer', '-communication_date'], name='idx_comm_customer_date'), models.Index(fields=['communication_type'], name='idx_comm_type'), models.Index(fields=['follow_up_date'], name='idx_comm_follow_up')],
            },
        ),
    ]
