# Generated by Django 5.2.11 on 2026-03-17 14:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_sp08_group_d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(help_text='Unique tag name within this tenant.', max_length=100, verbose_name='Tag Name')),
                ('color', models.CharField(default='#808080', help_text='Hex colour code for visual display (#RRGGBB).', max_length=7, verbose_name='Colour')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_tags', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Customer Tag',
                'verbose_name_plural': 'Customer Tags',
                'db_table': 'customers_customer_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTagAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tag_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='customers.customer', verbose_name='Customer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='customers.customertag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag Assignment',
                'verbose_name_plural': 'Tag Assignments',
                'db_table': 'customers_customer_tag_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMerge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_at', models.DateTimeField(auto_now_add=True, verbose_name='Merged At')),
                ('merge_reason', models.TextField(blank=True, default='', verbose_name='Merge Reason')),
                ('duplicate_score', models.IntegerField(default=0, help_text='Confidence score (0-100) from duplicate detection.', verbose_name='Duplicate Score')),
                ('orders_transferred', models.IntegerField(default=0)),
                ('invoices_transferred', models.IntegerField(default=0)),
                ('payments_transferred', models.IntegerField(default=0)),
                ('addresses_transferred', models.IntegerField(default=0)),
                ('phones_transferred', models.IntegerField(default=0)),
                ('total_purchases_added', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('duplicate_customer_snapshot', models.JSONField(blank=True, default=dict, help_text='Full data snapshot of the duplicate before merge.', verbose_name='Duplicate Snapshot')),
                ('duplicate_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_as_duplicate', to='customers.customer', verbose_name='Duplicate Customer (merged)')),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_merges', to=settings.AUTH_USER_MODEL, verbose_name='Merged By')),
                ('primary_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_as_primary', to='customers.customer', verbose_name='Primary Customer (kept)')),
            ],
            options={
                'verbose_name': 'Customer Merge',
                'verbose_name_plural': 'Customer Merges',
                'db_table': 'customers_customer_merge',
                'ordering': ['-merged_at'],
                'indexes': [models.Index(fields=['primary_customer'], name='idx_merge_primary'), models.Index(fields=['duplicate_customer'], name='idx_merge_duplicate'), models.Index(fields=['-merged_at'], name='idx_merge_date')],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(max_length=200, verbose_name='Segment Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('rules', models.JSONField(blank=True, default=dict, help_text='JSON conditions and logic for segment membership.', verbose_name='Segment Rules')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('auto_assign', models.BooleanField(default=False, help_text='Automatically assign matching customers.', verbose_name='Auto-Assign')),
                ('customer_count', models.IntegerField(default=0, help_text='Cached count of matching customers.', verbose_name='Customer Count')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_segments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Customer Segment',
                'verbose_name_plural': 'Customer Segments',
                'db_table': 'customers_customer_segment',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_segment_active')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_customer_segment_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='customertag',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_customer_tag_name'),
        ),
        migrations.AddIndex(
            model_name='customertagassignment',
            index=models.Index(fields=['customer'], name='idx_tagassign_customer'),
        ),
        migrations.AddIndex(
            model_name='customertagassignment',
            index=models.Index(fields=['tag'], name='idx_tagassign_tag'),
        ),
        migrations.AddConstraint(
            model_name='customertagassignment',
            constraint=models.UniqueConstraint(fields=('customer', 'tag'), name='unique_customer_tag_assignment'),
        ),
    ]
