# Generated by Django 5.2.11 on 2026-03-17 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_sp08_group_e'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30, verbose_name='Status')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Total Rows')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='Processed Rows')),
                ('successful_rows', models.IntegerField(default=0, verbose_name='Successful Rows')),
                ('failed_rows', models.IntegerField(default=0, verbose_name='Failed Rows')),
                ('skipped_rows', models.IntegerField(default=0, verbose_name='Skipped Rows')),
                ('error_log', models.JSONField(blank=True, default=list, verbose_name='Error Log')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_imports', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Customer Import',
                'verbose_name_plural': 'Customer Imports',
                'db_table': 'customers_customer_import',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='idx_import_status'), models.Index(fields=['-started_at'], name='idx_import_started')],
            },
        ),
    ]
