# Generated by Django 5.2.11 on 2026-02-17 01:36

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text="Human-readable business name (e.g. 'Acme Trading Pvt Ltd').", max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe tenant identifier used in subdomains and schema naming. Lowercase letters, digits, and hyphens only. Example: 'acme-trading' -> schema 'tenant_acme_trading', subdomain 'acme-trading.lankacommerce.lk'.", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must contain only lowercase letters, digits, and hyphens. Must start with a letter or digit. No consecutive hyphens.', regex='^[a-z0-9](?:[a-z0-9]|-(?=[a-z0-9]))*$')])),
                ('paid_until', models.DateField(blank=True, help_text='Subscription expiry date. Null for the public tenant or tenants with unlimited access. After this date, the tenant may be suspended or moved to a limited plan.', null=True)),
                ('on_trial', models.BooleanField(default=True, help_text='Whether this tenant is currently on a trial period. Trial tenants may have feature restrictions.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', help_text="Tenant lifecycle state. 'active': fully operational. 'suspended': temporarily disabled (e.g. payment overdue). 'archived': permanently deactivated, data retained for compliance.", max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Per-tenant configuration stored as JSON. Expected keys: currency, timezone, date_format, language. Defaults are applied at the application layer if keys are missing.')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this tenant was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='When this tenant was last updated.')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['domain'],
            },
        ),
    ]
