# Generated by Django 5.2.11 on 2026-02-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the tenant has completed the onboarding workflow. Set to True when all onboarding steps have been finished. Tenants that have not completed onboarding may see a setup wizard.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current onboarding step the tenant has reached. 0 = not started. Each step represents a setup milestone (e.g. 1=profile, 2=products, 3=payment, 4=launch). Used by the frontend to resume onboarding where the tenant left off.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='schema_version',
            field=models.CharField(default='1.0.0', help_text="Tracks the current schema migration version for this tenant. Used to determine whether the tenant's schema needs migration updates. Follows semantic versioning (e.g. '1.0.0', '1.1.0').", max_length=50),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status', 'created_on'], name='idx_tenant_status_created'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['onboarding_completed'], name='idx_tenant_onboarding'),
        ),
    ]
