# Generated by Django 5.2.11 on 2026-02-19 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_onboarding_schema_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_registration_number',
            field=models.CharField(blank=True, default='', help_text='Sri Lanka Business Registration Number. Formats: PV 12345 (Private), PB 12345 (Public), GA 12345 (Guarantee), or numeric (e.g. 123456). Used for invoicing and regulatory compliance.', max_length=20, validators=[django.core.validators.RegexValidator(message='Business registration number must be in a valid Sri Lanka format: PV/PB/GA followed by 4-6 digits, or a numeric registration number.', regex='^(PV|PB|GA)\\s?\\d{4,6}$|^\\d{4,9}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(blank=True, choices=[('sole_proprietor', 'Sole Proprietor'), ('partnership', 'Partnership'), ('pvt_ltd', 'Private Limited Company'), ('plc', 'Public Limited Company'), ('cooperative', 'Cooperative Society'), ('ngo', 'Non-Governmental Organization'), ('other', 'Other')], default='other', help_text='Legal structure of the business. Used during onboarding and for compliance reporting. Sri Lanka business types: Sole Proprietor, Partnership, Pvt Ltd, PLC, Cooperative, NGO.', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Primary contact email address for the tenant. Used for billing notifications, system alerts, and support.', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='Full name of the primary contact person for this tenant. Used for account communications and support.', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='Primary contact phone number in Sri Lanka format: +94 XX XXX XXXX or 0XX XXX XXXX. Used for urgent notifications and account verification.', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in Sri Lanka format: +94 XX XXX XXXX or 0XX XXX XXXX.', regex='^(\\+94|0)\\d[\\s-]?\\d{3}[\\s-]?\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='industry',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('manufacturing', 'Manufacturing'), ('services', 'Professional Services'), ('food_beverage', 'Food & Beverage'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('technology', 'Technology'), ('agriculture', 'Agriculture'), ('construction', 'Construction'), ('hospitality', 'Hospitality & Tourism'), ('automotive', 'Automotive'), ('other', 'Other')], default='other', help_text='Industry classification for the tenant. Used for analytics, reporting, and industry-specific feature recommendations. Standardized categories covering major Sri Lankan industries.', max_length=30),
        ),
    ]
