# Generated by Django 5.2.11 on 2026-02-19 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_business_info_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address_line_1',
            field=models.CharField(blank=True, default='', help_text='Primary address line (street name, building number). Used for billing documents, invoices, and legal correspondence.', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_line_2',
            field=models.CharField(blank=True, default='', help_text='Secondary address line (suite, floor, area). Optional additional address detail.', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City or town name. Used for regional reporting and delivery logistics.', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='district',
            field=models.CharField(blank=True, default='', help_text='Administrative district (e.g. Colombo, Gampaha, Kandy). Sri Lanka has 25 districts. Used for regional reporting.', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='Sri Lanka postal code (5 digits, e.g. 10100 for Colombo Fort). Used for delivery routing and regional classification.', max_length=10, validators=[django.core.validators.RegexValidator(message='Postal code must be a 5-digit Sri Lanka postal code (e.g. 10100).', regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='province',
            field=models.CharField(blank=True, choices=[('western', 'Western Province'), ('central', 'Central Province'), ('southern', 'Southern Province'), ('northern', 'Northern Province'), ('eastern', 'Eastern Province'), ('north_western', 'North Western Province'), ('north_central', 'North Central Province'), ('uva', 'Uva Province'), ('sabaragamuwa', 'Sabaragamuwa Province')], default='', help_text='Sri Lanka province. One of the 9 provinces: Western, Central, Southern, Northern, Eastern, North Western, North Central, Uva, Sabaragamuwa.', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='Primary contact phone number in Sri Lanka format: +94 XX XXX XXXX or 0XX XXX XXXX. Used for urgent notifications and account verification.', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in Sri Lanka format: +94 XX XXX XXXX or 0XX XXX XXXX.', regex='^(\\+94|0)[\\s-]?\\d{2}[\\s-]?\\d{3}[\\s-]?\\d{4}$')]),
        ),
    ]
