# Generated by Django 5.2.11 on 2026-02-19 15:39

import apps.tenants.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('si', 'Sinhala (සිංහල)'), ('ta', 'Tamil (தமிழ்)')], default='en', help_text='Default UI language for this tenant. Supported: English (en), Sinhala (si), Tamil (ta).', max_length=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Tenant logo image. Stored at tenants/<schema_name>/branding/. Used in tenant dashboard, invoices, and webstore header. Recommended size: 200x200px, max 2MB.', null=True, upload_to=apps.tenants.models.tenant_logo_upload_path),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(blank=True, default='#1a73e8', help_text='Primary brand color in hex format (e.g. #1a73e8). Applied to tenant dashboard theme and webstore accents.', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g. #FF5733 or #F53).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Secondary brand color in hex format (e.g. #ffffff). Applied to backgrounds and secondary UI elements.', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g. #FF5733 or #F53).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(choices=[('Asia/Colombo', 'Asia/Colombo (IST +05:30)')], default='Asia/Colombo', help_text='Tenant timezone for date/time display and reporting. Default: Asia/Colombo (IST +05:30).', max_length=50),
        ),
    ]
