# Generated by Django 5.2.11 on 2026-02-19 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_branding_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this domain record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_type',
            field=models.CharField(choices=[('platform', 'Platform Domain'), ('custom', 'Custom Domain')], default='platform', help_text="Type of domain. 'platform' domains are system-assigned subdomains (e.g. acme.lankacommerce.lk). 'custom' domains are user-provided and require DNS verification.", max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this domain has been verified via DNS. Platform domains are auto-verified. Custom domains require TXT record verification.'),
        ),
        migrations.AddField(
            model_name='domain',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional domain metadata (DNS records, verification tokens, CDN configuration, etc.). Structured as a JSON object.'),
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl_expires_at',
            field=models.DateTimeField(blank=True, help_text='SSL certificate expiry date. Used for monitoring and automated renewal. Null when no certificate is provisioned.', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl_status',
            field=models.CharField(choices=[('none', 'No SSL'), ('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('failed', 'Failed')], default='none', help_text="Current SSL certificate status. 'none': no SSL configured. 'pending': provisioning in progress. 'active': valid certificate. 'expired': certificate expired. 'failed': provisioning failed.", max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='When this domain record was last updated.'),
        ),
        migrations.AddField(
            model_name='domain',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the domain was last successfully verified.', null=True),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['domain_type', 'is_verified'], name='idx_domain_type_verified'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['ssl_status'], name='idx_domain_ssl_status'),
        ),
    ]
