# Generated by Django 5.2.11 on 2026-02-19 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_domain_type_ssl_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(default='#1E40AF', help_text="Primary brand color for the tenant's UI theme. Must be a valid hex color code (e.g. #1E40AF). Applied to headers, buttons, and accent elements.", max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g. #FF5733 or #F53).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers. Combined with a sequential number to generate invoice IDs (e.g. INV-0001, INV-0002).', max_length=10)),
                ('order_prefix', models.CharField(default='ORD', help_text='Prefix for order numbers. Combined with a sequential number to generate order IDs (e.g. ORD-0001, ORD-0002).', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default tax rate as a percentage (e.g. 8.00 for 8%). Applied to new products and invoices when no specific tax rate is configured. Sri Lanka standard VAT is typically set per business requirements.', max_digits=5)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this settings record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='When this settings record was last updated.')),
                ('tenant', models.OneToOneField(help_text='The tenant this settings record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
            },
        ),
    ]
