# Generated by Django 5.2.11 on 2026-02-19 16:04

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_add_tenant_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='feature_settings',
            field=models.JSONField(blank=True, default=apps.tenants.models.default_feature_settings, help_text='Feature toggle flags for the tenant. Controls which modules and capabilities are enabled. Expected keys: webstore_enabled (bool), pos_enabled (bool), multi_location (bool), advanced_reports (bool).'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='integration_settings',
            field=models.JSONField(blank=True, default=apps.tenants.models.default_integration_settings, help_text='Integration configuration for the tenant. Stores third-party service settings. Expected keys: payment_gateway (str|null), accounting_software (str|null), shipping_provider (str|null).'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='invoice_footer',
            field=models.TextField(blank=True, default='', help_text='Footer text printed on invoices. Supports plain text. Commonly used for payment terms, bank details, or legal disclaimers. Leave blank for no footer.'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='notification_settings',
            field=models.JSONField(blank=True, default=apps.tenants.models.default_notification_settings, help_text='Notification preferences for the tenant. Controls email, SMS, and alert notifications. Expected keys: email_on_order (bool), email_on_payment (bool), sms_enabled (bool), low_stock_alert (bool).'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='receipt_footer',
            field=models.TextField(blank=True, default='Thank you for your purchase!', help_text='Footer text printed on receipts. Supports plain text. Commonly used for thank-you messages, return policies, or promotional messages.'),
        ),
    ]
