# Generated by Django 5.2.11 on 2026-02-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial_platform_models'),
        ('tenants', '0008_add_settings_text_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], db_index=True, default='trial', help_text="Current subscription lifecycle state. 'trial': free trial period. 'active': paid and current. 'expired': billing period ended. 'cancelled': user cancelled. 'suspended': admin suspended.", max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', help_text="Billing frequency. 'monthly': billed every month. 'annual': billed yearly with approximately 17%% discount.", max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text="When this subscription was activated. Set when status transitions to 'active' or 'trial'. Null for subscriptions that haven't started yet.", null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the current billing period ends. Computed from started_at + billing_cycle duration. Used for expiration checks and renewal scheduling.', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this subscription record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='When this subscription record was last updated.')),
                ('plan', models.ForeignKey(blank=True, help_text='The subscription plan this subscription is based on. Null for legacy or migrated subscriptions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_subscriptions', to='platform.subscriptionplan')),
                ('tenant', models.ForeignKey(help_text='The tenant this subscription belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Subscription',
                'verbose_name_plural': 'Tenant Subscriptions',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='idx_subscription_tenant_status'), models.Index(fields=['expires_at'], name='idx_subscription_expires_at')],
            },
        ),
    ]
