# Generated by Django 5.2.11 on 2026-02-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_add_tenant_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Current billing amount in LKR (₨). Derived from the subscription plan's monthly or annual price. May differ from plan price if discounts or promotions are applied.", max_digits=10),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='is_auto_renew',
            field=models.BooleanField(default=True, help_text='Whether the subscription auto-renews at the end of each billing cycle. If False, the subscription expires and the tenant must manually renew.'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, help_text='Next scheduled billing date. Updated after each successful payment. Used for recurring charge scheduling.', null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text="Payment method used for this subscription. Common values: 'card', 'bank_transfer', 'mobile_payment'. Empty if no payment method has been set.", max_length=30),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the trial period ends. Calculated from started_at + trial_days (from SubscriptionPlan, default 14 days). Null if subscription was never on trial.', null=True),
        ),
    ]
