# Generated by Django 5.2.11 on 2026-03-13 00:41

import apps.products.pricing.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0009_sp05_bom_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('object_id', models.UUIDField(verbose_name='Object ID')),
                ('price_type', models.CharField(choices=[('BASE', 'Base Price'), ('SALE', 'Sale Price'), ('WHOLESALE', 'Wholesale Price'), ('COST', 'Cost Price')], help_text='Which price field changed.', max_length=20, verbose_name='Price Type')),
                ('old_value', apps.products.pricing.fields.PriceField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', apps.products.pricing.fields.PriceField(blank=True, null=True, verbose_name='New Value')),
                ('change_amount', apps.products.pricing.fields.PriceField(blank=True, help_text='new_value − old_value', null=True, verbose_name='Change Amount')),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Change %')),
                ('change_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Change Reason')),
                ('automated_change', models.BooleanField(default=False, help_text='True if this change was made by a scheduled task or signal.', verbose_name='Automated Change')),
                ('change_source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('api', 'API'), ('scheduled', 'Scheduled'), ('promotion', 'Promotion')], default='manual', max_length=20, verbose_name='Change Source')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'db_table': 'pricing_price_history',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_ph_ct_oid'), models.Index(fields=['product'], name='idx_ph_product'), models.Index(fields=['price_type'], name='idx_ph_ptype'), models.Index(fields=['created_on'], name='idx_ph_created')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('base_price', apps.products.pricing.fields.PriceField(default=Decimal('0.00'), help_text='Default selling price in LKR.', verbose_name='Base Price')),
                ('cost_price', apps.products.pricing.fields.PriceField(blank=True, help_text='Supplier or manufacturing cost in LKR.', null=True, verbose_name='Cost Price')),
                ('sale_price', apps.products.pricing.fields.PriceField(blank=True, help_text='Promotional price during sale period.', null=True, verbose_name='Sale Price')),
                ('sale_price_start', models.DateTimeField(blank=True, help_text='When the sale period begins.', null=True, verbose_name='Sale Start Date')),
                ('sale_price_end', models.DateTimeField(blank=True, help_text='When the sale period ends.', null=True, verbose_name='Sale End Date')),
                ('wholesale_price', apps.products.pricing.fields.PriceField(blank=True, help_text='Discounted price for B2B / wholesale customers.', null=True, verbose_name='Wholesale Price')),
                ('minimum_wholesale_quantity', models.PositiveIntegerField(default=1, help_text='Minimum order quantity to qualify for wholesale price.', verbose_name='Minimum Wholesale Quantity')),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether this product is subject to tax.', verbose_name='Is Taxable')),
                ('is_tax_inclusive', models.BooleanField(default=True, help_text='Whether the stored price already includes tax.', verbose_name='Tax Inclusive')),
                ('tax_exemption_reason', models.CharField(blank=True, help_text='Documentation reason if product is tax-exempt.', max_length=200, null=True, verbose_name='Tax Exemption Reason')),
                ('pricing_notes', models.TextField(blank=True, help_text='Internal notes about pricing decisions.', null=True, verbose_name='Pricing Notes')),
                ('last_cost_update', models.DateTimeField(blank=True, help_text='When the cost price was last changed.', null=True, verbose_name='Last Cost Update')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('product', models.OneToOneField(help_text='Product this pricing belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.product', verbose_name='Product')),
                ('tax_class', models.ForeignKey(blank=True, help_text='Tax classification for this product.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='products.taxclass', verbose_name='Tax Class')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'db_table': 'pricing_product_price',
                'ordering': ['product__name'],
                'permissions': [('view_cost_price', 'Can view cost prices'), ('manage_pricing', 'Can manage all pricing'), ('create_promotions', 'Can create promotional pricing')],
                'indexes': [models.Index(fields=['product'], name='idx_pp_product'), models.Index(fields=['is_taxable'], name='idx_pp_taxable'), models.Index(fields=['sale_price_start', 'sale_price_end'], name='idx_pp_sale_dates')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__lt', models.F('base_price')), _connector='OR'), name='chk_sale_lt_base'), models.CheckConstraint(condition=models.Q(('wholesale_price__isnull', True), ('wholesale_price__lt', models.F('base_price')), _connector='OR'), name='chk_wholesale_lt_base'), models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__lte', models.F('base_price')), _connector='OR'), name='chk_cost_lte_base')],
            },
        ),
        migrations.CreateModel(
            name='VariantPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('use_product_price', models.BooleanField(default=True, help_text='When True, inherit prices from the parent product.', verbose_name='Use Product Price')),
                ('base_price', apps.products.pricing.fields.PriceField(blank=True, help_text='Overridden base price for this variant.', null=True, verbose_name='Base Price Override')),
                ('sale_price', apps.products.pricing.fields.PriceField(blank=True, help_text='Overridden sale price for this variant.', null=True, verbose_name='Sale Price Override')),
                ('sale_price_start', models.DateTimeField(blank=True, null=True, verbose_name='Sale Start Override')),
                ('sale_price_end', models.DateTimeField(blank=True, null=True, verbose_name='Sale End Override')),
                ('wholesale_price', apps.products.pricing.fields.PriceField(blank=True, help_text='Overridden wholesale price for this variant.', null=True, verbose_name='Wholesale Price Override')),
                ('cost_price', apps.products.pricing.fields.PriceField(blank=True, help_text='Overridden cost price for this variant.', null=True, verbose_name='Cost Price Override')),
                ('price_adjustment_type', models.CharField(blank=True, choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], help_text='Fixed amount or percentage adjustment on parent price.', max_length=20, null=True, verbose_name='Adjustment Type')),
                ('price_adjustment_value', apps.products.pricing.fields.PriceField(blank=True, help_text='Amount or percentage to add/subtract from parent price.', null=True, verbose_name='Adjustment Value')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('variant', models.OneToOneField(help_text='Variant this pricing belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Variant Price',
                'verbose_name_plural': 'Variant Prices',
                'db_table': 'pricing_variant_price',
                'ordering': ['variant'],
                'indexes': [models.Index(fields=['variant'], name='idx_vp_variant'), models.Index(fields=['use_product_price'], name='idx_vp_useproduct')],
            },
        ),
    ]
