# Generated by Django 5.2.11 on 2026-03-13 00:54

import apps.products.pricing.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('products', '0009_sp05_bom_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TieredPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(blank=True, default='', help_text="Optional label, e.g. 'Wholesale', 'Bulk'.", max_length=100, verbose_name='Tier Name')),
                ('description', models.TextField(blank=True, default='')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum order quantity for this tier.', verbose_name='Min Quantity')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity. Leave blank for unlimited.', null=True, verbose_name='Max Quantity')),
                ('tier_price', apps.products.pricing.fields.PriceField(help_text='Per-unit price in LKR for this quantity range.', verbose_name='Tier Price (per unit)')),
                ('tier_type', models.CharField(choices=[('all_units', 'All Units (one price for entire order)'), ('incremental', 'Incremental (graduated, each tier separately)')], default='all_units', max_length=20, verbose_name='Tier Type')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Pre-calculated discount from base price.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_prices', to='products.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Tiered Pricing',
                'verbose_name_plural': 'Tiered Pricings',
                'db_table': 'pricing_tiered_pricing',
                'ordering': ['product', 'min_quantity'],
                'indexes': [models.Index(fields=['product', 'min_quantity'], name='idx_tp_prod_min'), models.Index(fields=['product', 'is_active'], name='idx_tp_prod_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_quantity__gte', 1)), name='chk_tp_min_gte_1'), models.CheckConstraint(condition=models.Q(('max_quantity__isnull', True), ('max_quantity__gt', models.F('min_quantity')), _connector='OR'), name='chk_tp_max_gt_min')],
            },
        ),
        migrations.CreateModel(
            name='VariantTieredPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('min_quantity', models.PositiveIntegerField(verbose_name='Min Quantity')),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Quantity')),
                ('tier_price', apps.products.pricing.fields.PriceField(verbose_name='Tier Price (per unit)')),
                ('tier_type', models.CharField(choices=[('all_units', 'All Units (one price for entire order)'), ('incremental', 'Incremental (graduated, each tier separately)')], default='all_units', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_pricing', to='products.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Variant Tiered Pricing',
                'verbose_name_plural': 'Variant Tiered Pricings',
                'db_table': 'pricing_variant_tiered',
                'ordering': ['variant', 'min_quantity'],
                'indexes': [models.Index(fields=['variant', 'min_quantity'], name='idx_vtp_var_min'), models.Index(fields=['variant', 'is_active'], name='idx_vtp_var_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_quantity__gte', 1)), name='chk_vtp_min_gte_1'), models.CheckConstraint(condition=models.Q(('max_quantity__isnull', True), ('max_quantity__gt', models.F('min_quantity')), _connector='OR'), name='chk_vtp_max_gt_min')],
            },
        ),
    ]
