# Generated by Django 5.2.11 on 2026-03-13 01:01

import apps.products.pricing.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_tiered_pricing'),
        ('products', '0009_sp05_bom_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sale_price', apps.products.pricing.fields.PriceField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Not Started)'), ('ACTIVE', 'Active (Currently Running)'), ('EXPIRED', 'Expired (Ended)')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority wins when schedules overlap.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_prices_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_prices', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_prices', to='products.productvariant')),
            ],
            options={
                'db_table': 'pricing_scheduled',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('scheduled_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='flash_sale_detail', serialize=False, to='pricing.scheduledprice')),
                ('max_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_sold_out', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sales',
                'db_table': 'pricing_flash_sale',
            },
        ),
        migrations.CreateModel(
            name='PromotionalPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE_OFF', 'Percentage Off'), ('FIXED_OFF', 'Fixed Amount Off'), ('FIXED_PRICE', 'Fixed Price')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('min_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage-based discounts.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('priority', models.IntegerField(default=0)),
                ('is_stackable', models.BooleanField(default=False, help_text='Can combine with other promotions.')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotional_prices', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='promotional_prices', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'pricing_promotional',
                'ordering': ['-priority', '-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('original_id', models.UUIDField(help_text='PK of the original ScheduledPrice.')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sale_price', apps.products.pricing.fields.PriceField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('priority', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_prices_history', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_prices_history', to='products.productvariant')),
            ],
            options={
                'db_table': 'pricing_scheduled_history',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_aggregated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('promotional_price', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='pricing.promotionalprice')),
                ('scheduled_price', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='pricing.scheduledprice')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('flash_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='pricing.flashsale')),
            ],
            options={
                'verbose_name': 'Promotion Analytics',
                'verbose_name_plural': 'Promotion Analytics',
                'db_table': 'pricing_promotion_analytics',
            },
        ),
        migrations.AddIndex(
            model_name='scheduledprice',
            index=models.Index(fields=['product', 'start_datetime'], name='idx_sp_prod_start'),
        ),
        migrations.AddIndex(
            model_name='scheduledprice',
            index=models.Index(fields=['variant', 'start_datetime'], name='idx_sp_var_start'),
        ),
        migrations.AddIndex(
            model_name='scheduledprice',
            index=models.Index(fields=['status', 'start_datetime'], name='idx_sp_status_start'),
        ),
        migrations.AddIndex(
            model_name='scheduledprice',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='idx_sp_date_range'),
        ),
        migrations.AddConstraint(
            model_name='scheduledprice',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('variant__isnull', False), _connector='OR'), name='scheduled_price_product_or_variant'),
        ),
        migrations.AddConstraint(
            model_name='scheduledprice',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='scheduled_price_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='promotionalprice',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='idx_promo_dates'),
        ),
        migrations.AddIndex(
            model_name='promotionalprice',
            index=models.Index(fields=['is_active', 'priority'], name='idx_promo_active_prio'),
        ),
        migrations.AddConstraint(
            model_name='promotionalprice',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='promo_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='scheduledpricehistory',
            index=models.Index(fields=['product', 'archived_at'], name='idx_sph_prod_arch'),
        ),
        migrations.AddIndex(
            model_name='scheduledpricehistory',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='idx_sph_dates'),
        ),
    ]
