# Generated by Django 5.2.11 on 2026-03-13 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_scheduled_promotional'),
        ('products', '0009_sp05_bom_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tieredpricing',
            options={'ordering': ['product', 'min_quantity'], 'permissions': [('manage_tiered_pricing', 'Can manage tiered pricing'), ('view_tier_reports', 'Can view tier reports')], 'verbose_name': 'Tiered Pricing', 'verbose_name_plural': 'Tiered Pricing Rules'},
        ),
        migrations.AddIndex(
            model_name='tieredpricing',
            index=models.Index(fields=['is_active', 'min_quantity'], name='idx_tp_active_min'),
        ),
        migrations.AddConstraint(
            model_name='tieredpricing',
            constraint=models.CheckConstraint(condition=models.Q(('tier_price__gt', 0)), name='chk_tp_price_gt_0'),
        ),
    ]
