# Generated by Django 5.2.11 on 2026-03-15 04:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0015_sp10_group_d_supplier_lead_time'),
        ('products', '0014_sp07_error_message_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], db_index=True, default='active', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('printer_type', models.CharField(choices=[('thermal', 'Thermal Printer'), ('impact', 'Impact Printer'), ('none', 'No Printer')], default='thermal', max_length=20)),
                ('receipt_printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('receipt_printer_port', models.PositiveIntegerField(blank=True, default=9100, null=True)),
                ('cash_drawer_enabled', models.BooleanField(default=True)),
                ('cash_drawer_auto_open', models.BooleanField(default=True)),
                ('barcode_scanner_enabled', models.BooleanField(default=True)),
                ('scanner_interface', models.CharField(choices=[('usb', 'USB'), ('bluetooth', 'Bluetooth'), ('wireless', 'Wireless')], default='usb', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('floor', models.CharField(blank=True, default='', max_length=50)),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('is_mobile', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('allow_price_override', models.BooleanField(default=False)),
                ('allow_discount', models.BooleanField(default=True)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('require_customer', models.BooleanField(default=False)),
                ('allow_negative_inventory', models.BooleanField(default=False)),
                ('auto_print_receipt', models.BooleanField(default=True)),
                ('receipt_copies', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('offline_mode_enabled', models.BooleanField(default=False)),
                ('receipt_header', models.TextField(blank=True, default='')),
                ('receipt_footer', models.TextField(blank=True, default='')),
                ('receipt_language', models.CharField(choices=[('en', 'English'), ('si', 'Sinhala'), ('ta', 'Tamil')], default='en', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('default_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_terminals_with_default_tax', to='products.taxclass')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'POS Terminal',
                'verbose_name_plural': 'POS Terminals',
                'db_table': 'pos_terminal',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('force_closed', 'Force Closed')], db_index=True, default='open', max_length=20)),
                ('session_number', models.CharField(max_length=50, unique=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_close_time', models.DateTimeField(blank=True, null=True)),
                ('opening_cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('opening_cash_counted_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash_notes', models.TextField(blank=True, default='')),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('closing_cash_counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_cash_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('opening_cash_counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_cash_opened', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pos.posterminal')),
            ],
            options={
                'verbose_name': 'POS Session',
                'verbose_name_plural': 'POS Sessions',
                'db_table': 'pos_session',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['code'], name='idx_pos_terminal_code'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['status'], name='idx_pos_terminal_status'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['warehouse'], name='idx_pos_terminal_warehouse'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['session_number'], name='idx_pos_session_number'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['status'], name='idx_pos_session_status'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['terminal', 'status'], name='idx_pos_session_term_stat'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['opened_at'], name='idx_pos_session_opened_at'),
        ),
    ]
