# Generated by Django 5.2.11 on 2026-03-15 05:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_sp01_cart_models'),
        ('products', '0014_sp07_error_message_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickButtonGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('code', models.CharField(help_text='Unique identifier for this group', max_length=50, unique=True, verbose_name='Code')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon name or class for the group tab', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(blank=True, default='', help_text='Hex color code for the group tab', max_length=20, verbose_name='Color')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('rows', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Rows')),
                ('columns', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Columns')),
                ('is_default', models.BooleanField(default=False, help_text='Show this group by default when POS opens', verbose_name='Default Group')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('terminals', models.ManyToManyField(blank=True, help_text='Terminals this group is assigned to (blank = all)', related_name='quick_button_groups', to='pos.posterminal', verbose_name='Terminals')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Quick Button Group',
                'verbose_name_plural': 'Quick Button Groups',
                'db_table': 'pos_quick_button_group',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('label', models.CharField(blank=True, default='', help_text='Custom label (defaults to product name)', max_length=50, verbose_name='Label')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pos/quick_buttons/', verbose_name='Image')),
                ('color', models.CharField(blank=True, default='', help_text='Hex color for the button', max_length=20, verbose_name='Color')),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Row')),
                ('column', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Column')),
                ('quick_quantity', models.DecimalField(decimal_places=3, default=1, help_text='Default quantity added when button is pressed', max_digits=10, verbose_name='Quick Quantity')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_buttons', to='products.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='pos.quickbuttongroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Quick Button',
                'verbose_name_plural': 'Quick Buttons',
                'db_table': 'pos_quick_button',
                'ordering': ['row', 'column'],
                'indexes': [models.Index(fields=['group', 'row', 'column'], name='pos_qb_position')],
                'constraints': [models.UniqueConstraint(fields=('group', 'row', 'column'), name='unique_quick_button_position')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='Search Query')),
                ('result_count', models.IntegerField(default=0, verbose_name='Result Count')),
                ('search_method', models.CharField(choices=[('barcode', 'Barcode Scan'), ('sku', 'SKU Lookup'), ('name', 'Name Search'), ('combined', 'Combined Search')], default='combined', max_length=20, verbose_name='Search Method')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product', verbose_name='Selected Product')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to='pos.posterminal', verbose_name='Terminal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_search_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search History',
                'db_table': 'pos_search_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['terminal', '-timestamp'], name='pos_sh_terminal_ts'), models.Index(fields=['user', '-timestamp'], name='pos_sh_user_ts')],
            },
        ),
    ]
