# Generated by Django 5.2.11 on 2026-03-15 05:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_sp01_search_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card (Visa/Mastercard)'), ('bank_transfer', 'Bank Transfer'), ('mobile_frimi', 'FriMi'), ('mobile_genie', 'Dialog Genie'), ('store_credit', 'Store Credit')], max_length=20, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (LKR)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='pending', max_length=20, verbose_name='Status')),
                ('amount_tendered', models.DecimalField(blank=True, decimal_places=2, help_text='Cash given by customer', max_digits=12, null=True, verbose_name='Amount Tendered')),
                ('change_due', models.DecimalField(blank=True, decimal_places=2, help_text='Change to return to customer', max_digits=12, null=True, verbose_name='Change Due')),
                ('reference_number', models.CharField(blank=True, default='', help_text='External payment reference (bank/mobile)', max_length=100, verbose_name='Reference Number')),
                ('authorization_code', models.CharField(blank=True, default='', help_text='Card payment authorization code', max_length=50, verbose_name='Authorization Code')),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', help_text='Gateway transaction identifier', max_length=100, verbose_name='Transaction ID')),
                ('gateway_response', models.TextField(blank=True, default='', help_text='Full JSON response from payment gateway', verbose_name='Gateway Response')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Voided At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.poscart', verbose_name='Cart')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_payments_processed', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'POS Payment',
                'verbose_name_plural': 'POS Payments',
                'db_table': 'pos_payment',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['cart', 'status'], name='pos_pay_cart_status'), models.Index(fields=['method'], name='pos_pay_method'), models.Index(fields=['-created_on'], name='pos_pay_created'), models.Index(fields=['reference_number'], name='pos_pay_ref')],
            },
        ),
    ]
