# Generated by Django 5.2.11 on 2026-03-15 11:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_sp10_group_d_supplier_lead_time'),
        ('pos', '0004_sp01_payment_model'),
        ('products', '0014_sp07_error_message_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payment_voided', 'Payment Voided'), ('payment_refunded', 'Payment Refunded'), ('cart_completed', 'Cart Completed'), ('cart_voided', 'Cart Voided')], max_length=30, verbose_name='Event Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Payment Audit Log',
                'verbose_name_plural': 'Payment Audit Logs',
                'db_table': 'pos_payment_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='posterminal',
            options={'ordering': ['warehouse', 'code'], 'verbose_name': 'POS Terminal', 'verbose_name_plural': 'POS Terminals'},
        ),
        migrations.AddField(
            model_name='poscart',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_carts', to=settings.AUTH_USER_MODEL, verbose_name='Held By'),
        ),
        migrations.AddField(
            model_name='poscart',
            name='held_identifier',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique identifier for retrieving held carts', max_length=50, verbose_name='Held Identifier'),
        ),
        migrations.AddField(
            model_name='poscart',
            name='held_reason',
            field=models.TextField(blank=True, default='', verbose_name='Held Reason'),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Failed At'),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Refunded At'),
        ),
        migrations.AddField(
            model_name='possession',
            name='card_sales_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='possession',
            name='cash_sales_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='possession',
            name='closing_cash_counted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='possession',
            name='closing_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='possession',
            name='items_sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possession',
            name='net_sales_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='possession',
            name='other_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='possession',
            name='refund_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possession',
            name='variance_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='poscart',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='poscart',
            name='grand_total',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='poscart',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount in LKR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount (LKR)'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card (Visa/Mastercard)'), ('bank_transfer', 'Bank Transfer'), ('mobile_frimi', 'FriMi'), ('mobile_genie', 'Dialog Genie'), ('store_credit', 'Store Credit'), ('payhere', 'PayHere')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='transaction_id',
            field=models.CharField(blank=True, default=None, help_text='Gateway transaction identifier', max_length=100, null=True, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='actual_cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='possession',
            name='total_refunds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='possession',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='pospayment',
            index=models.Index(fields=['paid_at'], name='pos_pay_paid_at'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['warehouse', 'status'], name='idx_pos_terminal_wh_status'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['warehouse', 'is_mobile'], name='idx_pos_terminal_wh_mobile'),
        ),
        migrations.AlterModelTable(
            name='posterminal',
            table='pos_terminals',
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.poscart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.pospayment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['cart', '-timestamp'], name='pos_audit_cart'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['event_type', '-timestamp'], name='pos_audit_event'),
        ),
    ]
