# Generated by Django 5.2.11 on 2026-03-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_sp02_offline_data_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinetransaction',
            name='related_sale_id',
            field=models.UUIDField(blank=True, help_text='UUID of the Sale record created after successful sync.', null=True),
        ),
    ]
