# Generated by Django 5.2.11 on 2026-03-16 03:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_sp03_receipt_receipt_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='receipt',
            new_name='pos_receipt_cart_id_544fe9_idx',
            old_name='pos_receipt_cart_id_receipt_type_idx',
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='receiptsequence',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='receiptsequence',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on'),
        ),
        migrations.AddField(
            model_name='receiptsequence',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on'),
        ),
        migrations.AddField(
            model_name='receiptsequence',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on'),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='header_line_1_center',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='header_line_2_center',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='header_line_3_center',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='return_policy_bold_heading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='return_policy_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='return_policy_separator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='show_return_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='receiptsequence',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='receiptsequence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receiptsequence',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='receiptsequence',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='receiptsequence',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='separator_length',
            field=models.CharField(choices=[('full', 'Full Width'), ('half', 'Half Width'), ('custom', 'Custom')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on'),
        ),
    ]
