# Generated by Django 5.2.11 on 2026-03-17 02:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0010_sp05_group_e_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('invoice_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated on issue. Format: {PREFIX}-YYYY-NNNNN', max_length=50, null=True, unique=True, verbose_name='Invoice Number')),
                ('type', models.CharField(choices=[('STANDARD', 'Standard Invoice'), ('SVAT', 'Simplified VAT Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], db_index=True, default='STANDARD', max_length=20, verbose_name='Invoice Type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='Invoice Status')),
                ('customer_name', models.CharField(blank=True, default='', help_text='Customer name at time of invoice', max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', help_text='Customer email at time of invoice', max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', help_text='Customer phone at time of invoice', max_length=20)),
                ('customer_address', models.TextField(blank=True, default='', help_text='Customer address at time of invoice')),
                ('business_name', models.CharField(blank=True, default='', help_text='Business name at time of invoice', max_length=255)),
                ('business_address', models.TextField(blank=True, default='', help_text='Business address at time of invoice')),
                ('business_phone', models.CharField(blank=True, default='', help_text='Business phone at time of invoice', max_length=20)),
                ('business_email', models.EmailField(blank=True, default='', help_text='Business email at time of invoice', max_length=255)),
                ('business_website', models.URLField(blank=True, default='', help_text='Business website URL', max_length=255)),
                ('business_registration_number', models.CharField(blank=True, default='', help_text='Business Registration Number (BRN)', max_length=50)),
                ('vat_registration_number', models.CharField(blank=True, default='', help_text='VAT Registration Number', max_length=50)),
                ('svat_number', models.CharField(blank=True, default='', help_text='Simplified VAT Registration Number', max_length=50)),
                ('tax_scheme', models.CharField(choices=[('VAT', 'Value Added Tax'), ('SVAT', 'Simplified VAT'), ('EXEMPT', 'Tax Exempt'), ('NONE', 'No Tax')], default='VAT', help_text='Tax scheme applicable for this invoice', max_length=20)),
                ('issue_date', models.DateField(blank=True, help_text='Date the invoice was issued', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('paid_date', models.DateField(blank=True, help_text='Date full payment was received', null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, help_text='Date/time the invoice was cancelled', null=True)),
                ('voided_date', models.DateTimeField(blank=True, help_text='Date/time the invoice was voided', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line item totals before tax and discount', max_digits=15)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='', help_text='Header-level discount type', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount value (percentage or fixed amount)', max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax amount', max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Grand total (subtotal - discount + tax)', max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid', max_digits=15)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining balance (total - amount_paid)', max_digits=15)),
                ('tax_breakdown', models.JSONField(blank=True, default=list, help_text='Tax breakdown by rate [{rate, taxable_amount, tax_amount}]')),
                ('external_reference', models.CharField(blank=True, default='', help_text='External reference number', max_length=255)),
                ('terms_and_conditions', models.TextField(blank=True, default='', help_text='Terms and conditions text for invoice')),
                ('payment_instructions', models.TextField(blank=True, default='', help_text='Payment instructions (bank details, etc.)')),
                ('footer_text', models.TextField(blank=True, default='', help_text='Custom footer text')),
                ('notes', models.TextField(blank=True, default='', help_text='Notes visible to customer')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Internal notes (not on invoice)')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom fields for extensibility')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment file references')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for invoice categorization')),
                ('currency', models.CharField(db_index=True, default='LKR', help_text='Currency code (ISO 4217)', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate to LKR', max_digits=12)),
                ('currency_symbol', models.CharField(default='LKR', help_text='Currency symbol for display', max_length=10)),
                ('base_currency_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total in base currency (LKR)', max_digits=15)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated invoice PDF', null=True, upload_to='invoices/pdfs/%Y/%m/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, help_text='When the PDF was last generated', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_records', to='customers.customer', verbose_name='Customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_records', to='orders.order', verbose_name='Source Order')),
                ('related_invoice', models.ForeignKey(blank=True, help_text='Original invoice (for credit/debit notes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='invoices.invoice', verbose_name='Related Invoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status', 'type'], name='inv_status_type_idx'), models.Index(fields=['customer'], name='inv_customer_idx'), models.Index(fields=['issue_date'], name='inv_issue_date_idx'), models.Index(fields=['due_date'], name='inv_due_date_idx'), models.Index(fields=['order'], name='inv_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal__gte', Decimal('0'))), name='inv_subtotal_non_negative'), models.CheckConstraint(condition=models.Q(('total__gte', Decimal('0'))), name='inv_total_non_negative'), models.CheckConstraint(condition=models.Q(('amount_paid__gte', Decimal('0'))), name='inv_amount_paid_non_negative')],
            },
        ),
    ]
