# Generated by Django 5.2.11 on 2026-03-17 02:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_sp06_group_a_invoice_model'),
        ('products', '0014_sp07_error_message_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display position/order of line item')),
                ('product_snapshot', models.JSONField(blank=True, default=dict, help_text='Product data snapshot at time of invoice')),
                ('description', models.CharField(blank=True, default='', help_text='Line item description', max_length=500)),
                ('sku', models.CharField(blank=True, default='', help_text='SKU at time of invoice', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantity of items', max_digits=10)),
                ('unit_of_measure', models.CharField(blank=True, default='unit', help_text='Unit of measure (e.g., unit, kg, hour)', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price', max_digits=15)),
                ('original_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original price before any adjustments', max_digits=15)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='', help_text='Discount type for this line', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount value (percentage or fixed amount)', max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount', max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate percentage (e.g., 12.00 for 12% VAT)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount', max_digits=15)),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether this line item is taxable')),
                ('tax_code', models.CharField(blank=True, default='', help_text='Tax category code (e.g., STANDARD_RATE, EXEMPT)', max_length=50)),
                ('tax_description', models.CharField(blank=True, default='', help_text="Tax description (e.g., 'VAT 12%')", max_length=100)),
                ('hsn_code', models.CharField(blank=True, default='', help_text='HSN/SAC code for product classification', max_length=20)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total (qty × price - discount + tax)', max_digits=15)),
                ('invoice', models.ForeignKey(help_text='Invoice this line item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
                ('product', models.ForeignKey(blank=True, help_text='Product reference (optional for custom items)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_line_items', to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Product variant reference (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_line_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['invoice', 'position'], name='inv_line_inv_pos_idx')],
            },
        ),
    ]
