# Generated by Django 5.2.11 on 2026-03-17 02:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_sp06_group_b_line_items'),
        ('tenants', '0010_add_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='invoices.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice History',
                'verbose_name_plural': 'Invoice History',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('invoice_number_prefix', models.CharField(default='INV', max_length=10)),
                ('credit_note_prefix', models.CharField(default='CN', max_length=10)),
                ('debit_note_prefix', models.CharField(default='DN', max_length=10)),
                ('sequence_start', models.IntegerField(default=1)),
                ('reset_sequence_yearly', models.BooleanField(default=True)),
                ('default_due_days', models.IntegerField(default=30)),
                ('default_payment_terms', models.CharField(default='Net 30', max_length=100)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('default_tax_inclusive', models.BooleanField(default=False)),
                ('show_business_registration', models.BooleanField(default=True)),
                ('show_vat_registration', models.BooleanField(default=True)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_bank_details', models.BooleanField(default=True)),
                ('auto_send_on_issue', models.BooleanField(default=False)),
                ('auto_issue_from_order', models.BooleanField(default=False)),
                ('require_approval', models.BooleanField(default=False)),
                ('allow_editing_issued', models.BooleanField(default=False)),
                ('apply_late_fees', models.BooleanField(default=False)),
                ('late_fee_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('late_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage rate (e.g., 2.00 for 2%)', max_digits=5)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed amount in LKR', max_digits=10)),
                ('late_fee_grace_days', models.IntegerField(default=7)),
                ('send_payment_reminders', models.BooleanField(default=True)),
                ('reminder_days_before_due', models.JSONField(blank=True, default=list)),
                ('reminder_days_after_due', models.JSONField(blank=True, default=list)),
                ('default_terms_and_conditions', models.TextField(blank=True, default='')),
                ('default_payment_instructions', models.TextField(blank=True, default='')),
                ('default_footer_text', models.TextField(blank=True, default='')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Invoice Settings',
                'verbose_name_plural': 'Invoice Settings',
            },
        ),
    ]
