# Generated by Django 5.2.11 on 2026-03-17 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_sp06_group_c_services_history_settings'),
        ('tenants', '0010_add_billing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Template', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (recommended: 200x100px)', null=True, upload_to='invoice_templates/logos/')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_website', models.URLField(blank=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=50)),
                ('vat_registration_number', models.CharField(blank=True, max_length=50)),
                ('svat_registration_number', models.CharField(blank=True, max_length=50)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_brn', models.BooleanField(default=True)),
                ('show_vat', models.BooleanField(default=True)),
                ('show_website', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('accent_color', models.CharField(default='#6c757d', max_length=7)),
                ('text_color', models.CharField(default='#212529', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Times', 'Times New Roman'), ('Courier', 'Courier'), ('Noto Sans', 'Noto Sans (Unicode)'), ('Roboto', 'Roboto')], default='Arial', max_length=50)),
                ('font_size', models.IntegerField(default=10)),
                ('heading_font_size', models.IntegerField(default=14)),
                ('page_size', models.CharField(choices=[('A4', 'A4 (210 x 297 mm)'), ('Letter', 'Letter (8.5 x 11 in)')], default='A4', max_length=10)),
                ('page_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('margin_top', models.IntegerField(default=20, help_text='Top margin in mm')),
                ('margin_bottom', models.IntegerField(default=20, help_text='Bottom margin in mm')),
                ('margin_left', models.IntegerField(default=15, help_text='Left margin in mm')),
                ('margin_right', models.IntegerField(default=15, help_text='Right margin in mm')),
                ('use_borders', models.BooleanField(default=True)),
                ('use_shading', models.BooleanField(default=True)),
                ('show_grid', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('payment_instructions', models.TextField(blank=True, default='Please make payment via bank transfer to the account details shown above. Include invoice number as payment reference.')),
                ('terms_and_conditions', models.TextField(blank=True, default='1. Payment is due within the specified period.\n2. Late payments may incur additional charges.\n3. Goods remain property of seller until full payment received.')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='invoice_templates/signatures/')),
                ('authorized_signatory', models.CharField(blank=True, max_length=100)),
                ('signatory_designation', models.CharField(blank=True, max_length=100)),
                ('show_bank_details', models.BooleanField(default=True)),
                ('show_terms', models.BooleanField(default=True)),
                ('show_signature', models.BooleanField(default=False)),
                ('footer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_template', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
                'db_table': 'invoice_templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
