# Generated by Django 5.2.11 on 2026-03-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0004_sp06_group_e_invoice_template'),
        ('orders', '0010_sp05_group_e_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_tax_id',
            field=models.CharField(blank=True, default='', help_text='Customer VAT or Tax ID number', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.IntegerField(default=30, help_text='Payment terms in days (e.g., 30 for Net 30)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_version',
            field=models.IntegerField(default=0, help_text='PDF generation version number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_date',
            field=models.DateField(blank=True, help_text='Date invoice was sent to customer', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Reference to customer record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order', verbose_name='Source Order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='related_invoice',
            field=models.ForeignKey(blank=True, help_text='Original invoice (for credit/debit notes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_invoices', to='invoices.invoice', verbose_name='Related Invoice'),
        ),
    ]
