# Generated by Django 5.2.11 on 2026-03-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_sp06_audit_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='hsn_description',
            field=models.CharField(blank=True, default='', help_text='Description of HSN/SAC category', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Line item description'),
        ),
    ]
