# Generated by Django 5.2.11 on 2026-03-17 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_sp06_audit_group_b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoicehistory',
            index=models.Index(fields=['invoice'], name='invhistory_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicehistory',
            index=models.Index(fields=['action'], name='invhistory_action_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicehistory',
            index=models.Index(fields=['created_on'], name='invhistory_created_idx'),
        ),
    ]
