# Generated by Django 5.2.11 on 2026-03-17 05:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0007_sp06_audit_group_c'),
        ('orders', '0010_sp05_group_e_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('method', models.CharField(db_index=True, help_text='The payment method code (e.g. CASH, CARD).', max_length=20, unique=True, verbose_name='Payment Method')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this payment method is currently available.', verbose_name='Active')),
                ('display_name', models.CharField(blank=True, default='', help_text='Custom display name for this method. Falls back to default if blank.', max_length=100, verbose_name='Display Name')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order for display (lower numbers appear first).', verbose_name='Display Order')),
                ('settings', models.JSONField(blank=True, default=None, help_text='Method-specific configuration (gateway keys, account numbers, etc).', null=True, verbose_name='Settings')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum payment amount for this method.', max_digits=15, null=True, verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum payment amount for this method.', max_digits=15, null=True, verbose_name='Maximum Amount')),
            ],
            options={
                'verbose_name': 'Payment Method Configuration',
                'verbose_name_plural': 'Payment Method Configurations',
                'db_table': 'payments_paymentmethodconfig',
                'ordering': ['display_order', 'method'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year for this sequence.', verbose_name='Year')),
                ('last_number', models.IntegerField(default=0, help_text='Last used sequence number for this year.', verbose_name='Last Number')),
            ],
            options={
                'verbose_name': 'Payment Sequence',
                'verbose_name_plural': 'Payment Sequences',
                'db_table': 'payments_paymentsequence',
                'unique_together': {('year',)},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('payment_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated. Format: PAY-YYYY-NNNNN', max_length=30, unique=True, verbose_name='Payment Number')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE', 'Mobile Payment'), ('CHECK', 'Check'), ('STORE_CREDIT', 'Store Credit')], db_index=True, help_text='Method of payment (e.g. cash, card, bank transfer).', max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in the specified currency.', max_digits=15, verbose_name='Amount')),
                ('payment_date', models.DateField(blank=True, help_text='Date the payment was received.', null=True, verbose_name='Payment Date')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when the payment was processed/completed.', null=True, verbose_name='Processed At')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when the payment was cancelled.', null=True, verbose_name='Cancelled At')),
                ('currency', models.CharField(default='LKR', help_text='ISO 4217 currency code (e.g. LKR, USD).', max_length=3, verbose_name='Currency')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate to base currency (LKR). 1.0 for LKR payments.', max_digits=12, null=True, verbose_name='Exchange Rate')),
                ('amount_in_base_currency', models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount converted to base currency (LKR).', max_digits=15, null=True, verbose_name='Amount in Base Currency')),
                ('method_details', models.JSONField(blank=True, default=None, help_text='Method-specific details. Card: last4, card_type, approval_code. Check: check_number, bank_name. Mobile: provider, transaction_id.', null=True, verbose_name='Method Details')),
                ('reference_number', models.CharField(blank=True, default='', help_text='External reference (gateway or bank reference).', max_length=50, verbose_name='Reference Number')),
                ('transaction_id', models.CharField(blank=True, default='', help_text='External payment gateway transaction ID.', max_length=100, verbose_name='Transaction ID')),
                ('notes', models.TextField(blank=True, default='', help_text='Customer-visible notes about this payment.', verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Internal notes (not visible to customer).', verbose_name='Internal Notes')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('customer', models.ForeignKey(blank=True, help_text='Customer who made the payment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='Linked invoice (if applicable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.invoice', verbose_name='Invoice')),
                ('order', models.ForeignKey(blank=True, help_text='Linked order (if applicable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Order')),
                ('received_by', models.ForeignKey(blank=True, help_text='User who received/recorded the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments_payment',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status'], name='idx_payment_status'), models.Index(fields=['method'], name='idx_payment_method'), models.Index(fields=['payment_date'], name='idx_payment_date'), models.Index(fields=['customer'], name='idx_payment_customer'), models.Index(fields=['invoice'], name='idx_payment_invoice'), models.Index(fields=['order'], name='idx_payment_order'), models.Index(fields=['status', 'payment_date'], name='idx_payment_status_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive')],
            },
        ),
    ]
