# Generated by Django 5.2.11 on 2026-03-17 05:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_sp06_audit_group_c'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('default_currency', models.CharField(default='LKR', help_text='Default currency for payments.', max_length=3, verbose_name='Default Currency')),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Payments above this amount require approval. 0 = no approval required.', max_digits=15, verbose_name='Approval Threshold')),
                ('duplicate_detection_minutes', models.IntegerField(default=5, help_text='Time window for duplicate payment detection.', verbose_name='Duplicate Detection Window (minutes)')),
                ('require_invoice_for_payment', models.BooleanField(default=False, help_text='Whether payments must be linked to an invoice.', verbose_name='Require Invoice')),
                ('allow_overpayment', models.BooleanField(default=False, help_text='Whether payments can exceed invoice balance.', verbose_name='Allow Overpayment')),
                ('auto_complete_cash', models.BooleanField(default=True, help_text='Automatically mark cash payments as completed.', verbose_name='Auto-Complete Cash')),
                ('enable_processing_fees', models.BooleanField(default=False, help_text='Whether to calculate and charge processing fees.', verbose_name='Enable Processing Fees')),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
                'db_table': 'payments_paymentsettings',
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated from this payment to this invoice.', max_digits=15, verbose_name='Allocated Amount')),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this allocation.', verbose_name='Notes')),
                ('invoice', models.ForeignKey(help_text='The invoice receiving the allocation.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='invoices.invoice', verbose_name='Invoice')),
                ('payment', models.ForeignKey(help_text='The payment being allocated.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'db_table': 'payments_paymentallocation',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['invoice'], name='idx_payalloc_invoice')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payalloc_amount_positive')],
                'unique_together': {('payment', 'invoice')},
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Payment Created'), ('STATUS_CHANGE', 'Status Changed'), ('AMOUNT_MODIFIED', 'Amount Modified'), ('APPROVED', 'Payment Approved'), ('REJECTED', 'Payment Rejected'), ('ALLOCATED', 'Allocated to Invoice'), ('REFUNDED', 'Payment Refunded'), ('NOTE_ADDED', 'Note Added'), ('METHOD_MODIFIED', 'Payment Method Modified'), ('CUSTOMER_CHANGED', 'Customer Changed')], help_text='Type of action/change.', max_length=50, verbose_name='Action')),
                ('old_value', models.JSONField(blank=True, default=None, help_text='Previous value before change (JSON).', null=True, verbose_name='Old Value')),
                ('new_value', models.JSONField(blank=True, default=None, help_text='New value after change (JSON).', null=True, verbose_name='New Value')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change occurred.', verbose_name='Changed At')),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of the change.', verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of user (for security audit).', null=True, verbose_name='IP Address')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('payment', models.ForeignKey(help_text='Payment this history entry relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'db_table': 'payments_paymenthistory',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['payment', '-changed_at'], name='idx_payhistory_payment_date'), models.Index(fields=['action', '-changed_at'], name='idx_payhistory_action_date')],
            },
        ),
    ]
