# Generated by Django 5.2.11 on 2026-03-17 05:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0007_sp06_audit_group_c'),
        ('orders', '0010_sp05_group_e_audit_fields'),
        ('payments', '0002_paymentsettings_paymentallocation_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('plan_number', models.CharField(db_index=True, help_text='Format: PP-YYYY-NNNNN', max_length=30, unique=True, verbose_name='Plan Number')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount to be paid via this plan.', max_digits=15, verbose_name='Total Amount')),
                ('number_of_installments', models.IntegerField(verbose_name='Number of Installments')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=20, verbose_name='Frequency')),
                ('start_date', models.DateField(help_text='Date of the first installment.', verbose_name='Start Date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='customers.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='invoices.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
                'db_table': 'payments_paymentplan',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('installment_number', models.IntegerField(help_text='Sequential number (1, 2, 3...).', verbose_name='Installment Number')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('payment', models.ForeignKey(blank=True, help_text='Linked payment when this installment is paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment', to='payments.payment', verbose_name='Payment')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.paymentplan', verbose_name='Payment Plan')),
            ],
            options={
                'verbose_name': 'Payment Plan Installment',
                'verbose_name_plural': 'Payment Plan Installments',
                'db_table': 'payments_paymentplaninstallment',
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='SplitPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('split_payment_number', models.CharField(db_index=True, help_text='Unique identifier for this split payment.', max_length=30, unique=True, verbose_name='Split Payment Number')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount across all payment components.', max_digits=15, verbose_name='Total Amount')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_payments', to='customers.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_payments', to='invoices.invoice', verbose_name='Invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_payments', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Split Payment',
                'verbose_name_plural': 'Split Payments',
                'db_table': 'payments_splitpayment',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SplitPaymentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0, help_text='Display ordering of this component.', verbose_name='Order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_component', to='payments.payment', verbose_name='Payment')),
                ('split_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payments.splitpayment', verbose_name='Split Payment')),
            ],
            options={
                'verbose_name': 'Split Payment Component',
                'verbose_name_plural': 'Split Payment Components',
                'db_table': 'payments_splitpaymentcomponent',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='plan_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_installments__gt', 0)), name='plan_installments_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentplaninstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='installment_amount_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentplaninstallment',
            unique_together={('payment_plan', 'installment_number')},
        ),
        migrations.AddConstraint(
            model_name='splitpayment',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='splitpay_total_positive'),
        ),
    ]
