# Generated by Django 5.2.11 on 2026-03-17 06:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentplan_paymentplaninstallment_splitpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('refund_number', models.CharField(db_index=True, help_text='Format: REF-YYYY-NNNNN', max_length=30, unique=True, verbose_name='Refund Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Refund Amount')),
                ('reason', models.CharField(choices=[('RETURN', 'Goods Return'), ('OVERCHARGE', 'Overcharge'), ('CANCELLED', 'Order Cancelled'), ('DUPLICATE', 'Duplicate Payment'), ('DEFECTIVE', 'Defective Product'), ('SERVICE_ISSUE', 'Service Issue'), ('OTHER', 'Other')], max_length=30, verbose_name='Reason')),
                ('reason_notes', models.TextField(blank=True, default='', help_text='Additional details about the refund reason.', verbose_name='Reason Details')),
                ('refund_method', models.CharField(choices=[('ORIGINAL', 'Original Payment Method'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('STORE_CREDIT', 'Store Credit')], default='ORIGINAL', max_length=20, verbose_name='Refund Method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('original_payment', models.ForeignKey(help_text='The original payment being refunded.', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='Original Payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'payments_refund',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status'], name='idx_refund_status'), models.Index(fields=['original_payment'], name='idx_refund_payment')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive')],
            },
        ),
    ]
