# Generated by Django 5.2.11 on 2026-03-17 06:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0007_sp06_audit_group_c'),
        ('payments', '0004_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('receipt_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('receipt_date', models.DateField()),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/pdfs/%Y/%m/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='invoices.invoice')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-created_on'],
                'indexes': [models.Index(fields=['customer', '-receipt_date'], name='payments_pa_custome_e6f717_idx'), models.Index(fields=['payment'], name='payments_pa_payment_ee1061_idx'), models.Index(fields=['invoice'], name='payments_pa_invoice_c4d148_idx'), models.Index(fields=['-receipt_date'], name='payments_pa_receipt_c8434c_idx'), models.Index(fields=['is_sent', '-sent_at'], name='payments_pa_is_sent_4c68ed_idx')],
            },
        ),
    ]
