# Generated by Django 5.2.11 on 2026-03-17 07:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0007_sp06_audit_group_c'),
        ('orders', '0010_sp05_group_e_audit_fields'),
        ('payments', '0005_paymentreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payment_status_date',
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='accepted_card_types',
            field=models.JSONField(blank=True, default=None, help_text='["VISA", "MASTERCARD", "AMEX"]', null=True, verbose_name='Accepted Card Types'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='allow_partial_payment',
            field=models.BooleanField(default=True, verbose_name='Allow Partial'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='allow_post_dated_checks',
            field=models.BooleanField(default=False, verbose_name='Allow Post-Dated Checks'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='allow_refund',
            field=models.BooleanField(default=True, verbose_name='Allow Refund'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='allow_split_payment',
            field=models.BooleanField(default=True, verbose_name='Allow Split'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amounts above this require manager approval.', max_digits=15, null=True, verbose_name='Approval Threshold'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='auto_reconcile',
            field=models.BooleanField(default=False, verbose_name='Auto Reconcile'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='check_clearing_days',
            field=models.IntegerField(default=3, verbose_name='Check Clearing Days'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='daily_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total amount via this method per day (fraud prevention).', max_digits=15, null=True, verbose_name='Daily Limit'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='gateway_api_key_reference',
            field=models.CharField(blank=True, default='', help_text='Reference to secure vault for API key (never store raw key).', max_length=100, verbose_name='API Key Reference'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='gateway_merchant_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Gateway Merchant ID'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='gateway_name',
            field=models.CharField(blank=True, default='', help_text='Payment gateway provider (e.g. Stripe, PayHere).', max_length=100, verbose_name='Gateway Name'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='UI icon identifier for this method.', max_length=50, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Instructions displayed to customer for this method.', verbose_name='Customer Instructions'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Whether this payment method is enabled for transactions.', verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='max_post_dated_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max Post-Dated Days'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='processing_fee_type',
            field=models.CharField(blank=True, default='', help_text='PERCENTAGE or FIXED.', max_length=20, verbose_name='Fee Type'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='processing_fee_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Fee Value'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='provider_merchant_ids',
            field=models.JSONField(blank=True, default=None, help_text='{"FriMi": "MERCHANT-ID"}', null=True, verbose_name='Provider Merchant IDs'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='receipt_label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Receipt Label'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='receipt_message',
            field=models.TextField(blank=True, default='', verbose_name='Receipt Message'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='reconciliation_account',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='GL Account Code'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='refund_within_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Refund Window (Days)'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='require_billing_address',
            field=models.BooleanField(default=False, verbose_name='Require Billing Address'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='require_cvv',
            field=models.BooleanField(default=True, verbose_name='Require CVV'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Requires Approval'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='settlement_period_days',
            field=models.IntegerField(default=1, verbose_name='Settlement Period (Days)'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='show_on_receipt',
            field=models.BooleanField(default=True, verbose_name='Show on Receipt'),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='supported_providers',
            field=models.JSONField(blank=True, default=None, help_text='["FriMi", "eZ Cash", "mCash"]', null=True, verbose_name='Supported Providers'),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='settings',
            field=models.JSONField(blank=True, default=None, help_text='Catch-all for extra method-specific configuration.', null=True, verbose_name='Additional Settings'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_number'], name='idx_payment_reference'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['currency'], name='idx_payment_currency'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'payment_date'], name='idx_payment_customer_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'method'], name='idx_payment_status_method'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'status'], name='idx_payment_date_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_on', 'status'], name='idx_payment_created_status'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'LKR'), ('exchange_rate__isnull', False), _connector='OR'), name='payment_foreign_currency_rate_required'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__isnull', True), ('exchange_rate__gt', 0), _connector='OR'), name='payment_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('processed_at__isnull', True), ('cancelled_at__isnull', True), _connector='OR'), name='payment_not_both_processed_cancelled'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
