# Generated by Django 5.2.11 on 2026-03-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_sp06_audit_group_c'),
        ('payments', '0006_sp07_audit_group_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='auto_allocate_to_oldest',
            field=models.BooleanField(default=True, help_text='Automatically allocate payments to oldest invoices first.', verbose_name='Auto-Allocate to Oldest'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='convert_overpayment_to_credit',
            field=models.BooleanField(default=True, help_text='Convert overpayments to store credit.', verbose_name='Convert Overpayment to Credit'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='currency_symbol',
            field=models.CharField(default='Rs.', help_text='Currency symbol for display.', max_length=5, verbose_name='Currency Symbol'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='decimal_places',
            field=models.IntegerField(default=2, help_text='Number of decimal places for currency.', verbose_name='Decimal Places'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='default_payment_terms_days',
            field=models.IntegerField(default=30, help_text='Default payment terms in days (e.g., Net 30).', verbose_name='Default Payment Terms (days)'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='enable_late_fees',
            field=models.BooleanField(default=False, help_text='Enable late payment fees.', verbose_name='Enable Late Fees'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='grace_period_days',
            field=models.IntegerField(default=0, help_text='Grace period before applying late fees.', verbose_name='Grace Period (days)'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='include_company_logo',
            field=models.BooleanField(default=True, help_text='Include company logo on receipts.', verbose_name='Include Company Logo'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='include_payment_method_details',
            field=models.BooleanField(default=True, help_text='Include payment method details (card last 4, etc.) on receipt.', verbose_name='Include Payment Method Details'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_fee_frequency',
            field=models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='ONCE', help_text='How often to apply late fees.', max_length=20, verbose_name='Late Fee Frequency'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_fee_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage of Outstanding'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', help_text='Type of late fee calculation.', max_length=20, verbose_name='Late Fee Type'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='late_fee_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late fee amount (percentage or fixed amount in LKR).', max_digits=10, verbose_name='Late Fee Value'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_reminder_days',
            field=models.IntegerField(default=7, help_text='Days before due date to send payment reminder.', verbose_name='Payment Reminder Days'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='receipt_footer_text',
            field=models.TextField(blank=True, default='', help_text='Custom footer text for payment receipts (terms, contact info).', verbose_name='Receipt Footer Text'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='receipt_header_text',
            field=models.TextField(blank=True, default='', help_text='Custom header text for payment receipts.', verbose_name='Receipt Header Text'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='receipt_prefix',
            field=models.CharField(default='REC', help_text='Prefix for receipt numbers (e.g., REC-2026-00001).', max_length=10, verbose_name='Receipt Prefix'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='require_customer_for_payment',
            field=models.BooleanField(default=True, help_text='Require customer to be specified for all payments.', verbose_name='Require Customer'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='send_overdue_reminders',
            field=models.BooleanField(default=True, help_text='Send reminders for overdue payments.', verbose_name='Send Overdue Reminders'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='send_payment_confirmation',
            field=models.BooleanField(default=True, help_text='Send email confirmation on payment receipt.', verbose_name='Send Payment Confirmation'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='send_payment_receipt',
            field=models.BooleanField(default=True, help_text='Auto-generate and send payment receipts.', verbose_name='Send Payment Receipt'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice', 'created_on'], name='idx_payalloc_invoice_date'),
        ),
    ]
