# Generated by Django 5.2.11 on 2026-03-17 09:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_sp07_audit_group_b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='splitpaymentcomponent',
            options={'ordering': ['sequence'], 'verbose_name': 'Split Payment Component', 'verbose_name_plural': 'Split Payment Components'},
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='allow_early_payment',
            field=models.BooleanField(default=True, help_text='Whether early installment payments are permitted.', verbose_name='Allow Early Payment'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when plan was fully completed.', null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date of the last installment.', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='grace_period_days',
            field=models.IntegerField(default=3, help_text='Days after due date before late fees apply.', verbose_name='Grace Period Days'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Date of the most recent installment payment.', null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='late_fee_applicable',
            field=models.BooleanField(default=False, help_text='Whether late fees apply to overdue installments.', verbose_name='Late Fee Applicable'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='max_missed_installments',
            field=models.IntegerField(default=2, help_text='Number of missed installments before defaulting the plan.', verbose_name='Max Missed Installments'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='plan_name',
            field=models.CharField(blank=True, default='', help_text='Optional descriptive name for this payment plan.', max_length=200, verbose_name='Plan Name'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount paid so far for this installment.', max_digits=15, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='late_fee_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Late fee amount applied to this installment.', max_digits=10, verbose_name='Late Fee Applied'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='reminder_sent_date',
            field=models.DateField(blank=True, help_text='Date when payment reminder was last sent.', null=True, verbose_name='Reminder Sent Date'),
        ),
        migrations.AddField(
            model_name='splitpayment',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when split payment was fully processed.', null=True, verbose_name='Processed At'),
        ),
        migrations.AddField(
            model_name='splitpayment',
            name='split_count',
            field=models.IntegerField(default=0, help_text='Number of payment components.', verbose_name='Split Count'),
        ),
        migrations.AddField(
            model_name='splitpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL_COMPLETED', 'Partially Completed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='splitpaymentcomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount for this component.', max_digits=15, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='splitpaymentcomponent',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE', 'Mobile Payment'), ('CHECK', 'Check'), ('STORE_CREDIT', 'Store Credit')], default='', help_text='Payment method for this component.', max_length=30, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='splitpaymentcomponent',
            name='method_details',
            field=models.JSONField(blank=True, default=dict, help_text='Method-specific details (card type, bank name, etc.).', verbose_name='Method Details'),
        ),
        migrations.AddField(
            model_name='splitpaymentcomponent',
            name='sequence',
            field=models.IntegerField(default=0, help_text='Display ordering of this component.', verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='paymentplaninstallment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount due for this installment.', max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='paymentplaninstallment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='splitpaymentcomponent',
            name='order_index',
            field=models.IntegerField(default=0, help_text='Display ordering of this component (legacy).', verbose_name='Order'),
        ),
    ]
