# Generated by Django 5.2.11 on 2026-03-17 09:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0007_sp06_audit_group_c'),
        ('payments', '0008_sp07_audit_group_c'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(db_index=True, default='NOT_REFUNDED', help_text='NOT_REFUNDED, PARTIALLY_REFUNDED, or FULLY_REFUNDED.', max_length=25, verbose_name='Refund Status'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total amount refunded from this payment.', max_digits=15, verbose_name='Total Refunded'),
        ),
        migrations.AddField(
            model_name='refund',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='refund',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='refund',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Bank Branch'),
        ),
        migrations.AddField(
            model_name='refund',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='refund',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Check Date'),
        ),
        migrations.AddField(
            model_name='refund',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Check Number'),
        ),
        migrations.AddField(
            model_name='refund',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When refund was fully completed.', null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='refund',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer receiving the refund.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='refund',
            name='customer_notes',
            field=models.TextField(blank=True, default='', help_text='Notes visible to the customer.', verbose_name='Customer Notes'),
        ),
        migrations.AddField(
            model_name='refund',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice related to this refund.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='invoices.invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='refund',
            name='reference_number',
            field=models.CharField(blank=True, default='', help_text='Bank/payment processor reference number.', max_length=100, verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='refund',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (if rejected).', verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='refund',
            name='store_credit_id',
            field=models.CharField(blank=True, default='', help_text='Store credit ID created for this refund.', max_length=100, verbose_name='Store Credit ID'),
        ),
        migrations.AddField(
            model_name='refund',
            name='transaction_id',
            field=models.CharField(blank=True, default='', help_text='External refund transaction ID (payment gateway).', max_length=200, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(choices=[('CUSTOMER_REQUEST', 'Customer Request'), ('OVERPAYMENT', 'Overpayment'), ('DUPLICATE', 'Duplicate Payment'), ('CANCELLED', 'Order Cancelled'), ('RETURN', 'Goods Return'), ('DEFECTIVE', 'Defective Product'), ('LATE_DELIVERY', 'Delivery Issues'), ('PRICING_ERROR', 'Pricing Error'), ('SERVICE_ISSUE', 'Service Not Rendered'), ('BILLING_ERROR', 'Billing Error'), ('GOODWILL', 'Goodwill Gesture'), ('OTHER', 'Other')], max_length=30, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_method',
            field=models.CharField(choices=[('ORIGINAL', 'Original Payment Method'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('STORE_CREDIT', 'Store Credit')], default='ORIGINAL', max_length=20, verbose_name='Refund Method'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['customer', '-created_on'], name='idx_refund_customer'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['invoice'], name='idx_refund_invoice'),
        ),
    ]
