# Generated by Django 5.2.11 on 2026-03-17 10:23

import apps.payments.models.payment_receipt
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_sp07_audit_group_d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.payments.models.payment_receipt.receipt_pdf_path),
        ),
    ]
