# Generated by Django 5.2.11 on 2026-03-25 01:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_departmentmember_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text="Human-readable leave type name (e.g. 'Annual Leave').", max_length=100)),
                ('code', models.CharField(help_text="Short uppercase code (e.g. 'AL'). Unique per tenant.", max_length=10)),
                ('category', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('NO_PAY', 'No-Pay Leave'), ('OTHER', 'Other')], help_text='Leave category aligned with Sri Lankan labor law.', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description, rules, and usage guidelines.')),
                ('color', models.CharField(default='#2196F3', help_text="Hex color code for calendar/UI display (e.g. '#4CAF50').", max_length=7)),
                ('default_days_per_year', models.PositiveIntegerField(blank=True, help_text='Default annual entitlement in days. Can be overridden by policy.', null=True)),
                ('max_consecutive_days', models.PositiveIntegerField(blank=True, help_text='Maximum consecutive days allowed in a single stretch.', null=True)),
                ('max_days_per_request', models.PositiveIntegerField(blank=True, help_text='Maximum days allowed per leave request.', null=True)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this leave type is paid.')),
                ('requires_document', models.BooleanField(default=False, help_text='Whether supporting documents are required.')),
                ('document_after_days', models.PositiveIntegerField(default=0, help_text='Number of consecutive days after which a document is required.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this leave type is available for new applications.')),
                ('allow_half_day', models.BooleanField(default=True, help_text='Whether half-day leave is allowed for this type.')),
                ('applicable_gender', models.CharField(choices=[('ALL', 'All Genders'), ('MALE', 'Male Only'), ('FEMALE', 'Female Only')], default='ALL', help_text='Gender restriction for this leave type.', max_length=10)),
                ('min_service_months', models.PositiveIntegerField(default=0, help_text='Minimum months of service required for eligibility.')),
                ('min_notice_days', models.PositiveIntegerField(default=0, help_text='Minimum days of advance notice required before leave start.')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='leave_type_category_idx'), models.Index(fields=['is_active'], name='leave_type_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text="Human-readable policy name (e.g. 'Sales Dept Annual Leave Policy').", max_length=200)),
                ('days_per_year', models.PositiveIntegerField(blank=True, help_text="Override for the leave type's default_days_per_year. Null uses default.", null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this policy is currently active.')),
                ('applies_to', models.CharField(choices=[('ALL', 'All Employees'), ('DEPARTMENT', 'Specific Department'), ('DESIGNATION', 'Specific Designation')], default='ALL', help_text='Target group for this policy.', max_length=20)),
                ('effective_from', models.DateField(help_text='Date from which this policy is effective.')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this policy is effective. Null means no expiry.', null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Target department (required when applies_to=DEPARTMENT).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='organization.department')),
                ('designation', models.ForeignKey(blank=True, help_text='Target designation (required when applies_to=DESIGNATION).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='organization.designation')),
                ('leave_type', models.ForeignKey(help_text='The leave type this policy applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leave.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['leave_type'], name='leave_policy_type_idx'), models.Index(fields=['is_active'], name='leave_policy_active_idx')],
            },
        ),
    ]
