# Generated by Django 5.2.11 on 2026-03-25 01:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('year', models.PositiveIntegerField(db_index=True, help_text='Calendar year (e.g. 2026).', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance at year start.', max_digits=6)),
                ('allocated_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Days accrued/granted during the year.', max_digits=6)),
                ('carried_from_previous', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Days carried over from the previous year.', max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total approved leave days taken.', max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Days in approval process (pending applications).', max_digits=6)),
                ('encashed_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Days converted to cash.', max_digits=6)),
                ('carry_forward_expiry', models.DateField(blank=True, help_text='Date when carried-forward days expire.', null=True)),
                ('last_accrual_date', models.DateField(blank=True, help_text='Date of the last accrual calculation.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this balance record is current.')),
                ('employee', models.ForeignKey(help_text='Employee this balance belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(help_text='Leave type for this balance.', on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='leave.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'ordering': ['-year', 'employee', 'leave_type'],
                'indexes': [models.Index(fields=['employee', 'year'], name='leave_bal_emp_year_idx'), models.Index(fields=['leave_type', 'year', 'is_active'], name='leave_bal_type_year_idx'), models.Index(fields=['carry_forward_expiry', 'is_active'], name='leave_bal_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_employee_leavetype_year')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=2, help_text='Total leave days requested (auto-calculated or manual).', max_digits=5)),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_type', models.CharField(blank=True, choices=[('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half')], help_text='Required when is_half_day is True.', max_length=20, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('contact_during_leave', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('RECALLED', 'Recalled')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_docs/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('recalled_at', models.DateTimeField(blank=True, null=True)),
                ('recalled_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status'], name='idx_leavereq_status'), models.Index(fields=['employee', 'status'], name='idx_leavereq_emp_status')],
            },
        ),
    ]
