# Generated by Django 5.2.11 on 2026-03-25 01:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavebalance_leaverequest'),
        ('organization', '0004_departmentmember_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('PUBLIC', 'Public Holiday'), ('BANK', 'Bank Holiday'), ('COMPANY', 'Company Holiday'), ('OPTIONAL', 'Optional Holiday')], default='PUBLIC', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to', models.CharField(choices=[('ALL', 'All Employees'), ('DEPARTMENT', 'Department Only'), ('LOCATION', 'Location Only')], default='ALL', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='RRULE format (RFC 5545).', max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.department')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='idx_holiday_date'), models.Index(fields=['is_active'], name='idx_holiday_active'), models.Index(fields=['applies_to'], name='idx_holiday_scope'), models.Index(fields=['department', 'date'], name='idx_holiday_dept_date'), models.Index(fields=['is_recurring'], name='idx_holiday_recurring')],
            },
        ),
    ]
