# Generated by Django 5.2.11 on 2026-03-26 03:46

import apps.payslip.models.payslip
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_alter_employee_department_alter_employee_designation'),
        ('payroll', '0010_sp06_audit_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('slip_number', models.CharField(db_index=True, help_text='Auto-generated slip number (PAY-YYYY-MM-NNN).', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('DOWNLOADED', 'Downloaded')], db_index=True, default='DRAFT', help_text='Current lifecycle status of the payslip.', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the PDF was generated.', null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF payslip document.', null=True, upload_to=apps.payslip.models.payslip.payslip_upload_to)),
                ('email_sent', models.BooleanField(db_index=True, default=False, help_text='Whether the payslip email has been sent.')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the payslip email was sent.', null=True)),
                ('sent_to', models.EmailField(blank=True, help_text='Email address the payslip was sent to.', max_length=254, null=True)),
                ('first_viewed_at', models.DateTimeField(blank=True, help_text='When the employee first viewed this payslip.', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times the employee viewed this payslip.')),
                ('first_downloaded_at', models.DateTimeField(blank=True, help_text='When the employee first downloaded this payslip.', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times the employee downloaded this payslip.')),
                ('employee', models.ForeignKey(help_text='Employee this payslip belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('employee_payroll', models.ForeignKey(help_text='Source payroll calculation data.', on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.employeepayroll')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who triggered PDF generation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payslips', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(help_text='Payroll period this payslip covers.', on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'db_table': 'payslip_payslip',
                'ordering': ['-payroll_period__period_year', '-payroll_period__period_month'],
                'indexes': [models.Index(fields=['status', 'email_sent'], name='idx_payslip_status_email')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'payroll_period'), name='unique_employee_payroll_period_payslip')],
            },
        ),
    ]
