# Generated by Django 5.2.11 on 2026-03-26 03:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial_payslip_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently in use.')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes about this template configuration.', null=True)),
                ('company_name', models.CharField(help_text='Company name displayed on payslip header.', max_length=200)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo for payslip header (PNG/JPG, max 2MB).', null=True, upload_to='payslip_templates/logos/')),
                ('company_address', models.TextField(help_text='Company address displayed on payslip header.')),
                ('company_phone', models.CharField(blank=True, help_text='Company phone (e.g. +94 11 234 5678).', max_length=20, null=True)),
                ('company_email', models.EmailField(blank=True, help_text='HR contact email for payslip queries.', max_length=100, null=True)),
                ('epf_number', models.CharField(blank=True, help_text="Employees' Provident Fund registration number.", max_length=50, null=True)),
                ('etf_number', models.CharField(blank=True, help_text="Employees' Trust Fund registration number.", max_length=50, null=True)),
                ('footer_text', models.TextField(blank=True, help_text='General footer text (contact info, portal links).', null=True)),
                ('disclaimer_text', models.TextField(blank=True, help_text='Legal disclaimer / confidentiality notice.', null=True)),
                ('show_footer', models.BooleanField(default=True, help_text='Display footer section on payslip.')),
                ('show_disclaimer', models.BooleanField(default=True, help_text='Display disclaimer section on payslip.')),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210mm × 297mm)'), ('LETTER', 'US Letter (8.5" × 11")')], default='A4', help_text='Paper size for PDF generation.', max_length=10)),
                ('primary_color', models.CharField(default='#2C3E50', help_text='Hex color for headers/accents (e.g. #2C3E50).', max_length=7)),
                ('secondary_color', models.CharField(default='#7F8C8D', help_text='Hex color for subheadings/borders (e.g. #7F8C8D).', max_length=7)),
                ('show_employer_contributions', models.BooleanField(default=False, help_text='Show employer EPF/ETF contributions on payslip.')),
                ('show_ytd', models.BooleanField(default=True, help_text='Show year-to-date totals for earnings/deductions.')),
                ('show_bank_details', models.BooleanField(default=True, help_text='Show employee bank account details on payslip.')),
            ],
            options={
                'verbose_name': 'Payslip Template',
                'verbose_name_plural': 'Payslip Templates',
            },
        ),
        migrations.CreateModel(
            name='PayslipDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('component_code', models.CharField(db_index=True, help_text='System identifier (e.g. EPF_EMPLOYEE, PAYE).', max_length=20)),
                ('component_name', models.CharField(help_text='Display name (e.g. EPF - Employee Contribution).', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Deduction amount for this period.', max_digits=12)),
                ('ytd_amount', models.DecimalField(decimal_places=2, default=0, help_text='Year-to-date total for this component.', max_digits=14)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order on the payslip.')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Whether to highlight this deduction on the PDF.')),
                ('payslip', models.ForeignKey(help_text='Payslip this deduction belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payslip.payslip')),
            ],
            options={
                'verbose_name': 'Payslip Deduction',
                'verbose_name_plural': 'Payslip Deductions',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('payslip', 'component_code'), name='unique_deduction_component_per_payslip')],
            },
        ),
        migrations.CreateModel(
            name='PayslipEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('component_code', models.CharField(db_index=True, help_text='System identifier (e.g. BASIC, TRANSPORT).', max_length=20)),
                ('component_name', models.CharField(help_text='Display name (e.g. Basic Salary).', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Earning amount for this period.', max_digits=12)),
                ('ytd_amount', models.DecimalField(decimal_places=2, default=0, help_text='Year-to-date total for this component.', max_digits=14)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order on the payslip.')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Whether to highlight this earning on the PDF.')),
                ('payslip', models.ForeignKey(help_text='Payslip this earning belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='payslip.payslip')),
            ],
            options={
                'verbose_name': 'Payslip Earning',
                'verbose_name_plural': 'Payslip Earnings',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('payslip', 'component_code'), name='unique_earning_component_per_payslip')],
            },
        ),
        migrations.CreateModel(
            name='PayslipEmployerContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('component_code', models.CharField(db_index=True, help_text='System identifier (e.g. EPF_EMPLOYER, ETF).', max_length=20)),
                ('component_name', models.CharField(help_text='Display name (e.g. EPF - Employer Contribution).', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Contribution amount for this period.', max_digits=12)),
                ('ytd_amount', models.DecimalField(decimal_places=2, default=0, help_text='Year-to-date total for this component.', max_digits=14)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order on the payslip.')),
                ('payslip', models.ForeignKey(help_text='Payslip this contribution belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='employer_contributions', to='payslip.payslip')),
            ],
            options={
                'verbose_name': 'Payslip Employer Contribution',
                'verbose_name_plural': 'Payslip Employer Contributions',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('payslip', 'component_code'), name='unique_employer_contrib_per_payslip')],
            },
        ),
    ]
