# Generated by Django 5.2.11 on 2026-03-26 04:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_sp06_audit_enhancements'),
        ('payslip', '0002_group_b_line_items_and_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('batch_type', models.CharField(choices=[('GENERATION', 'PDF Generation'), ('EMAIL', 'Email Distribution')], help_text='Type of batch operation.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed')], db_index=True, default='PENDING', help_text='Current batch status.', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total payslips in this batch.')),
                ('success_count', models.PositiveIntegerField(default=0, help_text='Successfully processed payslips.')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Failed payslips in this batch.')),
                ('error_log', models.TextField(blank=True, help_text='Error details for failed items.', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When batch processing started.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When batch processing completed.', null=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_batches', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(help_text='Payroll period for this batch.', on_delete=django.db.models.deletion.CASCADE, related_name='payslip_batches', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Payslip Batch',
                'verbose_name_plural': 'Payslip Batches',
                'ordering': ['-created_on'],
            },
        ),
    ]
