# Generated by Django 5.2.11 on 2026-03-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0003_group_d_payslip_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipdeduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deduction amount for this period.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payslipdeduction',
            name='ytd_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Year-to-date total for this component.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payslipearning',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Earning amount for this period.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payslipearning',
            name='ytd_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Year-to-date total for this component.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payslipemployercontribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Contribution amount for this period.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payslipemployercontribution',
            name='ytd_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Year-to-date total for this component.', max_digits=15),
        ),
    ]
