# Generated by Django 5.2.11 on 2026-02-21 12:46

import apps.products.models.category
import apps.products.models.image
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(help_text='Display name of the category.', max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Unique per tenant.', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description for the category.', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Optional image for category branding.', null=True, upload_to=apps.products.models.category.category_image_upload_path, verbose_name='Category Image')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Controls category visibility on the storefront.', verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order. Lower values appear first.', verbose_name='Sort Order')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category. Null for root categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'products_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('name', models.CharField(help_text='Display name of the product.', max_length=255, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Unique per tenant.', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed product description.', verbose_name='Description')),
                ('sku', models.CharField(help_text='Stock Keeping Unit. Unique per tenant.', max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, db_index=True, default='', help_text='Product barcode (EAN-13, UPC-A, or custom format).', max_length=50, verbose_name='Barcode')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Purchase cost from supplier in LKR.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost Price (₨)')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='Standard selling price in LKR.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Selling Price (₨)')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price in LKR. Common in Sri Lankan retail.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='MRP (₨)')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Bulk/wholesale purchase price in LKR.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wholesale Price (₨)')),
                ('tax_type', models.CharField(choices=[('none', 'No Tax'), ('standard', 'Standard Rate'), ('reduced', 'Reduced Rate'), ('exempt', 'Tax Exempt'), ('zero_rated', 'Zero Rated')], default='standard', help_text='Tax classification for Sri Lankan VAT.', max_length=20, verbose_name='Tax Type')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18, help_text='Tax rate percentage. Default: 18% (Sri Lankan standard VAT).', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax Rate (%)')),
                ('is_tax_inclusive', models.BooleanField(default=False, help_text='Whether the selling price includes tax.', verbose_name='Tax Inclusive')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], db_index=True, default='draft', help_text='Product lifecycle status.', max_length=20, verbose_name='Status')),
                ('category', models.ForeignKey(blank=True, help_text='Product category. Products remain if category is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products_product',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('image', models.ImageField(help_text='Product image file.', upload_to=apps.products.models.image.product_image_upload_path, verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Alternative text for accessibility.', max_length=255, verbose_name='Alt Text')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the main product image.', verbose_name='Primary Image')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order. Lower values appear first.', verbose_name='Sort Order')),
                ('product', models.ForeignKey(help_text='The product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'products_productimage',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('attribute_type', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('weight', 'Weight'), ('custom', 'Custom')], default='size', help_text='Type of variation (size, color, etc.).', max_length=20, verbose_name='Attribute Type')),
                ('attribute_value', models.CharField(help_text="Specific value (e.g., 'XL', 'Red', '500g').", max_length=100, verbose_name='Attribute Value')),
                ('sku', models.CharField(help_text='Variant-specific SKU. Unique per tenant.', max_length=50, unique=True, verbose_name='Variant SKU')),
                ('barcode', models.CharField(blank=True, default='', help_text='Variant-specific barcode.', max_length=50, verbose_name='Variant Barcode')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override selling price for this variant. Null uses product price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price Override (₨)')),
                ('cost_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override cost price for this variant. Null uses product cost.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost Override (₨)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this variant is currently available.', verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order. Lower values appear first.', verbose_name='Sort Order')),
                ('product', models.ForeignKey(help_text='The parent product this variant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'products_productvariant',
                'ordering': ['sort_order', 'attribute_type'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='idx_category_active_sort'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='idx_category_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'created_on'], name='idx_product_status_created'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='idx_product_category_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='idx_product_sku'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='idx_prodimg_product_primary'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'attribute_type'], name='idx_variant_product_attr'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='idx_variant_sku'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'attribute_type', 'attribute_value'), name='uq_variant_product_attr_value'),
        ),
    ]
