# Generated by Django 5.2.11 on 2026-03-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_upgrade_category_mptt'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='idx_category_parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Controls display order. Lower values appear first.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Display name of the category.', max_length=255, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Meta description for search results (155 chars optimal).', max_length=200, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated keywords (optional, legacy SEO).', max_length=255, verbose_name='SEO Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Meta title for search engines (60 chars optimal).', max_length=100, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier. Unique per tenant schema.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='idx_category_slug'),
        ),
    ]
