# Generated by Django 5.2.11 on 2026-03-12 04:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_display_order_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(db_index=True, help_text='Name of the brand or manufacturer (e.g., Apple, Samsung).', max_length=100, verbose_name='Brand Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank).', max_length=100, unique=True, verbose_name='URL Slug')),
                ('logo', models.ImageField(blank=True, help_text='Brand logo image (recommended: 500x500px, square aspect ratio).', null=True, upload_to='brands/logos/', verbose_name='Brand Logo')),
                ('description', models.TextField(blank=True, default='', help_text='Brand description for webstore display (supports HTML formatting).', verbose_name='Description')),
                ('website', models.URLField(blank=True, default='', help_text="Brand's official website URL (e.g., https://www.apple.com).", verbose_name='Official Website')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'products_brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text='Name of the tax class (e.g., Standard VAT, Zero-rated).', max_length=50, verbose_name='Tax Class Name')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate as percentage (e.g., 15.00 for 15% VAT).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Tax Rate (%)')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description for this tax class.', verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, help_text='Mark as default tax class for new products. Only one tax class should be default per tenant.', verbose_name='Default Tax Class')),
            ],
            options={
                'verbose_name': 'Tax Class',
                'verbose_name_plural': 'Tax Classes',
                'db_table': 'products_tax_class',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(help_text='Full name of the unit (e.g., Kilogram, Piece, Liter).', max_length=50, verbose_name='Unit Name')),
                ('symbol', models.CharField(help_text='Unit abbreviation or symbol (e.g., kg, pcs, l).', max_length=10, verbose_name='Symbol')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of when to use this unit.', verbose_name='Description')),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, help_text='Conversion factor to base unit (e.g., 1 g = 0.001 kg). Leave blank if not applicable.', max_digits=10, null=True, verbose_name='Conversion Factor')),
                ('is_base_unit', models.BooleanField(default=False, help_text='Mark as base unit for conversions in this category.', verbose_name='Base Unit')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'db_table': 'products_unit_of_measure',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_on', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_status_created',
            old_name='idx_product_status_created',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_category_status',
            old_name='idx_product_category_status',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_sku',
            old_name='idx_product_sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_tax_inclusive',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_type',
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='product',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on'),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as featured for display on homepage and promotions', verbose_name='Featured Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product height in centimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pos_visible',
            field=models.BooleanField(default=True, help_text='Show product in POS system. Product must also be Active. Use this to hide online-only products from POS.', verbose_name='POS Visible'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_webstore_visible',
            field=models.BooleanField(default=True, help_text='Show product in webstore. Product must also be Active. Use this to hide products from webstore while keeping in POS.', verbose_name='Webstore Visible'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product length in centimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Length (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple Product'), ('variable', 'Variable Product'), ('bundle', 'Bundle'), ('composite', 'Composite Product')], default='simple', help_text='Type determines product behavior: Simple (single item), Variable (with variants), Bundle (collection), Composite (BOM)', max_length=20, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Meta description for search engines (150-160 chars optimal). Defaults to short description if blank.', max_length=160, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Page title for search engines (50-60 chars optimal). Defaults to product name if blank.', max_length=70, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Brief product summary for listings and search results (max 500 characters). Plain text only, no HTML.', max_length=500, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Product weight in kilograms (e.g., 1.500 for 1.5kg)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product width in centimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Width (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Product barcode for scanning (EAN-13, UPC-A, or Code-128). Leave blank if product has no barcode.', max_length=50, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Product category for organization and filtering', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Full product description with features and specifications. Supports HTML formatting for rich content display.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text='Full product name as displayed to customers', max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit — unique product identifier (auto-generated if left blank). Example: PRD-A1B2C', max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL identifier (auto-generated from name if left blank). Example: apple-iphone-15-pro', max_length=200, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('discontinued', 'Discontinued')], db_index=True, default='draft', help_text='Product status: Draft (not visible), Active (published), Archived (hidden), Discontinued (unavailable)', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Product brand or manufacturer (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='taxclass',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='taxclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.ForeignKey(blank=True, help_text='Tax rate applied to this product (e.g., Standard VAT 15%). Used for price calculations and tax reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.taxclass', verbose_name='Tax Class'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, help_text='How product quantity is measured (e.g., Piece, Kilogram, Liter). Used in inventory tracking and display.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='product_type_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured'], name='product_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='products_br_slug_d4d839_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active'], name='products_br_is_acti_297ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='taxclass',
            index=models.Index(fields=['is_default'], name='products_ta_is_defa_a6e2de_idx'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['symbol'], name='products_un_symbol_a43f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['is_active'], name='products_un_is_acti_04bf59_idx'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['is_base_unit'], name='products_un_is_base_f37a44_idx'),
        ),
    ]
