# Generated by Django 5.2.11 on 2026-03-12 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sp03_product_base_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_pos_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Show product in POS system. Product must also be Active. Use this to hide online-only products from POS.', verbose_name='POS Visible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_webstore_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Show product in webstore. Product must also be Active. Use this to hide products from webstore while keeping in POS.', verbose_name='Webstore Visible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Meta description for search engines (150-160 chars optimal). Defaults to short description if blank.', max_length=300, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Page title for search engines (50-60 chars optimal). Defaults to product name if blank.', max_length=100, verbose_name='SEO Title'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_webstore_visible'], name='product_published_idx'),
        ),
    ]
