# Generated by Django 5.2.11 on 2026-03-12 10:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sp03_audit_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantOptionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('name', models.CharField(db_index=True, help_text='Name of the variant option type (e.g., Size, Color, Material)', max_length=100, verbose_name='Option Type Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name)', max_length=100, unique=True, verbose_name='URL Slug')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this option type appears (lower numbers first)', verbose_name='Display Order')),
                ('is_color_swatch', models.BooleanField(default=False, help_text='If True, option values will display as color swatches', verbose_name='Display as Color Swatch')),
                ('is_image_swatch', models.BooleanField(default=False, help_text='If True, option values will display as image swatches', verbose_name='Display as Image Swatch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Variant Option Type',
                'verbose_name_plural': 'Variant Option Types',
                'db_table': 'products_variantoptiontype',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantOptionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('value', models.CharField(help_text="Internal value identifier (e.g., 's', 'red', '8gb')", max_length=100, verbose_name='Value')),
                ('label', models.CharField(blank=True, default='', help_text="Display label for this value (e.g., 'Small', 'Red', '8GB RAM')", max_length=150, verbose_name='Display Label')),
                ('color_code', models.CharField(blank=True, default='', help_text='Hex color code (e.g., #FF0000 for red). Required if option type is color swatch', max_length=7, verbose_name='Color Code')),
                ('image', models.ImageField(blank=True, help_text='Swatch image for visual selection. Required if option type uses image swatches', null=True, upload_to='variant_option_swatches/', verbose_name='Swatch Image')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this value appears (lower numbers first)', verbose_name='Display Order')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('option_type', models.ForeignKey(help_text='The variant option type this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.variantoptiontype', verbose_name='Option Type')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Variant Option Value',
                'verbose_name_plural': 'Variant Option Values',
                'db_table': 'products_variantoptionvalue',
                'ordering': ['option_type', 'display_order', 'value'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='variantoptiontype',
            index=models.Index(fields=['slug'], name='varopttype_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoptiontype',
            index=models.Index(fields=['display_order', 'name'], name='varopttype_order_name_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoptiontype',
            index=models.Index(fields=['is_active'], name='varopttype_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='variantoptiontype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_variantoptiontype_name'),
        ),
        migrations.AddIndex(
            model_name='variantoptionvalue',
            index=models.Index(fields=['option_type', 'display_order'], name='varoptval_type_order_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoptionvalue',
            index=models.Index(fields=['value'], name='varoptval_value_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantoptionvalue',
            unique_together={('option_type', 'value')},
        ),
    ]
