# Generated by Django 5.2.11 on 2026-03-12 11:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_sp04_variant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this option type appears in the UI (lower numbers first)', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Product Option Configuration',
                'verbose_name_plural': 'Product Option Configurations',
                'db_table': 'products_productoptionconfig',
                'ordering': ['product', 'display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls option display order within the variant', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Variant Option',
                'verbose_name_plural': 'Variant Options',
                'db_table': 'products_productvariantoption',
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'sort_order', 'name'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='uq_variant_product_attr_value',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='idx_variant_product_attr',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='prodvar_sku_idx',
            old_name='idx_variant_sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='cost_override',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_override',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override product height for this variant (cm)', max_digits=10, null=True, verbose_name='Height Override'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override product length for this variant (cm)', max_digits=10, null=True, verbose_name='Length Override'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Display name for this variant (auto-generated from options if blank)', max_length=255, verbose_name='Variant Name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_override',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Override product weight for this variant (kg). Leave empty to use product weight', max_digits=10, null=True, verbose_name='Weight Override'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override product width for this variant (cm)', max_digits=10, null=True, verbose_name='Width Override'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, default='', help_text='Barcode for this variant (EAN-13, UPC, etc.)', max_length=100, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(help_text='The parent product this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(help_text='Unique Stock Keeping Unit for this variant', max_length=100, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this variant appears (lower numbers first)', verbose_name='Sort Order'),
        ),
        migrations.AddField(
            model_name='productoptionconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productoptionconfig',
            name='option_type',
            field=models.ForeignKey(help_text='Option type applicable to this product', on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='products.variantoptiontype', verbose_name='Option Type'),
        ),
        migrations.AddField(
            model_name='productoptionconfig',
            name='product',
            field=models.ForeignKey(help_text='Product this option configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='option_configs', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productoptionconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='option_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_options', to='products.variantoptionvalue', verbose_name='Option Value'),
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='products.productvariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='option_values',
            field=models.ManyToManyField(blank=True, help_text='Option values that define this variant', related_name='product_variants', through='products.ProductVariantOption', to='products.variantoptionvalue', verbose_name='Option Values'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='prodvar_product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'sort_order'], name='prodvar_product_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('sku',), name='unique_productvariant_sku'),
        ),
        migrations.AddConstraint(
            model_name='productoptionconfig',
            constraint=models.UniqueConstraint(fields=('product', 'option_type'), name='unique_product_option_config'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantoption',
            unique_together={('variant', 'option_value')},
        ),
    ]
