# Generated by Django 5.2.11 on 2026-03-12 22:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sp04_product_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('bundle_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('dynamic', 'Dynamic Price')], db_index=True, default='dynamic', help_text='Pricing strategy: fixed price or dynamic from components', max_length=20, verbose_name='Bundle Type')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text="Fixed bundle price (used when bundle_type is 'fixed')", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Fixed Price')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('none', 'No Discount')], db_index=True, default='none', help_text='Type of discount applied to dynamic pricing', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount amount (percentage or fixed based on discount_type)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount Value')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('product', models.OneToOneField(help_text='The base product this bundle configuration belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='bundle', to='products.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Product Bundle',
                'verbose_name_plural': 'Product Bundles',
                'db_table': 'products_bundle',
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of this product included in the bundle', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('is_optional', models.BooleanField(db_index=True, default=False, help_text='Whether this item is optional in the bundle', verbose_name='Optional')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order within the bundle', verbose_name='Sort Order')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('product', models.ForeignKey(help_text='The component product in this bundle', on_delete=django.db.models.deletion.PROTECT, related_name='bundle_items', to='products.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('variant', models.ForeignKey(blank=True, help_text='Specific variant of the product (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bundle_items', to='products.productvariant', verbose_name='Variant')),
                ('bundle', models.ForeignKey(help_text='The bundle this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productbundle', verbose_name='Bundle')),
            ],
            options={
                'verbose_name': 'Bundle Item',
                'verbose_name_plural': 'Bundle Items',
                'db_table': 'products_bundle_item',
                'ordering': ['sort_order', 'product__name'],
                'abstract': False,
                'indexes': [models.Index(fields=['bundle', 'is_optional'], name='idx_bundleitem_bundle_optional')],
                'constraints': [models.UniqueConstraint(fields=('bundle', 'product', 'variant'), name='unique_bundle_product_variant')],
            },
        ),
    ]
