# Generated by Django 5.2.11 on 2026-03-12 22:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_sp05_bundle_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('version', models.CharField(default='1.0', help_text='BOM version identifier (e.g., 1.0, 2.1, v3)', max_length=20, verbose_name='Version')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this BOM version is currently in use', verbose_name='Active')),
                ('notes', models.TextField(blank=True, help_text='Manufacturing instructions and notes', null=True, verbose_name='Notes')),
                ('yield_quantity', models.PositiveIntegerField(default=1, help_text='Number of units produced per batch', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Yield Quantity')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('product', models.ForeignKey(help_text='The composite product this BOM belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='products.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
                'db_table': 'products_bom',
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('deactivated_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was deactivated.', null=True, verbose_name='Deactivated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Required quantity of this material per batch', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantity')),
                ('wastage_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of material lost during manufacturing (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Wastage %')),
                ('is_critical', models.BooleanField(default=False, help_text='Whether this is an essential component with no substitutes', verbose_name='Critical Component')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within the BOM', verbose_name='Sort Order')),
                ('bom', models.ForeignKey(help_text='The Bill of Materials this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.billofmaterials', verbose_name='BOM')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('raw_material', models.ForeignKey(help_text='The raw material product used in manufacturing', on_delete=django.db.models.deletion.PROTECT, related_name='bom_usages', to='products.product', verbose_name='Raw Material')),
                ('substitute', models.ForeignKey(blank=True, help_text='Alternative material when primary is unavailable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_for', to='products.product', verbose_name='Substitute Material')),
                ('unit', models.ForeignKey(blank=True, help_text='Unit of measure for this material', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='products.unitofmeasure', verbose_name='Unit of Measure')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'verbose_name_plural': 'BOM Items',
                'db_table': 'products_bom_item',
                'ordering': ['sort_order', 'raw_material__name'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='billofmaterials',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_product_bom_version'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.UniqueConstraint(fields=('bom', 'raw_material'), name='unique_bom_raw_material'),
        ),
    ]
