# Generated by Django 5.2.11 on 2026-03-13 09:52

import apps.products.media.utils
import apps.products.media.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sp05_bom_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.TextField(blank=True, default='', help_text='Image caption or description.', verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order of image in gallery (lower numbers first).', verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='File size in bytes (auto-populated).', null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Image height in pixels (auto-populated).', null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='large_path',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='medium_path',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='original_filename',
            field=models.CharField(blank=True, default='', editable=False, help_text='Original filename when uploaded.', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of image variant processing.', max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_path',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Image title (displayed on hover).', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Image width in pixels (auto-populated).', null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Alternative text for accessibility (screen readers).', max_length=255, verbose_name='Alt Text'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Product image file (JPEG, PNG, WebP, or GIF).', max_length=500, upload_to=apps.products.media.utils.product_image_upload_path, validators=[apps.products.media.validators.validate_image_file_type, apps.products.media.validators.validate_image_file_size, apps.products.media.validators.validate_image_dimensions], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, help_text='Designate as the main product image.', verbose_name='Primary Image'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'display_order'], name='idx_prodimg_product_order'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'is_primary'), name='unique_primary_per_product'),
        ),
    ]
