# Generated by Django 5.2.11 on 2026-03-13 10:32

import apps.products.media.utils
import apps.products.media.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sp07_product_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('image', models.ImageField(help_text='Variant image file (JPEG, PNG, WebP, or GIF).', max_length=500, upload_to=apps.products.media.utils.variant_image_upload_path, validators=[apps.products.media.validators.validate_image_file_type, apps.products.media.validators.validate_image_file_size, apps.products.media.validators.validate_image_dimensions], verbose_name='Image')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order of image in gallery (lower numbers first).', verbose_name='Display Order')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Designate as the main variant image.', verbose_name='Primary Image')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.TextField(blank=True, default='')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('original_filename', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('thumbnail_path', models.CharField(blank=True, default='', editable=False, max_length=500)),
                ('medium_path', models.CharField(blank=True, default='', editable=False, max_length=500)),
                ('large_path', models.CharField(blank=True, default='', editable=False, max_length=500)),
                ('variant', models.ForeignKey(help_text='The product variant this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Variant Image',
                'verbose_name_plural': 'Variant Images',
                'db_table': 'products_variant_images',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['variant', 'display_order'], name='idx_varimg_variant_order'), models.Index(fields=['variant', 'is_primary'], name='idx_varimg_variant_primary')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('variant', 'is_primary'), name='unique_primary_per_variant')],
            },
        ),
    ]
