# Generated by Django 5.2.11 on 2026-03-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_sp07_webp_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order', 'id'], 'permissions': [('can_upload_images', 'Can upload product images'), ('can_delete_images', 'Can delete product images'), ('can_set_primary', 'Can set primary product image')], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['created_on'], name='idx_prodimg_created_on'),
        ),
    ]
