# Generated by Django 5.2.11 on 2026-03-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sp07_admin_index_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error details when processing fails.'),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error details when processing fails.'),
        ),
    ]
