# Generated by Django 5.2.11 on 2026-02-21 12:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.', verbose_name='Deleted')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted on')),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique invoice identifier within the tenant. Uses tenant-specific prefix + sequence.', max_length=50, unique=True, verbose_name='Invoice Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current status in the invoice lifecycle.', max_length=20, verbose_name='Invoice Status')),
                ('invoice_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time the invoice was issued.', verbose_name='Invoice Date')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date for this invoice.', null=True, verbose_name='Due Date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line item amounts before tax and discount.', max_digits=10, verbose_name='Subtotal (LKR)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount for the invoice.', max_digits=10, verbose_name='Tax Amount (LKR)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount applied to the invoice.', max_digits=10, verbose_name='Discount Amount (LKR)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final amount due (subtotal + tax - discount).', max_digits=10, verbose_name='Total Amount (LKR)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount received via payments.', max_digits=10, verbose_name='Amount Paid (LKR)')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this invoice.', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(help_text='The customer being billed.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='Customer')),
                ('order', models.ForeignKey(blank=True, help_text='Optional link to the order being invoiced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'sales_invoice',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.', verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.', verbose_name='Updated on')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile', 'Mobile Payment')], db_index=True, default='cash', help_text='Method of payment (cash, card, bank transfer, cheque, mobile).', max_length=20, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in LKR (₨). Must be greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount (LKR)')),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time the payment was received.', verbose_name='Payment Date')),
                ('reference_number', models.CharField(blank=True, default='', help_text='Transaction or cheque reference number. Optional for cash payments.', max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this payment.', verbose_name='Notes')),
                ('invoice', models.ForeignKey(help_text='The invoice this payment is applied to.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.invoice', verbose_name='Invoice')),
                ('received_by', models.ForeignKey(blank=True, help_text='The user who recorded this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'sales_payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'invoice_date'], name='idx_invoice_status_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='idx_invoice_customer_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-invoice_date'], name='idx_invoice_date_desc'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='idx_invoice_due_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_method'], name='idx_payment_invoice_method'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='idx_payment_date_desc'),
        ),
    ]
