# Generated by Django 5.2.11 on 2026-03-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0010_sp05_group_e_audit_fields'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(help_text='The customer being billed.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Optional link to the order being invoiced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='orders.order', verbose_name='Order'),
        ),
    ]
